### ISSUE TITLE
Cascading destroy when deleting flag conditions

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/metasmoke#100]
When you delete a flag condition, this will cascade to the flagging logs and cause all posts your account has autoflagged to be deleted.

A example of this is here: https://metasmoke.erwaysoftware.com/post/57906/flag_logs

This post was autoflagged by `NobodyNada`, `MAR`, `Ferrybig`, but it no longer shows my user after I deleted my flag condition.

**Comment by ArtOfCode-** [comment]
this probably needs denormalisation, or reassigning the affected flags to System

**Comment by Undo1** [comment]
Lost some data on this one, but it shouldn't happen in the future.
