### ISSUE TITLE
Time to deletion graphs lack units

### ISSUE THREAD

**Issue by CoconutMacaroon** [Charcoal-SE/metasmoke#1009]
[This graph](https://i.sstatic.net/FykY9MLV.png) on metasmoke displays a value.

For clarity, could units be added?

I'd probably suggest one of the following:
* List the value in seconds
* Do seconds/minutes/hours

The first is probably easier to do though.

**Comment by tripleee** [comment]
For the record, the unit stored in the database is seconds.
