### ISSUE TITLE
Autoflagging: preferences/conditions: site selection add explanation of ????????

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#107]
A few of the possible site selections are, or include, `???????`. There are multiple possibilities of what is meant by having `??????` in the text for the site name. The two that come immediately to mind are: A) Actual single character wildcards that will match multiple site names B) Sites with non-ASCII characters that have been converted to display `???????` instead of the actual text. Please either remove these entries in the list, or add some explanation as to what these selections are (e.g. in a tooltip).

**Comment by ArtOfCode-** [comment]
Thanks, Unicode. @Undo1 it done broke again.

**Comment by Undo1** [comment]
Fixed in 3a267e91823246817b1917a0821b398f24fbf7e0; HTML entity errors are still there but they're a separate issue.
