### ISSUE TITLE
Filter available sites in flagging conditions, based on user's accounts.

### ISSUE THREAD

**Issue by Cerbrus** [Charcoal-SE/metasmoke#108]
It is currently possible to select sites you don't have an account on, when you edit flagging conditions.
This results in flagging failures, because the system can't select a user based on whether or not they have an account on the site that god spammed.

I propose that the "Sites" dropdown in `/flagging/conditions/<id>/edit` is filtered based on what sites the user has registered on.

This means that:

- The autoflagger won't select users that don't have an account on the target site, eliminating failures due to _improperly configured users_. (pro)
- New accounts won't automatically get added to the filter, a user will have to update their conditions **manually**. (con)

The SE api exposes the required information at `/users/{ids}/associated`.
(Note that this request has a max page size of `100`).

Additionally, this information could be used to show the user a list of sites they're not yet registered at, linking to `site_url/users/join`.
(Probably under [tools](https://metasmoke.erwaysoftware.com/admin))

**Comment by Undo1** [comment]
Instead of keeping track of the data required for this, I'm doing the next best thing for now: Just completely ignoring those errors. It's extremely fast to cycle to the next eligible user; API calls are cheap and easily sub-100ms from EC2.

**Comment by Cerbrus** [comment]
I was thinking of a api call on config page load, so you don't have to store it, but that works as well, @Undo1 :+1:

I think this FR can be closed now?

**Comment by ArtOfCode-** [comment]
Sounds like it.
