### ISSUE TITLE
New reports are showing up in other tables

### ISSUE THREAD

**Issue by Cerbrus** [Charcoal-SE/metasmoke#110]
A picture says more than a thousand words:

![capture](https://cloud.githubusercontent.com/assets/2911988/23263756/7ece8746-f9df-11e6-8f20-65b038f7638a.PNG)

Somehow, this new report loaded into the "users" table.

**Comment by angussidney** [comment]
I've noticed this happening before, I just thought that some traffic was corrupted along the way to its destination.
