### ISSUE TITLE
Feature Request: "Users" list is getting quite large - Add sorting (/pagination)

### ISSUE THREAD

**Issue by Cerbrus** [Charcoal-SE/metasmoke#111]
The [list of users](https://metasmoke.erwaysoftware.com/users) has grown quite a bit in the short time we've been featured on meta.

Some sorting / filter (search) / pagination options on there could be practical.

**Comment by ArtOfCode-** [comment]
https://github.com/Charcoal-SE/metasmoke/commit/8465bfe10cc362bf018e9e644bc980690854f74c
