### ISSUE TITLE
Add reason weight and MS post ID to MS websocket messages

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#114]
As requested [here](http://chat.stackexchange.com/transcript/message/35637424#35637424): to realize some new AIM features we'd like to:

- have the `reason_weight` added to `flag_log` and `not_flagged` websocket messages
- have the MS post ID added to `flag_log` messages so that we can make the flag icon clickable, and link to e.g. https://metasmoke.erwaysoftware.com/post/58516/flag_logs

**Comment by Undo1** [comment]
To head off issues with fragmentation and give ya'll a *lot* more flexibility, I'm just embedding the post in the flag log messages. Like so:

![screen shot 2017-02-23 at 6 57 41 pm](https://cloud.githubusercontent.com/assets/5162342/23287326/fa2b0602-f9f9-11e6-8493-30502db250a2.png)

There's some redundant information there (like post link) that I'm keeping for backwards compatibility, at least for now.
