### ISSUE TITLE
Autoflagging doesn't always flag to the maximum number of flags

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/metasmoke#115]
There are times when posts are not automatically flagged to the `max_flags` limit. A few recent examples are listed below:

| Site | Weight | MS Link|
|-----|----------|---------|
| Drupal | 776 | https://metasmoke.erwaysoftware.com/post/58544 |
| Meta | 578 | https://metasmoke.erwaysoftware.com/post/58543 |
| Graphic Design | 479 | https://metasmoke.erwaysoftware.com/post/58542 |
| Graphic Design | 678 | https://metasmoke.erwaysoftware.com/post/58545 |
| Workplace | 487 | https://metasmoke.erwaysoftware.com/post/58514 |

---

These are all high weight posts and higher traffic posts. I can't image that we don't have three flaggers on these sites. There is a [single](https://metasmoke.erwaysoftware.com/post/58516) low weight (249) post that occurred in this same time period that did receive 3 flaggers.

**Comment by Undo1** [comment]
My fault, cause by fix to #114
