### ISSUE TITLE
Inactive standby instances are still labelled as standby

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#116]
When a copy of Smokey that was running in standby mode is turned off, it continues to be labelled as [Standy] (even though it is no longer on standby).

![standby instances](https://cloud.githubusercontent.com/assets/4848802/23294478/ca8295fc-fabf-11e6-8317-681edfebaf69.PNG)

**Comment by Undo1** [comment]
The label is at least partially by-design, to identify instances that *were* standby instances. However, I'm removing the failover button and greying out the standby label for now-dead instances.
