### ISSUE TITLE
Edit flagging condition Preview button doesn't work

### ISSUE THREAD

**Issue by cullub** [Charcoal-SE/metasmoke#117]
This preview button:
![](https://pageshot.net/images/8bd33f9d-5768-4470-ae1d-4332b962c1fd.png)

Using FF (confirmed on 49 and 51) on mac.

**Comment by cullub** [comment]
Note: not reproducible on Chrome for whatever reason.

**Comment by cullub** [comment]
Funny thing: If you enter a value that puts the accuracy below 99.5%, and click save, it gives an error (like it should), but then the preview button starts working.  Really weird..

**Comment by angussidney** [comment]
I have noticed that this *does* work on the sandbox page (), but not on the conditions setup page. https://metasmoke.erwaysoftware.com/flagging/conditions/sandbox

Firefox user

**Comment by Fortunate-MAN** [comment]
I'm a FF user too, on Ubuntu 14.04. I repro this like @angussidney is reproducing it.

**Comment by Undo1** [comment]
That *should* fix this. Let me know if it doesn't and we can reopen.

**Comment by cullub** [comment]
Yep, fixed!  Thanks.
