### ISSUE TITLE
Feature Request: Add a “code status”/“stack” page

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/metasmoke#128]
Currently, the commit SHA in the navbar links to that commit on github, and the tooltip tells the Rails version. It would be great to have it link to a page showing:

 - [x] The versions of Ruby, Rails, and dependencies
 - [x] The commit, possibly with a diff view
 - [x] *n* commits on `master` since this commit & diff?

----

* “Hey Undo, can you pull in the latest changes?” button for people w/ some level of privileges

---

I am 👍 on doing this myself if there’s interest.

**Comment by Undo1** [comment]
For the Rails version, ProTip: 

![screen shot 2017-03-03 at 10 02 32 am](https://cloud.githubusercontent.com/assets/5162342/23560694/901cbeea-fff8-11e6-958b-f832bc033130.png)

The rest is possible (although the button may be redundant; I get emails on each commit anyway). If you're desperate to find prod versions of dependencies, there's always https://github.com/Charcoal-SE/metasmoke/blob/master/Gemfile.lock.

**Comment by j-f1** [comment]
I covered the Rails version in the first comment:

> the tooltip tells the Rails version

**Comment by Undo1** [comment]
Started on this, includes simple commit hash and dependency versions. You're perfectly welcome to expand it to add any of the other things (except anything that sends me emails) you mention here.

There are a couple options for getting the current commit on GitHub's master - you *could* send a request from server side, but it may scale better to have that done client-side in a quick AJAX request.
