### ISSUE TITLE
Add testing to autoflagging code

### ISSUE THREAD

**Issue by Undo1** [Charcoal-SE/metasmoke#129]
It should be possible to stub in the necessary API requests (there are only a few of them).

**Comment by Undo1** [comment]
I've started on this, we've got `webmock` included now which allows us to do this. We'll probably need to do a little rearchitecting on the post model to not shunt everything into a new thread for testability, but it's doable.

**Comment by ArtOfCode-** [comment]
That sounds like it'll increase response times by a fair bit. Is there no way we can keep the autoflagging stuff (which is the bit that needs network requests and is therefore slow) in another thread so we don't block the HTTP response, and still make it testable?

**Comment by Undo1** [comment]
@ArtOfCode- oh, I was just thinking put everything in https://github.com/Charcoal-SE/metasmoke/blob/master/app/models/post.rb#L27 in its own method, then call it in production from within a Thread.new. Just need to expose the guts for testing in a non-async manner, doesn't mean we can't keep it async in prod.

**Comment by j-f1** [comment]
You could move it into `PostHelper`.

**Comment by Undo1** [comment]
Could, but I think we've (I've) been abusing helpers. http://api.rubyonrails.org/classes/ActionController/Helpers.html and other places show them as view helpers, not really logic helpers.

**Comment by Undo1** [comment]
I'm going to close this; we have a few tests now. I'll probably add more in the future, but we have a base. https://github.com/Charcoal-SE/metasmoke/blob/master/test/integration/flagging_test.rb
