### ISSUE TITLE
FR: Expose post edit status in webapi

### ISSUE THREAD

**Issue by Cerbrus** [Charcoal-SE/metasmoke#135]
In FIRE, I'd like to show that (if) a post has been edited.  
Something as simple as a `was_edited` boolean would suffice, but I imagine `edited_at` (like `deleted_at`) could be of use in the future.

**Comment by Undo1** [comment]
The only information we have is the number of revisions a post had when it was reported. There isn't any information about specific edit data currently available.

Would `revision_count` be good enough, keeping in mind that it won't be updated past when the post was reported?

**Comment by Cerbrus** [comment]
That would be sufficient. This is mostly meant to identify vandalism, which would have `revision_count >=1`.

**Comment by Undo1** [comment]
That'll work, then.

**Comment by Cerbrus** [comment]
I've implemented the check from SE's API, now.
However, this might still be useful for other scripts.

**Comment by ArtOfCode-** [comment]
Done with e8ee8f63ac993cd4210a9dd788b091d49c99cab9.
