### ISSUE TITLE
Clicking "Spam flag" link results in routing error

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#137]
The spam flag which is sometimes visible in a report leads to a 404, e.g. https://metasmoke.erwaysoftware.com/post/59564/spam_flag

According to the discussion following [this chat message](http://chat.stackexchange.com/transcript/message/35829680#35829680), it's because of a wrong HTTP verb.

Also reported by [QPaysTaxes](http://chat.stackexchange.com/transcript/message/35974442#35974442).

**Comment by j-f1** [comment]
If the browser uses the `GET` method, it could render https://metasmoke.erwaysoftware.com/post/59564 and show a confirmation popup.

**Comment by ArtOfCode-** [comment]
That's a POST route; hitting it with GET will 404. Does this happen when you click the link from the post page?

**Comment by Glorfindel83** [comment]
Yes it does.

**Comment by Undo1** [comment]
What browser?

**Comment by NobodyNada** [comment]
@Undo1 This happens to me in Safari 10.something.

**Comment by Undo1** [comment]
Interesting, norepro in 10.1 for me.

**Comment by NobodyNada** [comment]
Here's a screenshot (I'm on my phone at the moment):



It says something about verify_developer; could it happen to me since I'm not a dev?

From Jonathan

**Comment by angussidney** [comment]
@NobodyNada that didn't come through by the looks of it, could you re-upload the image when you get to a computer?

**Comment by NobodyNada** [comment]
Screenshot uploaded; sorry I forgot.  GitHub doesn't want to display it for some reason; you'll have to click the link.
