### ISSUE TITLE
Expose revision count on post page

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#138]
We have revision information on most posts since we started autoflagging.

Would it be possible to expose this on the post page and on /review, so that you don't have to leave metasmoke to determine whether or not the post is vandalism?

**Comment by Cerbrus** [comment]
Similar FR to expose the count in the webapi:
https://github.com/Charcoal-SE/metasmoke/issues/135

**Comment by Undo1** [comment]
Thoughts about where this could be shown? I'm leaning toward a tooltip, as it's not information one needs *often*, but I'm not sure where.

**Comment by angussidney** [comment]
Maybe in the bottom-right corner next to the user info? E.g.

>  reported 8 minutes ago | edited 3 minutes ago | posted by user353809 (1)

**Comment by Undo1** [comment]
We don't have revision timestamp data, only revision count, which'd complicate that.

**Comment by j-f1** [comment]
> reported 8 minutes ago | edited once | posted by user353809 (1)
