### ISSUE TITLE
Nice to Have: Trigger charcoal-se.org rebuilds whenever a wiki page is updated

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/metasmoke#140]
metasmoke can do this by listening for [`GollumEvent`](https://developer.github.com/v3/activity/events/types/#gollumevent)s from Charcoal-SE/metasmoke and Charcoal-SE/SmokeDetector and calling the Travis API to request a restart of the latest build on Charcoal-SE/charcoal-se.github.io. This way, the website stays up-to-date with the wiki.

**Comment by Undo1** [comment]
That can absolutely be done. It'd be great if you had the code to trigger the Travis build handy; I can take care of hooking us in to the GH webhook.

**Comment by j-f1** [comment]
Code to trigger Travis build:
```ruby
require 'travis'
Travis.github_auth("<GH Token>")
Travis::Repository.find('Charcoal-SE/charcoal-se.github.io').last_build.restart
```

**Comment by Undo1** [comment]
Should work now. Reopen if it stops.
