### ISSUE TITLE
BUG: API "Posts by URLs" doesn't work with POST calls.

### ISSUE THREAD

**Issue by Cerbrus** [Charcoal-SE/metasmoke#141]
`api/posts/urls` doesn't work then you use POST instead of GET:

> ![capture](https://cloud.githubusercontent.com/assets/2911988/23990635/fdb7369a-0a36-11e7-9fe0-627f63abbfde.png)

The [MS link](https://metasmoke.erwaysoftware.com/api/posts/urls?key=55c3b1f85a2db5922700c36b49583ce1a047aabc4cf5f06ba5ba5eff217faca6&page=1&urls=%2F%2Fsuperuser.com%2Fquestions%2F1189186&_=1489657074032) gets a response, as does [a GET request.](https://metasmoke.erwaysoftware.com/api/posts/urls?key=55c3b1f85a2db5922700c36b49583ce1a047aabc4cf5f06ba5ba5eff217faca6&page=1&urls=%2F%2Fsuperuser.com%2Fquestions%2F1189186&_=1489657074032)

Here's most of the error page I'm getting for the POST:

> ![capture](https://cloud.githubusercontent.com/assets/2911988/23990981/fee15cac-0a37-11e7-9de2-9c0788f868fd.png)

**Comment by ArtOfCode-** [comment]
e22cb85f66c96f88c62f71b01955f0f7c9381d88
