### ISSUE TITLE
Post CI Status to chat for other projects

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#142]
Currently, when a CI build for Smokey finishes the status is posted to chat:

> [CI on 4b53165 succeeded.](http://chat.stackexchange.com/transcript/message/36133306#36133306)

Some of our other projects also have CI builds/tests. In particular, our Userscripts Repo and our website.

Could we get CI status notifications on these in chat too? E.g.

> [ Userscripts ] CI on aabbcc1 succeeded

> [ charcoal-se.org ] CI build to HTML on ddeeff2 failed

**Comment by ArtOfCode-** [comment]
Certainly possible, just a case of hooking the webhook up to metasmoke.

**Comment by ArtOfCode-** [comment]
Done with 065919bb11e1348ff7aed42acc6e552146cba7b6. @Undo1 needs to set up the hooks because he's got the GH secret.
