### ISSUE TITLE
Rails error when opening a post with no user information

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#145]
Clicking the single result [here][1] results in a [Rails error][2]:

> ### ActionController::UrlGenerationError in Posts#show
> Showing /var/railsapps/metasmoke/releases/20170320150615/app/views/posts/show.html.erb where line #65 raised:
> No route matches {:action=>"show", :controller=>"stack_exchange_users", :id=>nil}, missing required keys: [:id]

 [1]: https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=upvote&username=&why=&site=4
 [2]: https://metasmoke.erwaysoftware.com/post/12892

**Comment by ArtOfCode-** [comment]
c3dc554ac5d86626f330ac58e9e2fa1f4ce54981
