### ISSUE TITLE
Posts appear multiple times in list after update

### ISSUE THREAD

**Issue by SulphurDioxide** [Charcoal-SE/metasmoke#149]
When I've left the [posts page](https://metasmoke.erwaysoftware.com/posts) on metasmoke open in a tab, upon a new post being added to that list I get a number of duplicates appear for the last few posts on the page: 
![meta2](https://cloud.githubusercontent.com/assets/14162920/24612078/1de62f40-187c-11e7-9d56-3734b85560aa.PNG)

The tab title also changes to be something like this:
![meta1](https://cloud.githubusercontent.com/assets/14162920/24612163/5ac98394-187c-11e7-9171-073c398e9b91.PNG)

This number corresponds to the number of copies of the posts that are being displayed (although these screenshots are not taken at the same time so might not match up) instead of the number of unique new posts (although I'd guess this is merely a byproduct of the initial issue). This number is not always the same. Refreshing the page or clicking on 'posts' again seems to resolve this problem.

The only thing in the JS console is the following:
![meta3](https://cloud.githubusercontent.com/assets/14162920/24612252/9f6bd254-187c-11e7-9494-b1f5b8d4b9b4.PNG)

This has been happening for a few weeks but doesn't happen in firefox as far as I can tell. 
I've been using: **Chrome Version 57.0.2987.110 on Windows 10**
It also happened in Version 56 too. 

I left the window open over the weekend without using it and came back to find: 
![meta5](https://cloud.githubusercontent.com/assets/14162920/24612847/53076f02-187e-11e7-88de-0e56918bc299.png)
Although this might have been Chrome's issue not MS...

**Comment by SulphurDioxide** [comment]
Also this happened just now:
![meta7](https://cloud.githubusercontent.com/assets/14162920/24619153/081d9454-1891-11e7-8705-54fac1a4d8d8.png)

They layout seems broken and may be related to the issue with adding multiple items.

**Comment by Undo1** [comment]
The second one is flag logs. Looks like websocket channels aren't being properly closed in some cases, and that we're not properly specifying tables to append to. Shouldn't be hard to fix.

**Comment by Undo1** [comment]
Committed an attempt to fix, let me know if this still happens.

**Comment by SulphurDioxide** [comment]
It no longer lists the Posts multiple times on an update but it also doesn't appear to be updating at all now on the MS posts page. A manual refresh is required to get the new posts to appear at the top of the list.

**Comment by SulphurDioxide** [comment]
This has just started happening again (probably last 2 days max). Just as it was before, two copies of the posts turned up. When I refreshed, only one version is displayed as expected.

**Comment by SulphurDioxide** [comment]
It looks like this might be related to the number of feedbacks. The last two posts (shown below) both received three feedbacks each when I took the screenshot.

![msposts](https://user-images.githubusercontent.com/14162920/27126857-b1c4943e-50f0-11e7-99aa-f5b70c2d0491.PNG)

**Comment by ArtOfCode-** [comment]
I can't repro any more; is this still happening?

**Comment by SulphurDioxide** [comment]
_testing_

**Comment by SulphurDioxide** [comment]
I can't make it happen anymore, looks fixed! Hurrah!
