### ISSUE TITLE
Make detailed time to delete data available via the api

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/metasmoke#156]
Currently, data needed to replicate the detailed time to delete graph isn't available via the posts/search route (or the Api [at all](http://chat.stackexchange.com/transcript/message/36717133#36717133)).

Please make the data available so that deletion analysis can be done using data from the API.

**Comment by ArtOfCode-** [comment]
Just a matter of copying GraphsController#detailed_ttd to the API.

**Comment by ArtOfCode-** [comment]
fa46ae9273da0f00a176cbeb6f81478228fb9783
