### ISSUE TITLE
When sorting by columns on the reasons page, sort disabled posts separately

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/metasmoke#157]
Reasons that are disabled should be sorted separately and at the bottom of active reasons.

**Comment by serixscorpio** [comment]
Does something like this look reasonable?
![selection_156](https://user-images.githubusercontent.com/1740566/31514303-2d7b8dc2-af5f-11e7-9aaa-401088517fd9.png)

**Comment by AWegnerGitHub** [comment]
I'd be very happy with that. :)
