### ISSUE TITLE
Add a dashboard panel to the homepage

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/metasmoke#158]
Things like autoflag count, last ping time, invalidated feedbacks, etc.

<sub>[source](https://chat.stackexchange.com/transcript/11540?m=36685128#36685128)</sub>

**Comment by angussidney** [comment]
I think stuff like last ping time and invalidated feedbacks should be left to a separate 'admin' dashboard (I've been meaning to create one myself for a while, just havent gotten around to it yet). After all, are people from outside of charcoal really going to be interested in those technical details?

But I do think it would be good to have something like '50 reasons caught 60 000 posts at 80% accuracy. 50 000 TPs, 8 000 FPs, and 2 000 NAAs. 10 000 posts have been automatically flagged' at the top of the homepage. *That's* the sort of stuff that people would be interested in.

**Comment by j-f1** [comment]
I was thinking it would only show up when logged in.

**Comment by Undo1** [comment]
The other argument is "would people from outside of Charcoal be visiting metasmoke *at all*", which I don't have any readily-accessible data for. I'm definitely not against putting some quick autoflagging stats above the homepage.

**Comment by j-f1** [comment]
I just wanted to avoid the clicks needed to go to the flagging page to view my autoflag count for the day.

**Comment by ArtOfCode-** [comment]
[status-completed]
