### ISSUE TITLE
New autoflag logs coming in on the wrong tab

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#164]
If you are on the [false positives](https://metasmoke.erwaysoftware.com/flagging/logs?filter=fps) tab of the flag logs page, new autoflags are sent down the websocket to be added to the list, even if they aren't yet false positives:

![Example of wrong flag logs being displayed](https://cloud.githubusercontent.com/assets/4848802/25553223/215d76d6-2cf1-11e7-9f84-af684069359b.PNG)

I assume this would also be an issue with the 'Mine' tab.

**Comment by ArtOfCode-** [comment]
I'd bet this is somehow related to #149.

**Comment by angussidney** [comment]
@ArtOfCode- My thoughts exactly, I just couldn't be bothered to go find the right issue :)
