### ISSUE TITLE
Should Second Feedback Invalidate First?

### ISSUE THREAD

**Issue by CalvT** [Charcoal-SE/metasmoke#166]
At the moment, you can submit two "feedbacks" on the same post to metasmoke, both a naa and a tp. 

Instead of this happening, I think that a second feedback should automatically clear the first. 

The current situation has been questioned by other users too, such as Compass: [Is it a bug for Smokey to consider my k and naa- different votes? Shouldn't one override the other?](http://chat.stackexchange.com/transcript/message/36575650#36575650)

**Comment by ArtOfCode-** [comment]
Doing this automatically would be ideal, because we can just drop the first instead of invalidating it, which makes correcting yourself not apply a penalty any more.
