### ISSUE TITLE
Add a SmokeDetector API

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/metasmoke#171]
For my SDS userscript, I have no way to pre-add all of the icons for the instances. Instead, I have to wait for them to ping. It would be great to have a `smoke_detectors` API route to load all of the instances on page load. Note that the `smoke_detectors` section in /api/filters includes the `access_token` which should probably never be sent. In fact, I have [removed it from `SmokeDetector#as_json`](https://github.com/Charcoal-SE/metasmoke/blob/master/app/models/smoke_detector.rb#L13) unconditionally.

**Comment by ArtOfCode-** [comment]
There's a bunch of stuff on the filters page that shouldn't ever be sent, but is included on the filter page for consistency. Implementing logic is responsible for making sure those fields don't get sent even if they're included in the filter.

**Comment by ArtOfCode-** [comment]
2ef08af8e7febc427cd6ed9560857045bd0c01ad

Hit `/api/smoke_detectors`. Filters supported, access tokens protected. You can filter down to instances belonging to one user by passing their user ID as the `owner` query string param.
