### ISSUE TITLE
Allow us to leave feedback from the post page

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#176]
You can submit a spam flag from the post page on MS, but you can't submit feedback. Currently, the only ways to do that are to find the post in chat and `k` it, or to use the API.

Originally proposed by Mithrandir: https://chat.stackexchange.com/transcript/message/37454701#37454701

**Comment by ArtOfCode-** [comment]
Submitting a spam flag also submits true positive feedback. Other than that, unless the post has *no* feedback (in which case it'll be in review), is it necessary to be able to submit more feedback?

**Comment by Fortunate-MAN** [comment]
@ArtOfCode- I do think this will be useful. For example, if you disagree with a feedback on a post, you'll currently have to go to chat/open the post and use FDSC which will be kinda irritating. Though it is preferable to go in chat and feedback if your feedback conflicts with another one as you'll be able to communicate your reason, this should also be allowed from the MS webpage.

**Comment by ArtOfCode-** [comment]
A bunch our stuff disallows conflicting feedback because we want to encourage discussion if you disagree with existing feedback. Letting people sidestep that with MS kinda defeats the point, it seems.

**Comment by Undo1** [comment]
It would still give us the conflicting feedback warning in chat, but forcing discussion is a pretty good point. If you're in chat, it's a lot easier to ask why you disagree than if you're pushing buttons on metasmoke from your phone.

**Comment by ArtOfCode-** [comment]
Calling this closed after 11 days dead. Reopen/comment with any further points.
