### ISSUE TITLE
Overwriting own feedback - please ignore this for 'ignore'.

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#182]
I marked a [post](https://metasmoke.erwaysoftware.com/posts/by-url?url=//expatriates.stackexchange.com/questions/11024) as `fp` (see the chat message [here](https://chat.stackexchange.com/transcript/message/37689572#37689572)), and later I asked Smokey to `ignore` it, because it had already been reported a couple of times before the migration. This resulted in my `fp` feedback being overwritten. Can we creation an exception to this new rule for `ignore` feedback?

**Comment by Glorfindel83** [comment]
Or alternatively, remove `ignore` from the feedback types and store it somewhere else.

**Comment by Undo1** [comment]
Any reason we couldn't drop `ignore` feedback completely as it comes in?

**Comment by j-f1** [comment]
@Undo1 Instances could get it from the API on startup to remember if a post is ignored.

**Comment by Undo1** [comment]
Turned out to be a bug (probably) in the way it was written. Ternary statements are awesome.
