### ISSUE TITLE
Autoflags=no search not working

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#184]
If you filter search by autoflags=no, it appears to return all posts. 

I think this is due to a dodgy SQL query here: https://github.com/Charcoal-SE/metasmoke/blob/master/app/models/post.rb#L19

Cc @superplane39 as you originally reported this

**Comment by Undo1** [comment]
![screen shot 2017-06-01 at 8 16 41 am](https://cloud.githubusercontent.com/assets/5162342/26684189/8839ec4c-46a3-11e7-914e-c9fc6afc049d.png)

**Comment by ArtOfCode-** [comment]
[status-gary-bernhardt]

![](https://i.imgur.com/IppKJ_d.jpg?maxwidth=640)

**Comment by ArtOfCode-** [comment]
[status-norepro] with current commit. If @Undo1 can deploy current, that should work.

**Comment by Undo1** [comment]
Awesome, should be able to get it done this afternoon.

**Comment by angussidney** [comment]
Still doesn't seem to be fixed

**Comment by ArtOfCode-** [comment]
Fixed in ece6de8f893e4964bf3907a54c10507036665dba, then fixed better in 6a44fb41ece3730b1f49a47725285af29c19334a
