### ISSUE TITLE
Make sure that overwriting feedback works with non tpu-/fp- feedback

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#188]
Currently, [this line](https://github.com/Charcoal-SE/metasmoke/blob/master/app/controllers/feedbacks_controller.rb#L97) assumes that the feedback will always be either `tpu-` or `fp-`. This could possibly fail if another feedback is given e.g. `tp-`

Related: #182

**Comment by ArtOfCode-** [comment]
Works now, happened to fix this with another change
