### ISSUE TITLE
Switch to webpacker for bundling

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/metasmoke#190]
> I’d recommend (at some point) switching to https://github.com/rails/webpacker or similar — webpack is a fairly modern bundler, and it supports Babili, the next-gen JS compressor. <sup>([source](https://chat.stackexchange.com/transcript/message/37980478#37980478))</sup>

**Comment by Undo1** [comment]
Been looking at this, and can't find a clear guide on how to migrate from what we're doing to this. Know of any guides for the Rails asset pipeline, specifically?

**Comment by j-f1** [comment]
@Undo1 I don’t, but I can try converting this weekend. If you have anything so far, can you push to a branch?

**Comment by Undo1** [comment]
Don't have anything useful, @j-f1. Farthest I got was the first couple steps on https://github.com/rails/webpacker (`gem 'webpacker', '~> 2.0'`, `rails webpacker:install`) and then being unable to figure out what comes next.
