### ISSUE TITLE
Reporting via FDSC still doesn't work (even though MetaSmoke returns status 201)

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#200]
This is the request posted by FDSC:

```
curl 'https://metasmoke.erwaysoftware.com/api/w/post/report' -H 'Host: metasmoke.erwaysoftware.com' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://mathoverflow.net/questions/207477/john-nashs-mathematical-legacy/272341' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Origin: https://mathoverflow.net' -H 'Connection: keep-alive' --data 'post_link=&key=070f26ebb71c5e6cfca7893fe1139460cf23f30d686566f5707a4acfd50c&token=8261acd787360f76daf073662020428c50aa7384aec04d66722e36a0fbe01be8'
```

The post wasn't deleted at the moment of reporting. Metasmoke returns

> OK

with HTTP status code 201.

**Comment by ArtOfCode-** [comment]
Smokey side bug. Metasmoke always returns 201 here, it has no way of telling if smokey received the report

**Comment by Glorfindel83** [comment]
OK. Well, this was probably the 3rd time in a week that it failed (even though metasmoke reported OK), and I haven't seen it working yet.

**Comment by ArtOfCode-** [comment]
Yeah, sounds like a smokey bug. Not sure what exactly, but that'll be where it is.

**Comment by Glorfindel83** [comment]
@ArtOfCode- Should I repost this bug on the Smokey repository, then? Or can it be migrated?

**Comment by Undo1** [comment]
Probably good to repost @Glorfindel83, I don't see a way to move issues around.

**Comment by Glorfindel83** [comment]
https://github.com/Charcoal-SE/SmokeDetector/issues/939
