### ISSUE TITLE
WebSocket for AIM is broken

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#211]
AIM currently has a problem (as of today; I think it worked correctly yesterday); information is not loaded for new reports. It seems the WebSocket (`/cable`) is broken; it only sends `ping` messages, nothing else.

https://chat.stackexchange.com/transcript/message/38371810#38371810

**Comment by tripleee** [comment]
The chat message is followed by one by @j-f1 which seems to contain a fix (I think)?

> @Undo Can you add the sensitive_fields field to the MS config file?
> under common:
>    sensitive_fields:
>     - api_keys.key
>     - api_tokens.code
>     - api_tokens.token
>     - audits.remote_address
>     - audits.request_uuid
>     - flags.reason
>     - flags.user_id
>     - github_tokens.token
>     - ignored_users.user_name
>     - ignored_users.user_id
>     - smoke_detectors.access_token
>     - users.email
>     - users.encrypted_password
>     - users.reset_password_token
>     - users.reset_password_sent_at
>     - users.encrypted_api_token
>     - users.two_factor_token
>     - users.salt
>     - users.iv

**Comment by j-f1** [comment]
@tripleee No, that was for the data explorer.

**Comment by Undo1** [comment]
Should be fixed by #213, waiting for confirmation.

**Comment by Glorfindel83** [comment]
Thanks, I can confirm it's working now.
