### ISSUE TITLE
Autoflagging breaks off when a moderator is selected

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#216]
Autoflagging breaks off when a moderator is selected, e.g. on this post: https://metasmoke.erwaysoftware.com/post/74869

The tooltip on the 'Fail' message (https://metasmoke.erwaysoftware.com/flagging/logs) says:

```
User is a moderator on this site; not flagging: User is a moderator on this site; not flagging | /var/railsapps/metasmoke/releases/20170629174329/app/models/user.rb:172:in `spam_flag'
/var/railsapps/metasmoke/releases/20170629174329/app/models/post.rb:106:in `send_autoflag'
/var/railsapps/metasmoke/releases/20170629174329/app/models/post.rb:76:in `block in autoflag'
/var/railsapps/metasmoke/releases/20170629174329/app/models/post.rb:74:in `each'
/var/railsapps/metasmoke/releases/20170629174329/app/models/post.rb:74:in `autoflag'
/var/railsapps/metasmoke/releases/20170629174329/app/models/post.rb:35:in `block (2 levels) in <class:Post>'
```

I'd expect metasmoke to select another user instead of Undo and continue with flagging.

The same thing happened with DavidPostill on SuperUser, see [here](https://chat.stackexchange.com/transcript/message/38529794#38529794).

**Comment by Undo1** [comment]
That's interesting, I was sure it used to behave properly in that case. I'll take a look.

**Comment by Undo1** [comment]
That should fix it, let me know if it pops up again

**Comment by Undo1** [comment]
Possible that I actually broke it more. https://chat.stackexchange.com/transcript/11540?m=38647805#38647805

**Comment by ArtOfCode-** [comment]
Is this still happening?

**Comment by Undo1** [comment]
It should be. I meant to come back to this and fix it, never got around to it. It's not a crippling issue, but probably still one to have open.

**Comment by Glorfindel83** [comment]
This is probably another instance: https://metasmoke.erwaysoftware.com/post/80665 but I can't find corresponding logs in metasmoke.

**Comment by ArtOfCode-** [comment]
Re-poke. Has anyone seen this issue come up again recently?

**Comment by Glorfindel83** [comment]
@ArtOfCode- nope. Might very well be fixed.
