### ISSUE TITLE
Automated Database Dumps

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#220]
It would be nice if there was a way for the MySQL database dumps to be automated, rather than relying on Undo to make them.

 - Create a new dump on user request (with ratelimit?), or create a new dump nightly/weekly and allow anyone to download?
 - Host on AWS S3, github, or other?
 - Open to all, or core only?

**Comment by Undo1** [comment]
Need to do the math on bandwidth cost - that'd determine how restrictive it is, if I'm hosting it on S3. Of course, folks can always email it to each other or do whatever they want with it, so it'd always be 'open to all' in some respects.

**Comment by angussidney** [comment]
@Undo1 a quick calculation using the [calculator](http://calculator.s3.amazonaws.com/index.html), assuming 50 downloads of a 500mb database per month, results in an estimated extra cost of 50 cents per month. I'm pretty sure that the database is *much* smaller than that, so the cost would probably be quite a bit less.

**Comment by ferrybig** [comment]
We could also think of using torrent for the database download. This allows members of the community  to help seeding by just keeping their computer on, and because of the p2p nature of torrents, it would mean less bandwidth usage for the main server (we could even impose a max upload speed server side on it, and unlike most http servers, this max upload speed is for all connections together.)

**Comment by ArtOfCode-** [comment]
If we write a script to generate a dump, then we can have a route that calls said script and emails the requesting user when it's done with a link to the dump. We can also tie that into a Backup model so that we only generate a dump a day at maximum.

**Comment by Undo1** [comment]
Alternatively @ArtOfCode-, just generate it every day (cheap) and overwrite it in S3 (free). Doesn't need to be user-triggered at all, IMO.

Heck, I already do it with nightly backups, just need to get redaction working for this one.

**Comment by ArtOfCode-** [comment]
996a6abf6a5cfa761619afe4e91a6c7ab2b02666; b64fc6cbedb7b27444f77782c563e72e91dc9d94

**Comment by Undo1** [comment]
Subtle hint? ;)

**Comment by ArtOfCode-** [comment]
I'd do it myself, but I'm not the one with server & S3 access ;)

**Comment by ArtOfCode-** [comment]
Thought we've recently thrown around: use `schedule.rb` and `s3cmd` to automate this. Ideally an MS page to download the backups too, but that's less essential.

**Comment by ArtOfCode-** [comment]
Completed
