### ISSUE TITLE
Cannot cancel account

### ISSUE THREAD

**Issue by JinEnMok** [Charcoal-SE/metasmoke#222]
Tried to cancel account today - got an error, something about 

```
ActiveRecord::StatementInvalid in Devise::RegistrationsController#destroy
``` 
and 

```
Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`metasmoke`.`flag_conditions`, CONSTRAINT `fk_rails_4296ce72f4` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)): DELETE FROM `users` WHERE `users`.`id` = 301

```

See the attached error page (originally HTML but extension changed to TXT because GitHub): 
[Action Controller_ Exception caught.txt](https://github.com/Charcoal-SE/metasmoke/files/1146680/Action.Controller_.Exception.caught.txt)

**Comment by ArtOfCode-** [comment]
For conditions, we can destroy dependants. We should check that we're nullifying not deleting for flag logs, though.
