### ISSUE TITLE
Odd regex errors in JSON search

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#223]
Oddly, attempting to use `\b` fails when I try to fetch a JSON search result.

    tripleee$ curl 'https://metasmoke.erwaysoftware.com/search.json?body=%5Cbpcsupremo%5C.com%5Cb&body_is_regex=1'
    []

The same query works fine in Chrome.  The same query without the `\b` (encoded as `%5Cb`) around the search phrase works fine in Curl.

Am I missing something obvious, or is this a bug?

**Comment by ArtOfCode-** [comment]
Using \b directly is probably being treated socially by your shell, so it's probably not sending what you think. URL-encode from a shell to be safe.

**Comment by tripleee** [comment]
No, single quotes inhibit all shell meddling with the string inside. I actually originally discovered this problem with Python and `requests` but `curl` is easier to repro for most people, and reveals that the problem is not with Python or the Requests library.

**Comment by ArtOfCode-** [comment]
Huh. I'll look at it when I'm back, then.

**Comment by tripleee** [comment]
I get the same result in Chrome if I visit the URL in an incognito window. I guess the thing which disables regex support when you are not logged in is doing something here. It would be nice if URLs to search results would work regardless of whether the visitor is logged in, though (or as a fallback at least there was an actionable error message).

**Comment by ArtOfCode-** [comment]
9ff243f
