### ISSUE TITLE
FR: include autoflagging weight in Metasmoke JSON search result

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#224]
The JSON blob I get back from something like https://metasmoke.erwaysoftware.com/search.json?body=pcsupremo.com does not include the autoflagging weight of each hit. This would be nice to obtain; it is displayed for each post in the corresponding interactive (non-JSON) search result https://metasmoke.erwaysoftware.com/search?body=pcsupremo.com

**Comment by tripleee** [comment]
If adding this to the existing schema is challenging, at least offer _some_ way of obtaining this information programmatically.

**Comment by tripleee** [comment]
The [`/posts/:id` API call](https://github.com/Charcoal-SE/metasmoke/wiki/Posts-by-ID) includes a `reason_weight` member for each `item`. I'm happy with this, but leaving this open for now in case we would like to document this in more detail somewhere.

**Comment by ArtOfCode-** [comment]
Because of views, the API returns posts with a bunch of extra detail, like reason weight. The interface, and JSON alternatives to the interface like search.json, don't. 

There's a slightly tamer version of search available in the API, which you can use if it has enough criteria for you in the meantime.

**Comment by tripleee** [comment]
I'm planning to update the `/posts/:id` documentation in the wiki to reflect what this interface actually currently returns. I was scouring the API wiki pages over the weekend and couldn't find the reason weight anywhere, but there are apparently several other things which have changed since December. Anyway, if you have other or different plans, maybe we should coordinate here.

**Comment by ArtOfCode-** [comment]
No plans on that front. I just haven't updated the docs in a *long* time. There's a bunch of undocumented routes, and another, bigger bunch of routes whose behaviour has changed or that now return extra data, all undocumented.

**Comment by tripleee** [comment]
I updated the API doco now.

**Comment by tripleee** [comment]
New ticket: https://github.com/Charcoal-SE/metasmoke/issues/226
