### ISSUE TITLE
API filter generator doesn't know about posts.reason_weight

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#227]
The one field I really want to query for is not visible here:

https://metasmoke.erwaysoftware.com/api/filters

Shouldn't the page be dynamically generated from the schema anyway?

**Comment by ArtOfCode-** [comment]
posts.reason_weight doesn't exist. You're thinking of SUM(reasons.weight) - you can either use posts-by-URL to get it, or query for a post's reasons and sim the weights.

**Comment by tripleee** [comment]
But https://github.com/Charcoal-SE/metasmoke/wiki/Posts-by-ID returns a field like that? Oh well, maybe close this.

**Comment by ArtOfCode-** [comment]
Posts by ID might have it as well. By URL definitely uses a jbuilder view, where we do the SUM(reasons.weight) automatically and include it; by ID might use the same view.
