### ISSUE TITLE
What should be on MS' dashboard?

### ISSUE THREAD

**Issue by ArtOfCode-** [Charcoal-SE/metasmoke#228]
The current homepage for metasmoke is the reasons dashboard. That's a pretty useful bit of info for Charcoal people, but doesn't make a whole lotta sense to anyone else.

I've been thinking, and I think a few others have too, that it's time to put something else on the homepage instead - some sort of summary of various useful bits of information and stats, maybe.

Problem is - what? What should we have on a new dashboard/homepage for metasmoke?

**Comment by j-f1** [comment]
See also #158.

**Comment by NobodyNada** [comment]
I think the [autoflagging dashboard](https://metasmoke.erwaysoftware.com/flagging) is a good example of how it should look.

There's tons of useful stats, cool graphs, and helpful links, and it looks *really* nice.  How about something like this?

<img width="1440" alt="dashboard" src="https://user-images.githubusercontent.com/19418817/28547622-97ca275c-7084-11e7-9d74-bb123c32ef4d.png">

I really like this format, although we should probably change *which* data is displayed (e.g. the box on the right could probably hold more important information than review stats, and we can display more useful graphs).

**Comment by j-f1** [comment]
I’d like to see how many flags were cast by me on the homepage.

**Comment by angussidney** [comment]
@NobodyNada wow, that's an impressive mockup, I like it. 

Under the stats heading I'd probably put a bit more, something like '50 reasons caught 60 000 posts at 80% accuracy. 50 000 TPs, 8 000 FPs, and 2 000 NAAs. 10 000 posts have been automatically flagged'. 

As for JF's suggestion, we could just add (20 by you) to the autoflagging box.

**Comment by ArtOfCode-** [comment]
@Nobody Nadal I like that; my only concern is that graphs are relatively expensive to generate. On the homepage, we probably don't want that - we can probably include one graph, but I'd be wary about any more. So, related question, what's the most important or interesting graph we could include - currently existing or not, either way.

**Comment by ferrybig** [comment]
@artofcode- can't we cache the graphs server side? Like only update them
every 15 minutes or longer (similar to see cross site flair), even if
multiple people request them. And then store them as simple ping images
instead of feature included highcharts graphs

----

Op 25 jul. 2017 09:42 schreef "ArtOfCode" <notifications@github.com>:

**Comment by angussidney** [comment]
And surely 2 graphs would be much less expensive to generate than the current long list of reasons, which takes a 10+ second SQL query (at least when I load it)?

**Comment by Undo1** [comment]
I'd be tempted to have it be tabbed - default to this new view, but allow going back the the classic one with a sticky tab. Reasons view is useful to me, at least, and there isn't anywhere else we show all reasons with accuracy data in one place.

**Comment by ArtOfCode-** [comment]
Yes there is @Undo - click reasons in the top bar, it's the same view.

**Comment by j-f1** [comment]
We could make the homepage even faster by having a small introductory message, then AJAX in the graphs and tables. We could also set it up to render everything at once when visiting with Turbolinks to decrease delays there.

**Comment by ArtOfCode-** [comment]
[status-completed]
