### ISSUE TITLE
TTD graph on dashboard should include entire first day

### ISSUE THREAD

**Issue by Undo1** [Charcoal-SE/metasmoke#230]
Queries like these:

```
WHERE ... (`posts`.`created_at` > '2017-04-29 17:19:34.104181')
```

Create graphs like this:

![screen shot 2017-07-29 at 11 20 22 am](https://user-images.githubusercontent.com/5162342/28746870-f4470e40-744f-11e7-8bbb-f2b5e4a69882.png)

Since we're cutting a day in an unnatural place. That query should be adjusted to take the whole day, or none of it.

**Comment by ArtOfCode-** [comment]
09a4dc91cd05ebdd5535793b84087bec52269b0d
