### ISSUE TITLE
Make the boxes on the MS dashboard links

### ISSUE THREAD

**Issue by superplane39** [Charcoal-SE/metasmoke#231]
I keep trying to click on the 'Flagging' box to go to https://metasmoke.erwaysoftware.com/flagging, and the 'feedback' box to go to https://metasmoke.erwaysoftware.com/admin/user_feedback?user_id=59. I also think that the 'Posts today' box should link to https://metasmoke.erwaysoftware.com/posts. This would be more useful than them just sitting there.

**Comment by ArtOfCode-** [comment]
Done in 2fdf7c1c5727a1ef7078e6d88ce983ead61bb83c; lint fixed in ac85be2d51e13abd8343f9d62ca2c9ba80bfbe80
