### ISSUE TITLE
Allow sending write token directly to app

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/metasmoke#233]
Currently, once the user allows write access for an app, they are given a token to copy-paste into the app. However, the app could instead ask for write access and provide a callback URL to redirect to once the token has been granted. Example:

```
https://metasmoke.erwaysoftware.com/oauth/request?key=abcd1234&callback=https://example.com
```

This would redirect the user to `https://example.com/?token=abcd1234`, where `abcd1234` is the actual write token.

**Comment by ArtOfCode-** [comment]
Parameter name is `redirect`, rather than `callback`, but otherwise implemented as described.
