### ISSUE TITLE
Regex title + body search functionality via API

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#235]
metasmoke/search.json?body=regex&body_is_regex=true used to sort of work but was disabled in https://github.com/Charcoal-SE/metasmoke/issues/223 which breaks one of my scripts.  I would like to be able to perform a regex search (ideally, on title + body at the same time, but the current code does both separately and then merges the results) over the API using my Metasmoke API key.

**Comment by ArtOfCode-** [comment]
9c5899b55c506bf48bd98aaeeb7351cd5681089b

Runs <code>SELECT <em>fields</em> FROM posts WHERE body REGEX <em>query</em> OR title REGEXP <em>query</em>;</code>
