### ISSUE TITLE
Tpu feedback from MS review

### ISSUE THREAD

**Issue by JohnMiliter** [Charcoal-SE/metasmoke#238]
I like the review interface, but I am tired of going back to chat later after reviewing to manually blacklist spammers via the !!/addblu command

I think it would be nice if the spam / abusive button in the metasmoke review gave tpu  feedback instead of tp feedback (I tested it, and unless another user was messing with the blacklist in another room, or there is a very long delay, that button does not auto-blacklist users).
If this was made the case, a separate "tp" or "vandalism" button should be added.

**Comment by JohnMiliter** [comment]
(Sorry if posted in the wrong place)

**Comment by tripleee** [comment]
I'm thinking this is because of an architectural disconnect -- Smoke Detector runs in chat, Metasmoke doesn't, and so it would have to grow a chat interface after all in order to communicate the blacklisting to Smoke Detector.

**Comment by angussidney** [comment]
AFAIK the full functionality is there to blacklist stuff via the MS websocket (because that's how the API blacklists stuff), it's just that it needs to be implemented for review.
