### ISSUE TITLE
Routing error on /review

### ISSUE THREAD

**Issue by Thaillie** [Charcoal-SE/metasmoke#241]
When I go to the review page I get a routing error, I attached the full trace as an attachment.
I don't think this is supposed to be happening :p

[full_trace.txt](https://github.com/Charcoal-SE/metasmoke/files/1221865/full_trace.txt)

**Comment by j-f1** [comment]
That’s because you’re not a reviewer, so you can’t visit `/review`

```
app/controllers/application_controller.rb:62:in `verify_reviewer'
```

I think we should have something nicer and clearer here when we verify privileges.

**Comment by ArtOfCode-** [comment]
@j-f1 [status-completed] I've added a nicer view for access-denied. b6b4a6cdf7c9ab47733bc700b2ed1ca2227dfba6
