### ISSUE TITLE
Announcement emails check box does not work

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#242]
I discovered this check box in my profile on Metasmoke, but attempting to tick it produces a backtrace.

Encoding::UndefinedConversionError in UsersController#set_announcement_emails
"\x8B" from ASCII-8BIT to UTF-8

("Extracted source" box can't be properly copy/pasted; points to line 17 of ... some file, apparently https://github.com/Charcoal-SE/metasmoke/blob/bc38143ed07ab3b3dcf3967b7e10a87b8a1daa7a/app/models/concerns/websocket.rb#L17)

Rails.root: /var/railsapps/metasmoke/releases/20170815214708

Application Trace | Framework Trace | Full Trace

app/models/concerns/websocket.rb:17:in `broadcast_event'
app/models/concerns/websocket.rb:25:in `broadcast_update'
app/controllers/users_controller.rb:81:in `set_announcement_emails'

Request

Parameters:

{"utf8"=>"✓", "authenticity_token"=>"JDZaofnge....deadbeef==", "emails"=>"on", "commit"=>"Save"}

**Comment by tripleee** [comment]
It's also not clear what these annoucement emails are, is this documented somewhere?

**Comment by tripleee** [comment]
I also get basically the same error if I attempt to enable 2FA.

**Comment by ArtOfCode-** [comment]
@tripleee Is this fixed?

**Comment by tripleee** [comment]
Seems to be; I successfully signed up for announcements and enabled 2FA (which is what I was actually having a problem with in the first place when I discovered this).
