### ISSUE TITLE
Regex search in API requires trusted key

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#243]
I'm trying out the new API from https://github.com/Charcoal-SE/metasmoke/issues/235 but I get an error response:

    {'error_message': 'The requested action requires the presented key to be trusted.', 'error_code': 403, 'error_name': 'trusted_key_required'}

I can find no documentation for what "trusted" means for a key or how to request it. Is this really necessary and useful, anyway? Other API calls with potentially high load requirements or database integrity risk do not have this requirement.

I have a single Metasmoke API key which I recently renamed from "tripleee" to "halflife".

**Comment by Undo1** [comment]
Your key is marked trusted now. Paging @ArtOfCode- for details on that system.

**Comment by tripleee** [comment]
For what it's worth, I don't seem to be able to use `\b` for word boundaries in these regex queries; but replacing it with "trad" patterns seems to work just fine.

**Comment by tripleee** [comment]
Also, the result doesn't contain e.g. `created_at` so I still have to query for that separately. Maybe that's by design, but I thought I'd ask.

**Comment by ArtOfCode-** [comment]
That'll just be down to MYSQL regex flavour, @tripleee. I required trusted keys on this because it's an additional level of protection for a seriously expensive call.

**Comment by tripleee** [comment]
More or less related: #244

**Comment by tripleee** [comment]
I'll leave this open until it's documented, but other than that, I guess we are all set here. Thanks for explaining, and for the very quick fix.
