### ISSUE TITLE
Traceback when supplying a filter to /api/posts/:id

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#244]
I used the "filter maker" at https://metasmoke.erwaysoftware.com/api/filters to try to construct a filter for some `posts` fields.  It gave me a result which causes Metasmoke to return to me with a completely humongous traceback -- if I'm reading this correctly, it looks like it attempts to fetch the `created_at` field from the wrong table, but I don't really pretend to understand this.

`req = requests.get('https://metasmoke.erwaysoftware.com/api/posts/80638', params={'key': MSkey, 'filter': 'AAAAAAAAABCDgAAAAAAAAA=='})`

This gives me a 500 error with a 170k `req.text` containing a HTML-formatted error message with many details. The gist of it seems to be this snippet:

```
    Showing <i>/var/railsapps/metasmoke/releases/20170815214708/app/views/api/posts.json.jbuilder</i> where line <b>#1</b> raised:
  </p>
  <pre><code>Mysql2::Error: Unknown column &#39;ignored_users.created_at&#39; in &#39;field list&#39;: SELECT  ignored_users.created_at, posts.body, posts.user_link, posts.username, posts.why FROM `posts` LEFT OUTER JOIN `feedbacks` ON `feedbacks`.`post_id` = `posts`.`id` AND `feedbacks`.`is_invalidated` = 0 LEFT OUTER JOIN `deletion_logs` ON `deletion_logs`.`post_id` = `posts`.`id` WHERE `posts`.`id` = 80638 GROUP BY `posts`.`id` ORDER BY `posts`.`id` DESC LIMIT 10 OFFSET 0</code></pre>
```

**Comment by tripleee** [comment]
I have edited this to replace my API key but other than that, this is verbatim.

[traceback.txt](https://github.com/Charcoal-SE/metasmoke/files/1227439/traceback.txt)

**Comment by tripleee** [comment]
Also, it looks vaguely like I get just random fields from some previous filter if I don't specify an explicit filter, is that correct?

**Comment by tripleee** [comment]
Through trial and error, I found that `'filter': 'AAAAAAAAAAO//gAAAAAAAUA='` seems to avoid a trace, and gives me a result which includes the `created_at` field.

**Comment by tripleee** [comment]
It would be great if there was a reverse mapping so you could see which fields an existing filter selects (other than by provoking a hideous backtrace).

**Comment by ArtOfCode-** [comment]
*I* don't pretend to understand this, and I developed it... The reverse mapping does exist in code, it's just not exposed as a UI.

**Comment by ArtOfCode-** [comment]
Wait, why is `ignored_users.created_at` in there? `ignored_users` doesn't exist any more... @Undo1, is your config up to date?

**Comment by Undo1** [comment]
Oops. Bingo @ArtOfCode- , sorry @tripleee. Try it now.

**Comment by ArtOfCode-** [comment]
I don't expect that to *work*, it'll probably just come out with a different field name in error, but it's probably a good idea to have the right config to debug against :)

**Comment by tripleee** [comment]
Yeah, I was hoping the reverse mapping could be exposed so you could feed in a filter string in a web form and get back a list of the fields it selects.

**Comment by tripleee** [comment]
So just to clarify, should I always pass in a `filter` to select some fields, and is the result basically undefined if I don't? I don't know if this needs to be in a separate bug report, as I'm still only speculating about what it's supposed to be like.

**Comment by tripleee** [comment]
Wait, if the output depends on the configuration, does that also mean that a filter string created with one configuration could start meaning something different when the server's configuration is updated?

**Comment by ArtOfCode-** [comment]
(a) Mind throwing that in a separate issue so I can track it as an FR instead of a bug?  
(b) There's a default filter on every route, so the fields you get are defined and constant.  
(c) Yep. Which is why we're careful about changing config.

**Comment by ArtOfCode-** [comment]
v1/EOL
