### ISSUE TITLE
Supress duplicate reports

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#246]
Inspired by [this comment](https://github.com/Charcoal-SE/metasmoke/issues/183#issuecomment-304521750) by @Undo1:

> Additionally, we should probably reject duplicate reports from different instances.

MS should probably test for:
- same post URL
- same post content
- reported within 1 min or so of each other

Additional idea: add a log of supressed post creations, showing time, title, link and Smokey instance. Similar to the invalidated feedbacks log.

**Comment by ArtOfCode-** [comment]
https://github.com/Charcoal-SE/metasmoke/blob/4bb1f718d306e182a3533bae3d433b526a294bf9/app/models/post.rb#L6
