### ISSUE TITLE
Cannot logout - UndefinedConversionError

### ISSUE THREAD

**Issue by SulphurDioxide** [Charcoal-SE/metasmoke#248]
When I attempt to log out of metasmoke I get the following error:
> Encoding::UndefinedConversionError in CustomSessionsController#destroy

Here is the stack trace: 
```
app/models/concerns/websocket.rb:17:in `broadcast_event'
app/models/concerns/websocket.rb:25:in `broadcast_update'
app/controllers/custom_sessions_controller.rb:24:in `destroy'
```

**Comment by ArtOfCode-** [comment]
[status-fixed-by-unrelated-fix]
