### ISSUE TITLE
Feature request: Live updates for the posts page, using websockets

### ISSUE THREAD

**Issue by JonasCz** [Charcoal-SE/metasmoke#25]
It would be cool to have live, realtime updates via websockets, so that I can keep metasmoke (the "posts" page, specifically) open in a tab, and immediately see if there's anything new, perhaps with the title changing to denote this ? Something like the new questions pages, where we get "x new questions" messages, would be super cool.

Would something like this be doable ?

**Comment by ArtOfCode-** [comment]
> Would something like this be doable ?

How technical are we being here? Yeah, it's possible - requires @Undo1 to set up websockets on the server, and for someone to write the feature.

**Comment by Undo1** [comment]
Writing the feature would be no problem; it's the sysadmin side that's
iffy. I'm using Passenger + Apache at the moment, which doesn't support
ActionCable
<https://www.phusionpassenger.com/library/config/apache/action_cable_integration/>
.

So it's just a bunch of sadmin work for me. I really want to do it, but I
don't have much of a gameplan on it yet.

**Comment by Undo1** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/5162342/15941912/6abe2a0c-2e3f-11e6-9f02-c72ab7416182.gif)

**Comment by JonasCz** [comment]
Wow - that's so awesome !

 Thank you both so much for this.
