### ISSUE TITLE
Track domain names

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#250]
Metasmoke currently does not easily allow us to track which domain names are used in spam.

This is one of the details we need in order to track who the spammers are and hopefully eventually track them down.  I would like to see the Metasmoke data model extended to track domain names from spam URLs, email addresses, etc.

Just being able to get statistics on recently active domain names and see how many times a particular domain has been used in the past would already be very useful.

Down the line, I'd love to be able to annotate the domain records with metadata such as hosting, whois, etc for tracking hosting and ownership, and maybe collect domains under tags like "#indian_pharma".

**Comment by tripleee** [comment]
As requested by @ArtOfCode- in chat:
https://chat.stackexchange.com/transcript/message/39647015#39647015

**Comment by ArtOfCode-** [comment]
[branch: `domain-tracking`](https://github.com/Charcoal-SE/metasmoke/tree/domain-tracking)
