### ISSUE TITLE
Metasmoke is out of disk

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#253]
Mysql2::Error: Can't create/write to file '/tmp/#sql_fc8_0.MAI' (Errcode: 28 "No space left on device")

https://chat.stackexchange.com/transcript/message/39686235#39686235

**Comment by angussidney** [comment]
Ideally Sentinel needs to have logrotate turned on, or as suggested by @ferrybig [here](https://chat.stackexchange.com/transcript/message/39687748#39687748), it can be run on a different user account with a per-user quota, so that issues with one won't cause the other to come down too.

**Comment by Undo1** [comment]
Should be fixed now. I'll look at setting up a disk space alarm, probably the easiest 'solution'. More like a long-term bandaid, but should work.
