### ISSUE TITLE
Post report feature broken

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/metasmoke#254]
When an userscript calls the endpoint `https://metasmoke.erwaysoftware.com/api/w/post/report`, MS should send this post to smokey to be reported.

This is not happening, and instead MS just returns status `201 Created`, without doing anything else.

This endpoint is used by FDSC in the following manner:

```http
POST /api/w/post/report HTTP/1.1
Host: metasmoke.erwaysoftware.com
Connection: keep-alive
Content-Length: 184
Accept: */*
Origin: https://stackoverflow.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: https://stackoverflow.com/questions/21184960/ruby-digestdigest-is-deprecated-use-digest/46058609
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8,nl;q=0.6

post_link=%2F%2Fstackoverflow.com%2Fa%2F46058609&key=070f26ebb71c5e6cfca7893fe1139460cf23f30d686566f5707a4acfd50c&token=mstokenfoundheremstokenfoundheremstokenfoundheremstokenfoundhere
```

Form decoded:
```
post_link: //stackoverflow.com/a/46058609
key: 070f26ebb71c5e6cfca7893fe1139460cf23f30d686566f5707a4acfd50c
token: mstokenfoundheremstokenfoundheremstokenfoundheremstokenfoundhere
```

**Comment by Undo1** [comment]
Norepro here; looks like a Smokey or userscript issue. Dug around in the logs, and it definitely sent the right data down the websocket both times you hit the endpoint.

About that 'both times' thing...

```
I, [2017-09-05T15:35:14.498022 #10530]  INFO -- : Started POST "/api/w/post/report" for ip:v6:goes:here at 2017-09-05 15:35:14 +0000
I, [2017-09-05T15:35:14.644762 #10530]  INFO -- : Started POST "/api/w/post/report" for ip:v6:goes:here at 2017-09-05 15:35:14 +0000
```

Looks like a userscript or something sent the request twice within 200ms? Curious what timing looked like on your end - where'd you get the data for this, and does it look like I'm missing a later request?
