### ISSUE TITLE
API FR: Notify when Smoke Detector's GitHub repo is updated

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#256]
It would be useful if the websocket API could send out an event when the SmokeDetector GitHub repo receives a new commit on the `deploy` branch.

Briefly, the code which already handles a notification when the `deploy` branch receives a push could be extended to pass on these notifications to whatever client wants to receive it.

Details and musings in chat:
https://chat.stackexchange.com/transcript/message/40111407#40111407

Related: https://github.com/Charcoal-SE/metasmoke/issues/214
https://github.com/Charcoal-SE/SmokeDetector/blob/master/metasmoke.py#L127

**Comment by tripleee** [comment]
There was an earlier discussion about querying the SmokeDetector blacklists and watchlist via the Metasmoke API somehow but that's a much more involved effort. I'm not submitting a ticket for that at this point because I think this would probably be enough for the time being, and it's not exactly clear what the flow from GitHub to Metasmoke and on to API clients should look like.

https://chat.stackexchange.com/transcript/11540?m=40109964#40109964

**Comment by quartata** [comment]
@tripleee Looks like we already do send a message on deploy update -- it goes down the SmokeDetector channel though, which is odd because I don't think it's used. Would be trivial to send it down the ApiChannel.

**Comment by ArtOfCode-** [comment]
_cough_ PR material for someone _cough_ ;)

**Comment by quartata** [comment]
https://github.com/Charcoal-SE/metasmoke/pull/285
