### ISSUE TITLE
Refactor API to use a prebuilt solution

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/metasmoke#260]
This will make the API easier to expand and easier to comprehend (*glares at filters*). https://github.com/ruby-grape/grape looks like it might be useful here.

**Comment by ArtOfCode-** [comment]
Easier to comprehend, yes. Not sure I agree with easier to expand... it's *dead easy* to expand our existing API.

**Comment by Undo1** [comment]
Don't know about closing it. Still worth consideration.

**Comment by ArtOfCode-** [comment]
V2
