### ISSUE TITLE
Domains not extracted from title

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#261]
Some spam posts only contain the spam URL in the title.  The domain name tracking logic should extract URLs from the title as well as from the body.

Example from earlier today: https://metasmoke.erwaysoftware.com/post/88187
(I hope I got the right link -- Metasmoke is down right now.)

I have reported this in chat once or twice before if you need more examples.

**Comment by quartata** [comment]
I think this works now?
