### ISSUE TITLE
Expose domain and tagging functionality in API

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#262]
In order to build automation on top of Metasmoke, getting API routes for the domain information and tagging functionality which was introduced in September would be extremely useful.

https://github.com/Charcoal-SE/metasmoke/pull/252

Quick run-down of use cases I could use right away:

* How many hits for this domain already?
* What tags does this domain have?
* Do we have a whois record on file for this domain?

Exposing all of the basic functionality would seem like the natural solution, but if you have to prioritize, maybe start with those?

**Comment by ArtOfCode-** [comment]
Done with API v2.
