### ISSUE TITLE
Domain listing: Prevent user from editing domain name

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#265]
It's been possible to edit the domain name itself but this is not useful, it just breaks the link between the extracted domain name and the record.

Please disable this behavior, and please advise how to fix the records I already broke.  Thanks!

**Comment by ArtOfCode-** [comment]
Also need to associate `www.` domains with their non-`www.` variants.

**Comment by tripleee** [comment]
If the subdomain has different tags or a different whois record than the TLD we need some manual review.  But for the most part I guess we have been consistent enough that you can just check that they are identical, and then go ahead and merge.  We can't do this blindly (e.g. Blogspot is nominally a TLD but each subdomain is a distinct site) but for www. -> TLD we can probably do it completely automatically (or better yet drop the www. when extracting it).  There should probably be a way to do this selectively, manually when other prefixes come up (ftp.TLD, web.TLD, site.TLD, etc).
