### ISSUE TITLE
Attempting to add an existing tag throws an error

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#267]
In the tags for a domain, if #drugs is already there but you miss it and try to add it again, you get a Ruby traceback.

**Comment by j-f1** [comment]
Can you paste the traceback here so we can see it?

**Comment by ArtOfCode-** [comment]
It'll be a MySQL duplicate primary key entry error, since you can't have the same combination of IDs in the join table twice.
