### ISSUE TITLE
Setup instructions are not working

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#269]
I am trying to set up my own private Metasmoke instance.

`rails db:schema:load` fails, apparently because of https://github.com/rails/rails/issues/26209 which does not currently seem to have a straightforward solution.

I worked around that by disabling all `sqlite3` databases in `config/database.yml`.

Next up, `rails db:seed` fails, apparently because it wants to talk to Redis:

https://gist.github.com/tripleee/e2aae2c58deb59a1d8f4466f432ad878

Chat anchors https://chat.stackexchange.com/transcript/message/40573369#40573369 and https://chat.stackexchange.com/transcript/message/40574161#40574161

Do I need a specific version of Rails (or Redis, or Ruby, or some Gem) or how can I proceed?

**Comment by ArtOfCode-** [comment]
Your `config/database.yml` should define all three databases as MySQL for ease of setup.

You will also need Redis, so that websockets work (and apparently for db:seed now as well).

**Comment by j-f1** [comment]
How can we install Redis?

**Comment by sharabromberg** [comment]
i had to do:
```
$ brew install redis                  # install
$ brew services start redis            # boot it up
$ redis-cli ping                         # returns "PONG" if working correctly
```

**Comment by ArtOfCode-** [comment]
https://redis.io/download#installation

**Comment by tripleee** [comment]
I made some edits to https://charcoal-se.org/ms/Set-up-local-instance-of-metasmoke-(Ubuntu-16.04) -- please review.

**Comment by tripleee** [comment]
https://github.com/tripleee/metasmoke/tree/dockerize contains a Dockerfile and some auxiliary scripts which now seem to set up a testing instance properly as far as I can tell.

**Comment by tripleee** [comment]
More questions and observations: https://chat.stackexchange.com/transcript/message/40594731#40594731

**Comment by j-f1** [comment]
Your email in those commits is incorrect — the private GitHub email address for you is `tripleee@users.noreply.github.com`.

**Comment by tripleee** [comment]
@j-f1 Thanks, I'll force push with correct email.  Updated the wiki some more with the answers I got in chat.

**Comment by tripleee** [comment]
Another update, but the changes I make to my user permissions don't seem to stick.

https://chat.stackexchange.com/transcript/message/40611965#40611965

**Comment by tripleee** [comment]
Permission problem resolved. I think this is pretty much done now.
