### ISSUE TITLE
Mysql2::Error: Unknown column 'deleted.deleted' when using an API filter

### ISSUE THREAD

**Issue by quartata** [Charcoal-SE/metasmoke#270]
Filters appear not to work, as querying one (`/api/posts/between` in my case) causes it to try to access columns that don't exist.

Full error:

```
Mysql2::Error: Unknown column 'deleted.deleted' in 'field list': SELECT deleted.deleted, posts.user_link, posts.username FROM `posts` WHERE (`posts`.`created_at` BETWEEN '1970-01-01 00:00:00' AND '2017-10-18 00:48:24') ORDER BY `posts`.`id` DESC LIMIT 10 OFFSET 0
```

on [line 80 of api_controller.rb](https://github.com/Charcoal-SE/metasmoke/blob/master/app/controllers/api_controller.rb#L80). I was going to take a closer look at that code but it kind of confuses me, it looks like you're ignoring the filter that's passed in and using a hardcoded one? That doesn't make sense since omitting the filter makes it work fine.

**Comment by ArtOfCode-** [comment]
Good luck with anything to do with filter code... Have you read the comment at the top of filterator.rb?

**Comment by ArtOfCode-** [comment]
Closing as an API v1 issue.
