### ISSUE TITLE
Ruby traceback for post 90292

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#272]
I am unable to visit this post in Metasmoke.

https://metasmoke.erwaysoftware.com/post/90292

The adjacent post 90291 works fine.

I'm attaching [the source of the traceback page.](https://github.com/Charcoal-SE/metasmoke/files/1409508/90292traceback.html.txt) (GitHub forces me to add a `.txt` extension but it's obviously properly HTML.)

The error message at the top of the page says

>  Showing /var/railsapps/metasmoke/releases/20171022203154/app/views/posts/show.html.erb where line #90 raised:
> 
> can't convert `nil` into an exact number

**Comment by Undo1** [comment]
Test post deleted by Art: https://chat.stackexchange.com/transcript/11540?m=40721370#40721370

Needs a better error message, probably a flat 404.
