### ISSUE TITLE
Rails backtrace: TypeError in Posts#show

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#278]
https://metasmoke.erwaysoftware.com/post/515 gives me a backtrace:

> Showing /var/railsapps/metasmoke/releases/20171102150746/app/views/posts/show.html.erb where line #90 raised:
>
> can't convert nil into an exact number
>
>  Extracted source (around line #90): 
> ```
> <% end %>
> 
> <% if user_signed_in? && current_user.api_token.present? && !@post.is_fp && !@post.is_deleted? && Time.now - @post.created_at <= 1.hour %>
>  <p>
>
> ```

**Comment by tripleee** [comment]
Spot checks and a bit of bisection suggests all the oldest posts up through 660 have this.

**Comment by j-f1** [comment]
Additionally, fetching it [from the API](https://metasmoke.erwaysoftware.com/api/posts/515?key=d897aa9f315174f081309cef13dfd7caa4ddfec1c2f8641204506636751392a4) fails with `undefined method `site_domain' for nil:NilClass`:

```rb
  def fetch_revision_count(post = nil)
    post ||= self
    # ⬇️ this line here
    params = "key=#{AppConfig['stack_exchange']['key']}&site=#{post.site.site_domain}&filter=!mggE4ZSiE7"

    url = "https://api.stackexchange.com/2.2/posts/#{post.stack_id}/revisions?#{params}"
    revision_list = JSON.parse(Net::HTTP.get_response(URI.parse(url)).body)['items']
```

**Comment by ArtOfCode-** [comment]
We don't have the information we need to find out which sites these old posts were from; unless anyone can think of some way to do that, I'm gonna close this.

**Comment by Undo1** [comment]
Reopening - we can't see what site it's from, but the display page should probably handle that case properly.

**Comment by ArtOfCode-** [comment]
That we can do :)
