### ISSUE TITLE
Better 'protection' of Spammers section

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#282]
We have a system to keep track of spammers' accounts.

Original suggestion [here](https://chat.stackexchange.com/transcript/message/41213099#41213099) (Teachers' Lounge, so mod-only).

It makes sense not to require authentication for that page, but we could start with displaying a warning message on those pages.

**Comment by ArtOfCode-** [comment]
First rule of TL ;)

**Comment by j-f1** [comment]
> First rule of TL ;)

That’s “What’s TL?”, right?

**Comment by ArtOfCode-** [comment]
That'd be the zeroth rule :)

**Comment by Undo1** [comment]
We now require at least one diamond (on any site) to click the "not a spammer" or "nuked" buttons on the page (for any site). This also means we require an account, that's up for debate if we want to.

**Comment by Glorfindel83** [comment]
@Undo1 seems to be broken: https://chat.stackexchange.com/transcript/message/41882310#41882310

**Comment by j-f1** [comment]
(TL[?] link)
