### ISSUE TITLE
'Conflicting feedback across revisions' triggers on posts with no feedback

### ISSUE THREAD

**Issue by Undo1** [Charcoal-SE/metasmoke#286]
In [this example](https://chat.stackexchange.com/transcript/message/41362313#41362313), the first post/revision had `tp` feedback while the second had no feedback at the time of the chat message being posted.

Looks like an issue in this call:

```
conflicting_revisions = Post.where(link: link)
                                               .where.not(id: id)
                                               .where('is_tp != ? or is_fp != ?', is_tp, is_fp)
```

triggering based on `is_tp != true` (due to complete lack of feedback).

**Comment by quartata** [comment]
I had a different predicate initially, which was a bit clunkier in terms of interactions wirh NAAs but didn't do this. Art suggested changing it to the current one -- I pointed out that this would occur, but at the time I think we were both OK with it because it didn't seem that common.

**Comment by quartata** [comment]
#280 for the full discussion

**Comment by ArtOfCode-** [comment]
I think I also misunderstood exactly what case it would trigger on :P

**Comment by Undo1** [comment]
Apparently this was fixed by just shutting off the conflicting feedback warnings in 571cbe77b. Ping @quartata - think this is worth fixing?

**Comment by thesecretmaster** [comment]
@quartata Pinging again re: above

**Comment by ArtOfCode-** [comment]
Closing as no longer relevant with these messages disabled.
