### ISSUE TITLE
'Update now' button in /spammers removes all users

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#287]
Situation before: https://metasmoke.erwaysoftware.com/spammers/site?site=44 with 10 potential spammers:

<img width="601" alt="screen shot 2017-11-26 at 10 56 15" src="https://user-images.githubusercontent.com/24611142/33238985-da08fbb8-d298-11e7-9abf-495d84724942.png">

Only three of those were already deleted:
https://apple.stackexchange.com/users/264669
https://apple.stackexchange.com/users/261619
https://apple.stackexchange.com/users/260651
but the others were not:
https://apple.stackexchange.com/users/264277/angry
https://apple.stackexchange.com/users/261249/user261249
https://apple.stackexchange.com/users/262276/mar-yio
https://apple.stackexchange.com/users/260822/primalift-skin
https://apple.stackexchange.com/users/265280/user265280
https://apple.stackexchange.com/users/265053/saludasd
https://apple.stackexchange.com/users/261907/hair-bloom

After the update has finished, the list is empty nevertheless:

<img width="595" alt="screen shot 2017-11-26 at 10 57 13" src="https://user-images.githubusercontent.com/24611142/33239005-2c547e38-d299-11e7-8efb-a5368bc74876.png">

I'd expect only the three already deleted users to be gone from the list.

Reference: https://chat.stackexchange.com/transcript/11540?m=41278137#41278137

**Comment by ArtOfCode-** [comment]
Norepro recently on other sites

**Comment by Glorfindel83** [comment]
So that leaves the question:
- is it something that happens only on Ask Different
- does it have something to do with my roles (you're admin, I'm just code-admin)
- has something changed (e.g. the page didn't require authentication until a few weeks ago, but now it does)

I'm happy to retry / test again, but you might want to add some logging first. Please let me know.
