### ISSUE TITLE
Skip button for review page.

### ISSUE THREAD

**Issue by Videonauth** [Charcoal-SE/metasmoke#292]
As a new member of the reviewer team, I sometimes have it hard to decide if something is now actually spam and so on. 

Currently I'm running in the situation that I sometimes cannot see the posts anymore in their natural habitat since they have been already deleted, which makes a decision not easier.

In such cases to keep the review page from cluttering it would be nice to have a 'Skip' button, to pass on reviewing said item.

**Comment by ArtOfCode-** [comment]
While we're at it, I'd quite like to record review results. Technically we can already track who gave what feedback in review, via inference and deduction and some clever use of admin tools, but we should ideally be tracking it all in a new ReviewResult models.

**Comment by ArtOfCode-** [comment]
All of the above done
