### ISSUE TITLE
Expose search result page as RSS feed

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/metasmoke#298]
If we expose the search result page, moderators using private chat channels could use the link to the rss feed, seeing the latest posts, without causing any information leakage compared to the alternative solution of inviting the smokey account.

Exposing the search page instead of the posts page also has its advantages that moderators could filter the information in a way they want to use it, instead of sticking with predefined filters we provide them.

This has been suggested by [me](https://chat.stackexchange.com/transcript/message/41724154#41724154) and [quartata](https://chat.stackexchange.com/transcript/message/40340847#40340847) before.

**Comment by ArtOfCode-** [comment]
Doing this as part of API v2.0.

**Comment by ArtOfCode-** [comment]
626c16f0dbf5478f61b1498b06cc0f577aa6c734
