### ISSUE TITLE
Mod Sites API returns null user ids

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/metasmoke#302]
The first page returns mod sites with `user_id` set to `null`. https://metasmoke.erwaysoftware.com/api/v2.0/mods?key=1658080a59604fa5386e39290dd415ed5270dc6f12fab053cd4cc3d32cb154d4&per_page=100

However, after 50 pages, you start to get useful results: https://metasmoke.erwaysoftware.com/api/v2.0/mods?key=1658080a59604fa5386e39290dd415ed5270dc6f12fab053cd4cc3d32cb154d4&per_page=100&page=50

(xref https://github.com/Charcoal-SE/metasmoke/issues/301#issuecomment-353398916)

/cc @ArtOfCode-

**Comment by Undo1** [comment]
https://github.com/Charcoal-SE/metasmoke/commit/3ca5b4832f & truncated the table. Returns expected results now.
