### ISSUE TITLE
Alert on condition disable

### ISSUE THREAD

**Issue by CalvT** [Charcoal-SE/metasmoke#307]
I recently checked my autoflags graph, and noticed that none had been cast since the middle of December. After a bit of digging around, I found that the problem was that my autoflagging condition had been disabled.

Now I know this is very much edge case, (might even only happen to me?) but I'd like to be notified/emailed if my autoflagging condition is disabled.

**Comment by ArtOfCode-** [comment]
Probably easier to send a thing to chat to ping you - we have the websocket

**Comment by quartata** [comment]
If I'm not mistaken it already sends you an email when this occurs.

**Comment by ArtOfCode-** [comment]
You are mistaken :)

**Comment by quartata** [comment]
I was thinking of this, which is currently commented out: https://github.com/Charcoal-SE/metasmoke/blob/master/app/mailers/autoflagging_mailer.rb#L10

**Comment by ArtOfCode-** [comment]
and that's for setting changes, in any case, not for condition disables

**Comment by zixuan75** [comment]
#1 This issue it the identical.

**Comment by ArtOfCode-** [comment]
@zixuan75 Your contributions to Charcoal repositories so far have been entirely nonsensical. Please either explain what you're doing and why it's necessary, or stop doing it. If you can't do either of those, your next ban will be much more permanent.

**Comment by zixuan75** [comment]
I don't understand what you are saying, are you saying what are my comments mean?
