### ISSUE TITLE
SE authentication not possible

### ISSUE THREAD

**Issue by pbdevch** [Charcoal-SE/metasmoke#309]
I can't authenticate my MetaSmoke account with Stack Exchange. I land on a [error page](https://stackexchange.com/error?aspxerrorpath=/oauth).

Steps to reproduce:

1. Create a new account (not sure if this is actually needed)
2. Go to https://metasmoke.erwaysoftware.com/authentication/status
3. Click the green "Authenticate" button
4. And you're at the already mentioned error page

**Comment by Undo1** [comment]
I'm unable to repro this using either my account or a fresh account. Are there any other details you have?

This feels like an SE-side issue.

**Comment by teward** [comment]
No-repro with my sockpuppet account that runs my AquariusOne chat bot account on other channels.  Definitely sounds like an SE-side problem, I'd ask the SE staff to see if there's something up with your account (perhaps your account has some type of suspension or some time of reputation related thing preventing this from working?)

**Comment by pbdevch** [comment]
Apparently, I can't repro it myself now. Maybe it was a temporary issue or was connected to the permissions of Metasmoke (I've been granted the MS Reviewer permissions in the meantime).
