### ISSUE TITLE
Internal Server Error while trying to submit feedback via /review

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#310]
I'm trying to submit 'Spam / Abusive' feedback to this post: https://metasmoke.erwaysoftware.com/post/104135
via https://metasmoke.erwaysoftware.com/review
but I get a 500 - Internal Server Error in the console. As can be seen here: https://chat.stackexchange.com/transcript/message/42559624#42559624 the feedback is somehow pushed to Smokey, but fails to be stored.

**Comment by ArtOfCode-** [comment]
Only occurs on that post - it doesn't have a site associated, for some reason, so it bugs out when you try to get the site URL

**Comment by j-f1** [comment]
Can you manually set it to writing.SE?

**Comment by quartata** [comment]
Yes but only Undo can do that

**Comment by Undo1** [comment]
Done

**Comment by j-f1** [comment]
Now it thinks the favicon is for [meta Technical Communication](https://techcomm.meta.stackexchange.com/):

![tc](https://cdn.sstatic.net/Sites/techcommmeta/img/favicon.ico)
