### ISSUE TITLE
Bug in announcements

### ISSUE THREAD

**Issue by paper1111** [Charcoal-SE/metasmoke#311]
The `<span>` is shown...?

![bug](https://user-images.githubusercontent.com/30367398/35565143-4927fe0e-05f7-11e8-9f9f-f0783dab5302.png)

**Comment by surajrao** [comment]
Something must have occurred https://github.com/Charcoal-SE/metasmoke/commit/23fa0c0318236d2d1a79daa654e3082cda5f0f6d#diff-9599427925097c3c66f26ac1e0de5cad.. I think need to use `.html_safe`. https://stackoverflow.com/a/12399977/4826457

**Comment by angussidney** [comment]
Additionally, everything in the HTML is being title-cased due to [this line](https://github.com/Charcoal-SE/metasmoke/blob/master/app/helpers/application_helper.rb#L40), which isn't ideal.
