### ISSUE TITLE
Rename 'Code Admin' role to 'Blacklist manager'

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#318]
### Scroll down for up-for-grabs summary and guidance.

I'm proposing that we rename the code admin role to 'Blacklist manager' or similar.

Originally, this privilege was only given to people who had push access to the repo on Github (hence the name 'code admin'). But once the blacklist command was introduced, and we wanted to allow non-collaborators to edit the blacklist too, this definition quickly broke down. 

Today, the role is used [almost exclusively for blacklisting](https://github.com/Charcoal-SE/SmokeDetector/wiki/Privileges#code-admin-aka-blacklister-ms). The only privilege which would make more sense for an actual code admin is the ability to failover.

👍 to rename it, 👎 to leave it, and comment if you have other ideas.

**Comment by ArtOfCode-** [comment]
Indifferent. A rename makes more semantic sense, but the current name isn't causing problems beyond a bit of confusion on occasion.

**Comment by angussidney** [comment]
It's a relatively simple change to make, so I'm willing to do it.

**Comment by iBug** [comment]
Not sure if this is a big change.

Currently the only thing Blacklist Maintainers can do is issue new keywords and approve non-code-privileged users' issues. If one accidentally made a typo when blacklisting, or if one needs to merge or delete a blacklist item, they need to propose a PR and wait for it to be merged by a real code admin.

So, we could extend this, probably by allowing BMs to commit directly to the blacklist `.txt` files. This is not possible as per the design of GitHub, so I think we could allow a bot that merges the PRs from BMs automatically, if only the blacklist files are changed. This way we are really getting "**Maintainers**" (instead of "Blacklist **Adders**").

**Comment by ArtOfCode-** [comment]
I'm sure we looked at something like that... Not sure where it got to

**Comment by angussidney** [comment]
Honestly, I don’t think hint it’s worth setting up a bot like that since Helios will allow the same functionality once it is implemented.

**Comment by thesecretmaster** [comment]
@ArtOfCode- Are you closing this as status-declined? Or just something we'll need to open another issue about later?

**Comment by angussidney** [comment]
Looks like a good hacktoberfest issue

**Comment by ArtOfCode-** [comment]
![contrib-guidance](https://user-images.githubusercontent.com/10406565/45100551-949aa500-b121-11e8-93e9-0bda7186d113.png)

# Summary
**Difficulty:** Easy  
**Scope:** Wide
**Issue Owner:** @ArtOfCode-

This issue involves renaming one of the permissions in Charcoal's systems. It's currently called "code admin", but that doesn't reflect what it actually _is_ very well, so we'd like to update it to "blacklist manager".

For the most part this should be relatively easy find-and-replace, but there are places where you'll need to take care that other things relying on the current name don't break. You'll also need to rename the permission across multiple Charcoal projects - not only this one (metasmoke), but also [SmokeDetector](https://github.com/Charcoal-SE/SmokeDetector) and [our website repository](https://github.com/Charcoal-SE/charcoal-se.github.io).

# Guidance
You'll need to rename the permission in several places. I'd suggest starting off with the permission itself (which you'll find in `Role#names`, in `app/models/role.rb`). Once you've done that, have a look for other occurrences - that might be role checks, before_actions, method names, etc. Variable names aren't as important to update as method names, but would still be awesome to do if you have the time. You'll also need to update references to any methods you rename.

If you want to leave it there, send in a pull request to this repository and we'll review it together. If you'd like to carry on, you can also rename the permission in other places we use it - [SmokeDetector](https://github.com/Charcoal-SE/SmokeDetector) is the most important, followed by documentation and so on in [our website](https://github.com/Charcoal-SE/charcoal-se.github.io). If you need more guidance about those two repositories, let this issue's owner (listed above) know in this or any related thread.

**Comment by Zohvek** [comment]
Attempting a commit to resolve this issue. Thanks for checking it out. ^^^

**Comment by snpd25** [comment]
@ArtOfCode- , Can you please help to know which file needs modification

**Comment by ArtOfCode-** [comment]
@snpd25 There are lots. Have a read of the Guidance section in my comment above, that should give you an idea of where to start, but it won't be a single file - there are multiple files across several projects.

**Comment by snpd25** [comment]
@ArtOfCode- Few migrations are also required to be run, right?

**Comment by thesecretmaster** [comment]
Seeing as this PR has been merged, is this status-complete?

**Comment by teward** [comment]
Closed by #682
