### ISSUE TITLE
False positive feedback via API does not delete smokey message

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#32]
When you reply `sd f` to a smokey message, Smokey will attempt to delete the message.

However, when you feedback via the API (i.e. FDSC), smokey does not attempt to delete the message.

I know that `tpu` and `naa` feedbacks are already sent back to smokey for various purposes, so it should be fairly easy to send `fp` feedbacks across the websocket too.

(I reported this here since it is MS which sends smokey the message on API feedback)

**Comment by magisch** [comment]
Doesn't sound like a bug, sounds more like it would be nice as a feature request.

**Comment by ArtOfCode-** [comment]
Should be fixed now that we send fp feedback down the websocket.
