### ISSUE TITLE
MS Not Autoflagging Spam on User Feedback

### ISSUE THREAD

**Issue by K-Davis1** [Charcoal-SE/metasmoke#330]
I encountered a bug when providing feedback to a spam post within chat the post would not be flagged as spam.

With the assistance of ArtOfCode, we determined that it was an issue with the MS auth token being invalidated somehow.

Upon manually revoking and reauthenticating the token, this resolved the problem. 

Perhaps after a few consecutive failed flag attempts a post can be auto-generated in chat recommending the user to reauthenticate MS with SE.

![Error](https://i.stack.imgur.com/soVmP.png)

**Comment by angussidney** [comment]
A more accurate title would probably be 'FIRE submitting feedback but not flagging'

**Comment by ArtOfCode-** [comment]
@angussidney that'd be a bug report, which this is not :) this is an FR for MS to post to chat if a user's flags keep failing to go through.

**Comment by ArtOfCode-** [comment]
Determined this was an issue with a Chrome extension, not MS.
