### ISSUE TITLE
Add autoflags to the ttd graph at /graphs

### ISSUE THREAD

**Issue by izwick-schachter** [Charcoal-SE/metasmoke#335]
Pretty much in the title.

**Comment by ArtOfCode-** [comment]
Uh... issue descriptions are useful ;)

What are you thinking this would look like? Autoflags and TTD are on different scales entirely; are you thinking some frequency-based series, cumulative, time-based?

**Comment by izwick-schachter** [comment]
I was thinking that we could have one side with a y-axis of seconds (ttd) and the other side is flags (autoflags). It would be interesting to see the relationship between autoflags and TTD, IMO.

**Comment by angussidney** [comment]
After the current 5-flag experiment is over, we'll only cast 5 flags per post, so that graph won't show anything interesting.

**Comment by izwick-schachter** [comment]
I thought we were planning on making it a sliding scale of some sort? e.g 3 on 99% certainty, 4 on 99.9%, 5 on 99.99%. But anyways, I kinda agree that it wouldn't be useful. I ... don't really know what I was thinking.

**Comment by angussidney** [comment]
You're right - I completely forgot about how we're planning to do a sliding scale.
