### ISSUE TITLE
'Require' two reviews for every post

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#339]
Once we start casting five autoflags, only a single Charcoaler is required to nuke a post, often giving feedback in the process, via FDSC or FIRE. To minimize the effects of this user making a mistake, i.e. flagging a false positive, we should ideally require *two* reviews per report instead of one. In other words, /review should show all posts you haven't reviewed with less than two feedbacks.

Reference: https://chat.stackexchange.com/transcript/message/43223159#43223159 and the next 6-8 messages.

**Comment by izwick-schachter** [comment]
It might be interesting to make this something that users can opt-in to. E.g. "I want to review anything on site <x> with more than <y> autoflags that has more than <z> reviews by users with more than <q> site rep already." This would also allow mods/users to do their own oversight of Charcoal, which IIRC was requested.

**Comment by angussidney** [comment]
Fixed by 2808d8cf26cb2b56dee8e4f7d5e36d734d3633f9

@thesecretmaster Can I suggest you make a separate issue if you still want that implemented.
