### ISSUE TITLE
Don't let self-invalidated feedback count against you.

### ISSUE THREAD

**Issue by Cerbrus** [Charcoal-SE/metasmoke#341]
Currently, on your feedback overview, there's a percentage shown that indicates how much of your feedback is invalidated. For me, [that page](https://metasmoke.erwaysoftware.com/admin/user_feedback?user_id=52) shows:

> **1261** feedbacks, **29** invalidated (**2.3%** invalid)

However, this doesn't take into consideration that **19** of those invalidated feedbacks [are invalidated by myself](https://chat.stackexchange.com/transcript/message/43237602#43237602).

Self-invalidated feedback shouldn't count against you. It's a bit of a [artifact of older days](https://chat.stackexchange.com/transcript/message/43237544#43237544) that it does.

Leaving out those 19 feedbacks, the numbers change significantly:

> **1261** feedbacks, **10** invalidated (**0.79%** invalid)

I propose the calculation behind that row is updated to leave out self-invalidated feedback.

**Comment by honnza** [comment]
Not sure about that. If your incorrect feedback (I assume FIRE) causes the post to be deleted, you can retract the feedback on Metasmoke but you can't retract your flag against the post. This will be even more important if we are to set up 5x autoflagging.

**Comment by Cerbrus** [comment]
@honnza: I'm pretty sure most of those 19 self-invalidated feedbacks were from testing / developing FIRE.
Feedback that wasn't retracted by yourself (so retracted by MS staff) would still count against you.

**Comment by ArtOfCode-** [comment]
0d7d997a11e5f93c1d1c96a85b511937fe525af7
