### ISSUE TITLE
Review shows a teasing 2, but I don't have priveleges

### ISSUE THREAD

**Issue by tschallacka** [Charcoal-SE/metasmoke#342]
As the image below shows, it gives me a nice (2) in the menu, but I don't have the privilege to look at it.

Add a privilege check before pushing the status to the menu?

![image](https://user-images.githubusercontent.com/8638425/37036892-573ef6c6-2151-11e8-98b5-12f50b385e75.png)

**Comment by j-f1** [comment]
We should probably hide the item unless you can view the page.

**Comment by ArtOfCode-** [comment]
3a92a8544d1f36615d8fc792d1b61b6a5d1ec062
