### ISSUE TITLE
Feature request: Clickable tags in list view smoke detector

### ISSUE THREAD

**Issue by tschallacka** [Charcoal-SE/metasmoke#344]
On the page https://metasmoke.erwaysoftware.com/posts

![image](https://user-images.githubusercontent.com/8638425/37082641-5a2d87b6-21ed-11e8-9d8b-6ac3b878b477.png)

Here the `Blacklisted website in answer` is not clickable

Here it is https://metasmoke.erwaysoftware.com/post/109242

![image](https://user-images.githubusercontent.com/8638425/37082617-47fabed8-21ed-11e8-9b38-a32663580097.png)

It would be nice to also make the tags on https://metasmoke.erwaysoftware.com/posts clickable to go the the list view for that tag?

**Comment by ArtOfCode-** [comment]
Completed
