### ISSUE TITLE
FP submitted through API doesn't remove user from blacklist

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#346]
Currently, if you submit a `fp` in chat, the user is automatically removed from the blacklist. However, if you submit a `fp` through the API (e.g. FIRE), then the user is not removed from the blacklist.

**Comment by angussidney** [comment]
See also: https://github.com/Charcoal-SE/SmokeDetector/issues/1072

Although it's not worded in the best way, they're both asking for FP API feedbacks to remove the user from the blacklist.

**Comment by thesecretmaster** [comment]
So, is this something that should be fixed in MS? It seems like a SmokeDetector issue to me.

**Comment by makyen** [comment]
@thesecretmaster I'm fine with wherever it's appropriate.

Given that my issue is that I want the metasmoke API to be changed, I had assumed it went in the metasmoke repository. I don't really know how the code is partitioned, but I'd assumed it was the "metasmoke API", not the "SmokeDetector API", in part, to indicate that it was in this project/repository.

**Comment by quartata** [comment]
This does require Metasmoke change

**Comment by quartata** [comment]
This couldn't be consistently done with Metasmoke changes (if it had been recently reported, we'd have the owner URL on hand and could use that but we aren't guaranteed)

**Comment by ArtOfCode-** [comment]
Completed

**Comment by makyen** [comment]
This does not appear to have been fixed. Or at least I believe MS has deployed more recently than 10 days ago. See [this instance](https://chat.stackexchange.com/transcript/message/43809031#43809031) of SD indicating that a user still needed to be manually removed from the blacklist when they had been given 3 `fp` feedbacks from two people on two different reports, both of which the only reason was that the user was blacklisted.

**Comment by j-f1** [comment]
The [code status page](https://metasmoke.erwaysoftware.com/status/code) says metasmoke is running the latest commit.

**Comment by tripleee** [comment]
Tangentially, it would be nice if there was a way to say "this was an FP but I don't want this troll to be removed from the blacklist just yet".
