### ISSUE TITLE
Posts visible in /review even if I've already reviewed them

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#347]
For a couple of days now, posts require two feedbacks to not appear in /review. However, even if I've already provided feedback, I still see those posts in /review if nobody else did. This is slightly confusing.

**Comment by ArtOfCode-** [comment]
Can't repro locally. If this happens again, let me know the post ID ASAP.

**Comment by Glorfindel83** [comment]
@ArtOfCode- it happened again today: https://metasmoke.erwaysoftware.com/post/112109
I gave my (first) feedback from chat, maybe that helps in reproducing it?

**Comment by ArtOfCode-** [comment]
Ah, so you gave feedback from chat, but it still showed up in review for you after? I guess that's _technically_ by-design, but it's not particularly intuitive... I'll see if it can be fixed.

**Comment by ArtOfCode-** [comment]
Solved with the new review system
