### ISSUE TITLE
Feature Request: weekly average of statistics

### ISSUE THREAD

**Issue by Wrzlprmft** [Charcoal-SE/metasmoke#348]
The time series on Metasmoke show daily data, making it quite difficult to discern long-term effects under the typical weekly oscillation. It would be nice to be able to enable weekly averaging to avoid this effect. (A completely user-controlled averaging would be even better.)

**Comment by ArtOfCode-** [comment]
Calling this [status-declined] because the SQL exploder exists now and can be used for this kind of thing.
