### ISSUE TITLE
API Route Request: Get posts by date range

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/metasmoke#36]
I'd like the ability to retrieve posts that were reported within a certain datetime range. This would be similar to `/api/posts/feedback`, but take two parameters - `startdate` and `enddate`

### Request

    HTTP/1.1 GET /api/posts/daterange?startdate=1476102300&enddate=1476145500

This would return all posts between Oct 10, 2016 12:25 PM and Oct 11, 2016 12:25 AM. Time zone is assumed to be UTC. I am not requesting any timezone math be implemented.

**Comment by ArtOfCode-** [comment]
Documentation upcoming.
