### ISSUE TITLE
API Route Request: Posts by site

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/metasmoke#37]
I'd like the ability to retrieve all posts by a specific site. This route would return a list of MS IDs which can then be used to gather more information.

### Request

     HTTP/1.1 GET /api/posts/site?url=drupal.stackexchange.com

This call would return everything from `drupal.stackexchange.com`

**Comment by ArtOfCode-** [comment]
Documentation upcoming.

**Comment by zixuan75** [comment]
Si no de xi an.
