### ISSUE TITLE
'Invalidated by' column on the invalidated feedback page is empty

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#390]
The 'Invalidated by' column on the [invalidated feedback page]( https://metasmoke.erwaysoftware.com/admin/invalidated) is empty.

<img width="625" alt="screen shot 2018-04-02 at 16 04 06" src="https://user-images.githubusercontent.com/24611142/38199061-8c92e0dc-368f-11e8-9a9c-d42b88f4b065.png">

**Comment by angussidney** [comment]
This was definitely working a week or two ago when I last checked the page.

**Comment by angussidney** [comment]
https://github.com/Charcoal-SE/metasmoke/commit/3c3d8705d42369b25a34157b64940ce8484e8435
