### ISSUE TITLE
Assign lower priority to MS web access (e.g. searches) than to MS API access

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#391]
Over the last while I've noticed a consistent correlation between when I do a search on MS via the [search web interface](https://metasmoke.erwaysoftware.com/search) and when I see, and people report, delays/timeouts in using FIRE/AIM.

SD being able to access MS and people being able to use the MS API (e.g. FIRE, AIM, etc.) is something that should not be affected by resources requested by someone using the MS web interface (or at most minimally affected).

**Comment by ArtOfCode-** [comment]
This would be nice, but is kinda pretty difficult. I'm not convinced it's worth the significant effort it would take.

**Comment by quartata** [comment]
this isn't so much a "priority" thing as it is a "mysql queries are blocking and we only have one worker" deal
