### ISSUE TITLE
Remove duplicate messages about CI.

### ISSUE THREAD

**Issue by gsquaredxc** [Charcoal-SE/metasmoke#393]
MetaSmoke seems to be outputting duplicate messages relating to CI.
For example:

    [ metasmoke ] ci/circleci success on cae3898: Your tests passed on CircleCI!
    [ metasmoke ] ci/circleci success on cae3898: Your tests passed on CircleCI!

[Permalink](https://chat.stackexchange.com/transcript/message/43761611#43761611)
This is takes up premium real estate on the screen, preventing users from acting on spam. However, this does not occur 100% of the time. This is a minor and (probably) easy to fix bug.

**Comment by gsquaredxc** [comment]
Wrong repo lol.

**Comment by NobodyNada** [comment]
@gsquaredxc The messages come from Metasmoke AFAIK, so I think the issue is more appropriate here.
