### ISSUE TITLE
channel-verify broken?

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#395]
PrincessLuna and IIRC some others are saying the mechanism we have in place for joining Teams is not operating properly. Is it broken or turned off on purpose?

https://chat.stackexchange.com/transcript/message/43811163#43811163

**Comment by LunarWatcher** [comment]
It looks like it's still broken (and yes, with the new system). It never arrives in the /channels/link/ endpoint.

**Comment by ArtOfCode-** [comment]
@Undo1 needs to check configurations
