### ISSUE TITLE
Clicking the same option in MS multiple times causes smokey to output multiple messages.

### ISSUE THREAD

**Issue by gsquaredxc** [Charcoal-SE/metasmoke#396]
This issue happens when you select tpu-, fp, or naa inside of MS. [This](https://metasmoke.erwaysoftware.com/post/113728) is a page that this occurs on. Every time you select it, it causes smokey to post a message. Select it 5 times, 5 messages. This does not always occur, but occurs 100% of the time for me personally. [Chat messages](https://chat.stackexchange.com/transcript/message/43848965#43848965). I deleted a few messages, but quite a bit remain to show this. Essentially, only one message should occur unless it was changed, for instance from tpu- to fp.

**Comment by CalvT** [comment]
And here's a gif of it for lolz:

![ice_video_20180406-145505](https://user-images.githubusercontent.com/15909971/38436489-1afe3e02-39ab-11e8-9222-1da24150db0a.gif)

Note that doing this particular one did not cause Smokey to report it, but doing others did.

**Comment by Undo1** [comment]
Seems likely that Art's feedback system overhaul in 460e7dadcbce2303825ac0ccfc5b86379c087ac3 fixed this. Duplicate feedback should be rejected in all cases.
