### ISSUE TITLE
Expose SQL data explorer

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#398]
Currently, the SQL data explorer is not discoverable.

https://github.com/tripleee/metasmoke/tree/sql-menu has my no doubt incompetent attempt to figure out how to add it. The first commit might actually be useful. The second mainly just illustrates how lost I am.

**Comment by j-f1** [comment]
The `nav_link` function is defined [here](https://github.com/Charcoal-SE/metasmoke/blob/master/app/helpers/application_helper.rb#L12). From my exploration of the Blazer source, this should work:

```erb
<%= nav_link Blazer::QueriesController, action: :home, label: 'SQL Data Explorer' %>
```
