### ISSUE TITLE
Support white theme for the sql editor

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/metasmoke#399]
The editor on the [/data](https://metasmoke.erwaysoftware.com/data) page already has white theme support, why not have it on [/data/sql](https://metasmoke.erwaysoftware.com/data/sql/queries/new) too?

Supporting white themes is useful, because for some people it's less harmful to the eyes.

**Comment by j-f1** [comment]
This might be an issue for [blazer](https://github.com/ankane/blazer), the tool used to run the SQL explorer.

**Comment by ArtOfCode-** [comment]
Would be good, but [status-declined]. This isn't something we have control over - it's not the same editor as is used in the JS exploder, so this would need upstream work on Blazer, as JF said.
