### ISSUE TITLE
Tetsuya Yamamoto can't !!/watch or !!/blacklist

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#401]
Tetsuya has Code Admin privileges, but the blacklist commands still generate a PR which needs to be approved.

This is apparently a known bug; can we get it fixed?

https://chat.stackexchange.com/transcript/message/44202256#44202256

**Comment by angussidney** [comment]
If [this](https://github.com/Charcoal-SE/metasmoke/blob/master/app/controllers/users_controller.rb#L116) works, the problem should be able to be fixed with a single button press.

**Comment by ArtOfCode-** [comment]
It didn't work; I fixed it; it works; I pressed the button. Try again, see if it's fixed.
