### ISSUE TITLE
New /uid link not working for MathOverflow

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#402]
Report: https://chat.stackexchange.com/transcript/message/44326539#44326539
Contains a link to: https://m.erwaysoftware.com/posts/uid/mathoverflow/299145
Following that link gives the error:

> Post not found for mathoverflow/299145. It may have been reported during a period of metasmoke downtime.

even though the post *is* in metasmoke: https://metasmoke.erwaysoftware.com/post/117431

(I haven't tested this, but my guess is that it's related to MathOverflow, which has a different TLD, .net, which might throw the logic off. If this is the case, it would be good to double-check other domains as well, e.g. StackApps, SuperUser, ServerFault, AskUbuntu)

Another MathOverflow example: https://chat.stackexchange.com/transcript/11540?m=44253575#44253575
SuperUser seems to work, from an n=1 test.

**Comment by ArtOfCode-** [comment]
Weird, the tests pass for MO... unless I got the API param wrong.

**Comment by ArtOfCode-** [comment]
Fixed
