### ISSUE TITLE
View more records per page

### ISSUE THREAD

**Issue by WELZ-gh** [Charcoal-SE/metasmoke#404]
On feedback pages (or other pages with a bunch of data) It's currently limited to 100 (?) records per page.

It'd be nice if we can go higher (100 | 250 | 500) maybe even (1000) records per page , o that a user can "sort" more records at once.

**Comment by ArtOfCode-** [comment]
100 is probably the maximum sane limit for posts. Other types we can go higher on.

**Comment by WELZ-gh** [comment]
@ArtOfCode- For user data or feedbacks (those were the ones I was particularly getting annoyed about)
