### ISSUE TITLE
Can't update duplicate domain

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#405]
There are duplicate entries for some domains. This is otherwise rather harmless, but it prevents updating a domain record when it has a duplicate.

~~Back when domain tags were introduced, I sometimes changed the domain name from www.domain to just domain. This is now biting me in the rear. Can these somehow be reverted in bulk?~~

For example, I cannot save edits to https://metasmoke.erwaysoftware.com/domains/10010 `besthealthdiet.com` because it clashes with https://metasmoke.erwaysoftware.com/domains/14424 ~~(nominally `www.besthealthdiet.com` but I edited it to refer to `besthealtdiet.com` too).~~

I'll be happy to figure out which domains exactly need this, if there is some hope that they can all be fixed.

**Comment by ArtOfCode-** [comment]
cc'ing @Undo1 for console magic

**Comment by Undo1** [comment]
I can definitely update them in bulk. Throw me a list of ids/strings and the desired transformation(s) and I'll get it done.

**Comment by tripleee** [comment]
Here: https://metasmoke.erwaysoftware.com/data/sql/queries/42-duplicate-domain-tags-405

**Comment by tripleee** [comment]
... Actually, looks like my query unearthed more than just the ones I had manually edited, and possibly not those at all, but still a useful diagnostic (currently 39 rows). At least `besthealthdiet.com` and `drozien.com` in those results look like they are an example of what I originally reported, but some of the other results are just duplicates (e.g. `basij.um.ac.ir` seems to have been extracted twice from a single post somehow).

**Comment by tripleee** [comment]
The symptoms are more complex than I thought, and there may be more than a single root cause.

There does *not* seem to be a need to rename things, generally speaking.

I _think_ that where I had manually renamed the `www.something` domain to just `something`, this would then result in a new `www.something` record to be created.  Perhaps this is also the reason it appears like some domain was extracted twice from some posts, but I can't completely confirm this; there may be a separate bug behind that.

In addition, it looks like some duplicate domain records were created simply because of a race condition.

The end result is that many records are redundant and could simply be removed by myself; but others are more complex, and need some manual merging.

I've tried to order this by order of complexity, hardest first, but I might not have a full understanding of what it takes to fix them.

* `besthealtdiet.com` [9428](https://metasmoke.erwaysoftware.com/domains/9428) should be renamed to `www.besthealtdiet.com` and merged with [14428](https://metasmoke.erwaysoftware.com/domains/14428)
* Some domain names have multiple records which should be merged. I speculate that there was a race condition of some sort when these were created; you'll notice they are usually adjacent.
  * `osxuninstaller.com`:
    * Domain record [16431](https://metasmoke.erwaysoftware.com/domains/16431) extracted from sample [95820](https://metasmoke.erwaysoftware.com/post/95820)
    * Domain record [16432](https://metasmoke.erwaysoftware.com/domains/16432) extracted from sample [95821](https://metasmoke.erwaysoftware.com/post/95821)
    * Domain record [16433](https://metasmoke.erwaysoftware.com/domains/16433) extracted from sample [95822](https://metasmoke.erwaysoftware.com/post/95822)
  * `sparechange.io`:
    * Domain record [16752](https://metasmoke.erwaysoftware.com/domains/16752)
    * Domain record [16753](https://metasmoke.erwaysoftware.com/domains/16753)
  * `www.btwvisas.com`:
    * Domain record [15988](https://metasmoke.erwaysoftware.com/domains/15988)
    * Domain record [15989](https://metasmoke.erwaysoftware.com/domains/15989)
  * `www.canonprintersdrivers.com`:
    * Domain record [15405](https://metasmoke.erwaysoftware.com/domains/15405)
    * Domain record [15406](https://metasmoke.erwaysoftware.com/domains/15406)
  * `www.firstmats.co.uk`:
    * Domain record [15986](https://metasmoke.erwaysoftware.com/domains/15986)
    * Domain record [15987](https://metasmoke.erwaysoftware.com/domains/15987)
  * `www.miracgogo.com`:
    * Domain record [15670](https://metasmoke.erwaysoftware.com/domains/15670)
    * Domain record [15671](https://metasmoke.erwaysoftware.com/domains/15671)

There is a duplicate for `www.timberdoorsmelbourne.net.au` but it's because there are two post records for the same post; [95607](https://metasmoke.erwaysoftware.com/post/95607) should be deleted as it duplicates [95606](https://metasmoke.erwaysoftware.com/post/95606) and then the domain record [16386](https://metasmoke.erwaysoftware.com/domains/16386) can be zapped.

----
These were so trivial I could handle them myself. I'm listing them here for reference.

* These had redundant records, where one of them should simply be removed. Basically, this looked like the same domain was extracted twice.
  * `basij.um.ac.ir` was extracted twice in sample [108345](https://metasmoke.erwaysoftware.com/post/108345)
    * Removed duplicate domain record [19126](https://metasmoke.erwaysoftware.com/domains/19126) and leave [19125](https://metasmoke.erwaysoftware.com/domains/19125)
  * `besthealthdiet.com` was extracted twice in samples [62920](https://metasmoke.erwaysoftware.com/post/62920),  and 
    * Removed duplicate domain record [10010](https://metasmoke.erwaysoftware.com/domains/10010)
  * Ditto in samples [87289](https://metasmoke.erwaysoftware.com/post/87289) and [87288](https://metasmoke.erwaysoftware.com/post/87288)
    * Removed duplicate domain record [14424](https://metasmoke.erwaysoftware.com/domains/14424)
  * Several domain names were extracted twice in sample [101452](https://metasmoke.erwaysoftware.com/post/101452)
      * `cdn.firebase.com`: Removed duplicate domain record [17589](https://metasmoke.erwaysoftware.com/domains/17589)
    * `d2zah9y47r7bi2.cloudfront.net`: Removed duplicate domain record [17591](https://metasmoke.erwaysoftware.com/domains/17591)
    * `browser-update.org`: Removed duplicate domain record [17593](https://metasmoke.erwaysoftware.com/domains/17593)
    * `fast.fonts.net`: Removed duplicate domain record [17595](https://metasmoke.erwaysoftware.com/domains/17595)
    * `cdn.heapanalytics.com`: Removed duplicate domain record [17598](https://metasmoke.erwaysoftware.com/domains/17598)
  * `BSIpro.com` was extracted twice in sample [88467](https://metasmoke.erwaysoftware.com/post/88467)
    * Removed duplicate domain record [14677](https://metasmoke.erwaysoftware.com/domains/14677)
  * (`www.`) `drozien.com` was extracted twice in sample [86963](https://metasmoke.erwaysoftware.com/post/86963)
    * Removed duplicate domain record [14346](https://metasmoke.erwaysoftware.com/domains/14346)
  * (`www.`) `facts4supplement.com` was extracted twice in samples [86961](https://metasmoke.erwaysoftware.com/post/86961) and [86992](https://metasmoke.erwaysoftware.com/post/86992]
    * Removed duplicate domain record [14345](https://metasmoke.erwaysoftware.com/domains/14345)
    * Removed duplicate domain record [14349](https://metasmoke.erwaysoftware.com/domains/14349)
  * (`www.`) `healthprograme.com` was extracted twice in 14 samples
    * Removed duplicate domain record [9042](https://metasmoke.erwaysoftware.com/domains/9042)
  * `howtoways.com` was extracted twice in sample [85795](https://metasmoke.erwaysoftware.com/post/85795)
    * Removed duplicate domain record [14150](https://metasmoke.erwaysoftware.com/domains/14150)
  * `idpro.info` was extracted twice in sample [102844](https://metasmoke.erwaysoftware.com/post/102844)
    * Removed duplicate domain record [17927](https://metasmoke.erwaysoftware.com/domains/17927)
  * `jorendrasingh.me` was extracted twice in sample [107061](https://metasmoke.erwaysoftware.com/post/107061)
    * Removed duplicate domain record [18798](https://metasmoke.erwaysoftware.com/domains/18798)
  * `nutritionfit.org` was extracted twice in 7 samples
    * Removed duplicate domain record [6416](https://metasmoke.erwaysoftware.com/domains/6416)
  * `reddit.com` and `tumblr.com` was extracted twice in sample [103237](https://metasmoke.erwaysoftware.com/post/103237)
    * Removed duplicate domain record [17998](https://metasmoke.erwaysoftware.com/domains/17998) for `reddit.com`
    * Removed duplicate domain record [18000](https://metasmoke.erwaysoftware.com/domains/18000) for `tumblr.com`
  * `saintpat1985.wordpress.com` was extracted twice in sample [84394](https://metasmoke.erwaysoftware.com/post/84394)
    * Removed duplicate domain record [13912](https://metasmoke.erwaysoftware.com/domains/13912)
  * (`www.`) `stressfreebrains.com` was extracted twice in samples [87254](https://metasmoke.erwaysoftware.com/post/87254) and [87237](https://metasmoke.erwaysoftware.com/post/87237)
    * Removed duplicate domain record [14413](https://metasmoke.erwaysoftware.com/domains/14413)
  * (`www.`) `supplementschoice.com` was extracted twice in sample [87226](https://metasmoke.erwaysoftware.com/post/87226)
    * Removed duplicate domain record [14410](https://metasmoke.erwaysoftware.com/domains/14410)
  * The same domain was also extracted multiple times in 4 other samples.
    * Removed duplicate domain record [14407](https://metasmoke.erwaysoftware.com/domains/14407)
  * `tradingbotpro.com` was extracted twice in sample [89796](https://metasmoke.erwaysoftware.com/post/89796)
    * Removed duplicate domain record [14892](https://metasmoke.erwaysoftware.com/domains/14892)
  * `try-nitricstorm.com` was extracted twice in samples [86973](https://metasmoke.erwaysoftware.com/post/86973) and [86936](https://metasmoke.erwaysoftware.com/post/86936)
    * Removed duplicate domain record [14340](https://metasmoke.erwaysoftware.com/domains/14340)
  * `tryapext.com` was extracted twice in sample [70784](https://metasmoke.erwaysoftware.com/post/70784)
    * Removed duplicate domain record [11470](https://metasmoke.erwaysoftware.com/domains/11470)
  * `ultraguide.net` was extracted twice in sample [105330](https://metasmoke.erwaysoftware.com/post/105330)
    * Removed duplicate domain record [18452](https://metasmoke.erwaysoftware.com/domains/18452)
  * (`www.`) `usahealthguide.com` was extracted twice in sample [87280](https://metasmoke.erwaysoftware.com/post/87280)
    * Removed duplicate domain record [14422](https://metasmoke.erwaysoftware.com/domains/14422)
  * `usahealthmarket.info` was extracted twice in sample [101343](https://metasmoke.erwaysoftware.com/post/101343)
    * Removed duplicate domain record [17559](https://metasmoke.erwaysoftware.com/domains/17559)
  * (`www.`) `weightloss-spot.com` was extracted twice in 4 samples
    * Removed duplicate domain record [14411](https://metasmoke.erwaysoftware.com/domains/14411)
  * `www.ingic.uk` was extracted twice in sample [87496](https://metasmoke.erwaysoftware.com/post/87496)
    * Removed duplicate domain record [14467](https://metasmoke.erwaysoftware.com/domains/14467) *(done by Art)*
  * `www.pdftodo.com` was extracted twice in sample [90060](https://metasmoke.erwaysoftware.com/post/90060)
    * Removed duplicate domain record [14937](https://metasmoke.erwaysoftware.com/domains/14937) _(done)_
  * `www.studentstutorial.com` was extracted twice in sample [87110](https://metasmoke.erwaysoftware.com/post/87110)
    * Removed duplicate domain record [14374](https://metasmoke.erwaysoftware.com/domains/14374) _(done)_
  * `www.techquery.org` was extracted twice in sample [87470](https://metasmoke.erwaysoftware.com/post/87470)
    * Removed duplicate domain record [14455](https://metasmoke.erwaysoftware.com/domains/14455) _(done)_
  * `www.vitatalalay.com` was extracted twice in sample [91271](https://metasmoke.erwaysoftware.com/post/91271)
    * Removed duplicate domain record [15420](https://metasmoke.erwaysoftware.com/domains/15420) _(done)_

**Comment by Undo1** [comment]
Manual console magic should be done - see edits to above comment.
