### ISSUE TITLE
In the post partial, display whether a post has any comments

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#406]
When you're using MS search to try and figure out whether a post is part of a pattern of posts by a single spammer, or simply a random unaffiliated user, it would be really helpful to have a look at any comments attached to past posts.

It would be easier to find relevant posts if a comment symbol was added to the post partial view (the one that appears on /search, /posts, site dashboard etc) to indicate which posts do and don't have comments. 

I'm not sure how computationally expensive this would be, but it would be a really useful tool to have in the future.

**Comment by j-f1** [comment]
There’s a `comments` glyphicon which would work well here.
