### ISSUE TITLE
Domain search capped at 100 results

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#408]
https://metasmoke.erwaysoftware.com/domains?utf8=%E2%9C%93&filter=supplement&commit=Search only displays 100 results, even though there are more hits. I saw the same with the search term "health".

https://metasmoke.erwaysoftware.com/data/sql/queries/41-domain-name-substring-search?keyword=supplement currently produces 306 results

https://metasmoke.erwaysoftware.com/data/sql/queries/41-domain-name-substring-search?keyword=health currently produces 495 rows

**Comment by ArtOfCode-** [comment]
[status-technically-by-design-but-blame-art-for-forgetting-things]

**Comment by ArtOfCode-** [comment]
Pagination incoming

**Comment by tripleee** [comment]
I still see this manifest in search results, can we get a "built but not deployed" status distinct from "really actually fixed in production" maybe?

**Comment by j-f1** [comment]
You can check [this page](https://metasmoke.erwaysoftware.com/status/code) to see how far behind MS is.

**Comment by tripleee** [comment]
Deployed now, thanks!
