### ISSUE TITLE
Blazer: p_domain_tags_posts is empty

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#409]
This used to work just fine but now it comes up with no results at all, did a mapping somewhere get lost or misspelled perhaps?

`SELECT * FROM p_domain_tags_posts LIMIT 10`
0 rows

**Comment by ArtOfCode-** [comment]
"used to work fine" - I think you're getting tables confused.

 - `p_spam_domains` contains domain records
 - `p_posts` contains posts
 - `p_domain_tags` contains tag records

That much is fairly obvious. There are two more tables that make the HABTM associations between DomainTag <-> SpamDomain and DomainTag <-> Post work:

 - `p_domain_tags_spam_domains` links tags to domains; if you're looking for what tags are on a _domain_ you need to be querying this one
 - `p_domain_tags_posts` links tags to posts; you should query this one if you're looking for tags on a _post_

The latter was only added yesterday when post tags became a thing.

**Comment by tripleee** [comment]
The query I posted literally returns zero rows. It looks like the table is empty (but then more things would break, so I'm guessing there's something in the Blazer configuration).

**Comment by ArtOfCode-** [comment]
What are you trying to query for? AFAICT, no posts have tags yet, so that table _shouldn't_ have any rows.

**Comment by tripleee** [comment]
Sorry, you're right; I was confused.

**Comment by tripleee** [comment]
FWIW this is the query I pieced together ultimately. https://metasmoke.erwaysoftware.com/data/sql/queries/43-drugs-spammer-hours
