### ISSUE TITLE
Abuse: Hosting arrangement category

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#415]
The abuse tracking system (which is amazing btw!) currently has categories for reporting individual posts, and individual domains. However, I have so far mainly been attempting to report broader hosting arrangements, where our archive of spam posts is substantial evidence to establish a snowshoe hosting pattern. Could we have a category for this sort of report as well?  Not sure how it should work, but this is exactly where I think our recent Metasmoke developments are really finally paying off by allowing us to collect compelling and comprehensive evidence about abuse which is otherwise hard to handle systematically.

**Comment by ArtOfCode-** [comment]
In these cases, is there (are there) specific record(s) that you'd want to associate the report with instead of a post/domain? Or would it be better to leave the report with no associated record and you can just mention what it's about in the text?

**Comment by tripleee** [comment]
Typically so far, the report has involved a number of related domains. As a cheapskates solution, maybe add a (hidden?) tag to those domains to collect them and link them to the report?

**Comment by tripleee** [comment]
Or posts, for that matter. If we wanted to report the voodoo doctor to WhatsApp, all the related posts  (which typically don't have a domain name, or if there is one, it's Gmail or Hotmail or something like that) would be useful to collect as evidence.  Ideally, these posts should be tagged with #voodoo-doctor (I think I called it) but perhaps the report only concerns a subset of those with that specific tag, and/or some which are not tagged.

**Comment by ArtOfCode-** [comment]
Given that you'll need to collect a list of the posts or domains that you're reporting in metasmoke in any case (i.e. whether they're tagged or not), does it work if I just make tags reportable? Just means you collect your list of things by adding them to a tag.

**Comment by ArtOfCode-** [comment]
^ Since I'm not going to have much time for MS work in the next few days, that's what I've done for now.

**Comment by tripleee** [comment]
Sounds very good actually, thanks!
