### ISSUE TITLE
Abuse: Make contact card editable

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#416]
I created a contact for wordpress.com but I would like to add some more details about them.

https://metasmoke.erwaysoftware.com/abuse/contacts/3

The card should probably mention that this is for blogs hosted on the domain Wordpress.com rather than Wordpress blogs generally.

**Comment by ArtOfCode-** [comment]
Bah, missed a link. You can edit at https://metasmoke.erwaysoftware.com/abuse/contacts/3/edit - I just need to link to that somewhere.
