### ISSUE TITLE
Back button broken in sql data explorer

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/metasmoke#424]
Steps:
1. Go to https://metasmoke.erwaysoftware.com/ (or any other page of metasmoke that has the menu bar active)
2. Press tools in the menu bar
3. Press "SQL data explorer"
4. Press the back button in your browser

Expected:
It shows page you were previously on

Actual:
It keeps showing the SQL Data explorer, breaking expected user behaviour

**Comment by ArtOfCode-** [comment]
[status-declined] because this is down to Blazer not our logic, but I'll bet you it's because you've got some sort of privacy extension on that nukes the Referer header.
