### ISSUE TITLE
Stop creating comments for "K" or "why"

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#425]
Currently, when your reply to a report with something that isn't tp/fp/k or something simple like that, it creates a MS comment. Also, we should clean the existing ones out of the database.

**Comment by thesecretmaster** [comment]
https://metasmoke.erwaysoftware.com/post/119402

**Comment by quartata** [comment]
almost certain that was caused by replying before commands were registered during startup. if you could find when it happened that'd be great

**Comment by thesecretmaster** [comment]
Regardless, would you object to removing/not creating any comment that starts with (case insensitive) "fp", "tp", "why", "naa" etc.

**Comment by NobodyNada** [comment]
@thesecretmaster AFAIK it’s a feature, not a bug — I can send “k <more details about why it’s spam>” to have those details recorded in Metasmoke.

**Comment by thesecretmaster** [comment]
Alright. I have an idea, expect a PR later today.
