### ISSUE TITLE
Error message on search

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/metasmoke#43]
First, I admit that regular expressions and I don't get along. 

My goal is to find a post that has the following in the body:

    http://Xtreme*Testrone/

I used the following string and checked the "regex" box for body:

    *http://Xtreme*Testrone/*

My search URL ends up being this: 

    https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=*http%3A%2F%2FXtreme*Testrone%2F*&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search

As an aside, I realize this is an invalid domain (no TLD)
 

---

The error message this generates:

```
Mysql2::Error: Got error 'repetition-operator operand invalid' from regexp: SELECT `posts`.* FROM `posts` WHERE (IFNULL(posts.username, '') LIKE '%%' AND IFNULL(title, '') LIKE '%%' AND IFNULL(body, '') REGEXP '*http://Xtreme*Testrone/*' AND IFNULL(why, '') LIKE '%%') AND (ifnull(user_reputation, 0) >= 0) ORDER BY `posts`.`created_at` DESC LIMIT 100 OFFSET 0
```

**Comment by ArtOfCode-** [comment]
Your regex doesn't do what you think it does. Try `https?://xtreme.*testrone/`.
