### ISSUE TITLE
Abuse: Link MS record to abuse report

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#431]
When you submit an abuse report, it would be nice if it turned up as an icon on the domain record and/or the archived spam record in MS so you can see the link between the two.

Not sure what exactly would be a good design; I'm thinking maybe the "create abuse report" could also be dimmed, and perhaps a sequence of links could appear next to it.

(Tangentially, WELZ was complaining about its placement, I guess on the archived spam record; maybe it could be moved up to the top near the provide feedback on post links?)

**Comment by tripleee** [comment]
Oh, and the domain name page should probably show when individual posts in the listing have abuse reports, perhaps somewhat like it shows a speech bubble on the ones which have a comment.

**Comment by tripleee** [comment]
... Could there be two different symbols, one for "has an abuse report for *this* domain name" and another for "has an abuse report for some other record"?

**Comment by thesecretmaster** [comment]
You want a list of relevant domain tags on the domain page (e.g. [here](https://metasmoke.erwaysoftware.com/domains/1875)) and on the domain tags page (e.g. [here](https://metasmoke.erwaysoftware.com/domains/tags/5))? Anywhere else? On the indexes?

**Comment by tripleee** [comment]
Individual domain page I think would be sufficient. When a post has one or more abuse reports, that should be visible on the post's page in Metasmoke. If there is a convenient icon to put in line listings, that would be neat, too, but I guess that's harder to cram in as well as less important.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thesecretmaster** [comment]
@tripleee status-completed?
