### ISSUE TITLE
Blazer: Once you get in, you can't get out (wishlist)

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#432]
This is minor/cosmetic, but there is no easy way to get back to the main Metasmoke site once you click your way into Blazer.  Could the home page perhaps have a link back to Metasmoke main, or even the menu we have on all other pages?

**Comment by ArtOfCode-** [comment]
[status-declined]: We have no control over Blazer views. We only have its config, and that doesn't give us any option for this.
