### ISSUE TITLE
"Routing Error: Not Found" when trying to access review page when logged out

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/metasmoke#434]
URL: https://metasmoke.erwaysoftware.com/review/posts

    Rails.root: /var/railsapps/metasmoke/releases/20180517172121

**Comment by tripleee** [comment]
Why is this a problem? You should not be able to review when you are not logged in.

**Comment by gparyani** [comment]
@tripleee It should be redirecting to the login page, or showing a friendly error, not a vague server error.
