### ISSUE TITLE
No Method Error - Invalidated Feedback

### ISSUE THREAD

**Issue by SulphurDioxide** [Charcoal-SE/metasmoke#441]
When visiting the [invalidated feedback page](https://metasmoke.erwaysoftware.com/admin/invalidated) with a `?page` parameter, like the one added by the pagination buttons at the bottom, I get the following error message:
> NoMethodError in Admin#recently_invalidated

[This link](https://metasmoke.erwaysoftware.com/admin/invalidated?page=2) should present the error in question. You should also be able to trigger this error when clicking on any of the pagination links at the bottom of the [invalidated feedback page](https://metasmoke.erwaysoftware.com/admin/invalidated).

**Comment by thesecretmaster** [comment]
@Undo1 Possible that this is related to Yvette's deleted account? This is caused by the feedback still having a user_id, but that user_id not matching an actual user since Yvette is gone.

**Comment by Undo1** [comment]
@thesecretmaster Could we change it to `f.user&.name` to handle null users?

**Comment by j-f1** [comment]
@Undo1 `f.user_name` could be present even if `f.user` is `nil`.

**Comment by thesecretmaster** [comment]
@j-f1 As it is, in this case. But I think we wanted to fully remove Yvette from our system (GRPR?), so maybe in the future feedbacks should be anonymized.

**Comment by thesecretmaster** [comment]
Yeah. I don't know if there's an actual anonymization process that exists, but if there is, it shouldn't fully nuke the user, just remove email+password+refrences to name scattered around, like feedback user_name and leave the user record, to avoid breaking stuff like this.

**Comment by ArtOfCode-** [comment]
Anonymisation policy is "either you give us the info we need or you don't have an account"; see /privacy on metasmoke.

**Comment by thesecretmaster** [comment]
@ArtOfCode- But "you don't have an account... but we store your name" is an edge case which exists here.

**Comment by ArtOfCode-** [comment]
@thesecretmaster Because chat exists, and not all chat users have metasmoke accounts.

**Comment by thesecretmaster** [comment]
Ok. Well, anyways, things to do to solve the problem. @Undo1 Can you confirm that on the prod DB, there are feedbacks with user_name and a user_id that pointed to a non-existant user? If so, can you set user_id to null?

**Comment by thesecretmaster** [comment]
Fix deployed. @Undo1 could still do some majik fixing in the database, but the issue is resolved.
