### ISSUE TITLE
Repair broken "Blacklisted for" links in Metasmoke

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#443]
The "why" link in this recent post points to `.../uid/Stackoverflow/None` 

https://metasmoke.erwaysoftware.com/post/120621

where apparently it should in fact point to

https://metasmoke.erwaysoftware.com/post/116462

The underlying root cause was a bug in SmokeDetector, but there is a number of records which need to be repaired in Metasmoke as a consequence.

**Comment by tripleee** [comment]
This one too: https://metasmoke.erwaysoftware.com/post/120846

**Comment by tripleee** [comment]
This one too: https://metasmoke.erwaysoftware.com/post/120848

**Comment by tripleee** [comment]
(Sorry for the noise, I was in the wrong window.)

**Comment by tripleee** [comment]
In fact this seems to hold for all the recent "blacklisted user" hits.

https://chat.stackexchange.com/search?q=Blacklisted+user&room=11540

**Comment by tripleee** [comment]
Fixed in https://github.com/Charcoal-SE/SmokeDetector/pull/2194

**Comment by tripleee** [comment]
Actually reopen in order to have the broken links fixed in Metasmoke.

**Comment by tripleee** [comment]
https://metasmoke.erwaysoftware.com/data/sql/queries/83-none-in-why returns 53 apparently broken records.

**Comment by tripleee** [comment]
**This is incomplete.** I'll continue tomorrow if nobody else picks up where I left off.

* [120328](https://metasmoke.erwaysoftware.com/post/120328) should link to [120187](https://metasmoke.erwaysoftware.com/post/120187)
* [120362](https://metasmoke.erwaysoftware.com/post/120362) should link to [120360](https://metasmoke.erwaysoftware.com/post/120360)
* [120452](https://metasmoke.erwaysoftware.com/post/120452] should link to [118781](https://metasmoke.erwaysoftware.com/post/118781)
* [120464](https://metasmoke.erwaysoftware.com/post/120464) should link to [120463](https://metasmoke.erwaysoftware.com/post/120463)
* [120477](https://metasmoke.erwaysoftware.com/post/120477) should link to [118844](https://metasmoke.erwaysoftware.com/post/118844)
* [120478](https://metasmoke.erwaysoftware.com/post/120478) should also link to [118844](https://metasmoke.erwaysoftware.com/post/118844)
* [120489](https://metasmoke.erwaysoftware.com/post/120489) should link to [119606](https://metasmoke.erwaysoftware.com/post/119606)
* [120508](https://metasmoke.erwaysoftware.com/post/120508) should link to [118984](https://metasmoke.erwaysoftware.com/post/118984)
* [120511](https://metasmoke.erwaysoftware.com/post/120511) should link to [120499](https://metasmoke.erwaysoftware.com/post/120499)
* [120513](https://metasmoke.erwaysoftware.com/post/120513) should link to [120492](https://metasmoke.erwaysoftware.com/post/120492)
* [120533](https://metasmoke.erwaysoftware.com/post/120533) should link to [120530](https://metasmoke.erwaysoftware.com/post/120530)
* [120543](https://metasmoke.erwaysoftware.com/post/120543) should link to [120542](https://metasmoke.erwaysoftware.com/post/120542)
* [120589](https://metasmoke.erwaysoftware.com/post/120589) should link to [120509](https://metasmoke.erwaysoftware.com/post/120509)
* [120594](https://metasmoke.erwaysoftware.com/post/120594) should link to [120593](https://metasmoke.erwaysoftware.com/post/120593)
* [120621](https://metasmoke.erwaysoftware.com/post/120621) should link to [116462](https://metasmoke.erwaysoftware.com/post/116462)
* [120650](https://metasmoke.erwaysoftware.com/post/120650) should link to [120603](https://metasmoke.erwaysoftware.com/post/120603)

**Comment by Undo1** [comment]
Did the first bit, plan to do the second bit later.

**Comment by ArtOfCode-** [comment]
@Undo1 poke?

**Comment by Undo1** [comment]
I guess that now counts as 'later' :)
