### ISSUE TITLE
Feature request: Manually add a domain

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#444]
There are some scenarios where it would be beneficial to add a domain name to the database without having it linked from a spam sample.
* Sometimes, Metasmoke fails to extract a spam domain link. The [recent jjbu / jjcu / etc samples identified by Makyen](https://chat.stackexchange.com/transcript/message/44763562#44763562) are a prime example. This also happens e.g. with email address links, which are not extracted by Metasmoke.
* Some domains are _related_ to spam domains and should have searchable whois, abuse reports, and other associated metadata.
Could we please have a way to manually add a domain name to the spam domains?

Tangentially, being able to manually link a sample to a domain would also be nice.

**Comment by thesecretmaster** [comment]
Where should this be linked from?

**Comment by ArtOfCode-** [comment]
@thesecretmaster If you add them from the post, then link to it from posts; if not, link to it from spam domains index.
