### ISSUE TITLE
Wishlist: API for domain tags

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#446]
The API currently has three methods related to domain tags, but it doesn't really lend itself to navigating *from* a domain to its tag(s).

Could we please have the following? This is in rough order of usefulness for me.

* `/api/v2.0/domains/:id/tags` - fetch tags for a particular domain
* `/api/v2.0/domains/:tag/tagged` - fetch domains which have a particular tag
* `/api/v2.0/domains/tags` - enumerate available tags

I guess a mapping between numeric tag IDs to human-readable labels could be technically doable but of limited usefulness, so I'm thinking the API might as well just use and expose the human labels only (though they might change over time). Having to go via the numeric tag IDs would be robust against renames but complicate the simple actions. (Maybe the API should have a set of well-defined error responses too, though?)

**Comment by tripleee** [comment]
Sorry, I'm blind.

**Comment by thesecretmaster** [comment]
Ehm... for reference.. I meant #466.
