### ISSUE TITLE
Code coverage link is broken. Fix or remove?

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#449]
The "code coverage" link in the readme (at the very end, under "References") is broken. I don't know if anyone uses it, so we could probobly just remove it, if it isn't an easy fix. The link currently points to
https://circleci.com/api/v1/project/Charcoal-SE/metasmoke/latest/artifacts/0/home/ubuntu/metasmoke/coverage/index.html

**Comment by Undo1** [comment]
Should be something that got broken in the API v1 -> v2 migration. Should be fixable.

**Comment by thesecretmaster** [comment]
For refrence, here's JSON for all artifacts: https://circleci.com/api/v1.1/project/github/Charcoal-SE/metasmoke/latest/artifacts

**Comment by thesecretmaster** [comment]
Seems to me like there's no way to link directly anymore. However, we could make it link to a magic route on the CHQ website which does JS magic to redirect you to the real link to code cov.

**Comment by Undo1** [comment]
Yep, looks harder than I thought. I don't think coverage is too important at this stage; closing. Anyone is welcome to attempt to revive it if they'd like.
