### ISSUE TITLE
Problem with Unicode/Emoji

### ISSUE THREAD

**Issue by DavidPostill** [Charcoal-SE/metasmoke#45]
Clicking on MS link https://m.erwaysoftware.com/posts/by-url?url=//physics.stackexchange.com/a/298560 gives a "Routing error".

Error message:

```
p.update(:body => "My name is jeff😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂")
   (0.5ms)  BEGIN
  SQL (1.4ms)  UPDATE `posts` SET `body` = 'My name is jeff😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂', `updated_at` = '2016-12-13 23:23:36' WHERE `posts`.`id` = 48666
   (0.4ms)  ROLLBACK
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '\xF0\x9F\x98\x82\xF0\x9F...' for column 'body' at row 1: UPDATE `posts` SET `body` = 'My name is jeff😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂', `updated_at` = '2016-12-13 23:23:36' WHERE `posts`.`id` = 48666
```

**Comment by ArtOfCode-** [comment]
@Undo1 did the update you did a while ago solve this issue?

**Comment by Undo1** [comment]
Don't know, but I doubt it.

**Comment by ArtOfCode-** [comment]
https://chat.stackexchange.com/transcript/message/36129843#36129843

The MS DB needs poking to update individual columns to a Unicode/Emoji-compatible format, like UTF8MB4.

**Comment by Undo1** [comment]
*Should* be fixed, caused by `last_post_title` on Reasons. Original issue was also fixed at some point.
