### ISSUE TITLE
Some charts on /reasons have 'none' feedbacks

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#451]
![image](https://user-images.githubusercontent.com/4848802/40906673-da9c0bb6-6824-11e8-9814-20ad1e3ee2fd.png)

Many of the charts on the /reasons page have a section labelled 'none'.

I don't remember this being a problem before, so some sort of bug appears to have been introduced. 

Alternatively, if it means that there are several posts which literally have no feedback, could we ignore these posts when constructing the graph?

**Comment by ArtOfCode-** [comment]
I blame you for the "Ambiguous" feedbacks, @Undo1 :P

**Comment by thesecretmaster** [comment]
So, what's the status on this? Review shouldn't be ignoring posts with non-tp/fp/naa feedbacks?

**Comment by ArtOfCode-** [comment]
Feedback type cleanup should have solved the root of this problem; there are still some None sections because there's a bunch in review.
