### ISSUE TITLE
Domain extraction should be case-insensitive

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#455]
For example, https://metasmoke.erwaysoftware.com/post/123222 contains two different extracted domain names, though they only differ in capitalization. 

As an interim fix, the lowercase one should probably be redirected to the mixed-case one, because this variant exists in other posts, too.

More generally, domains should probably be normalized to lower case internally.

**Comment by iBug** [comment]
I've done the case conversion in the PR above. However, merging existing duplicates may require @Undo1 to manually edit the database.
