### ISSUE TITLE
Blazer refuses to graph more than 20 months

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#458]
I tried to create some graphs showing spam per month, but Blazer insists on visualizing the result as a histogram and only showing a maximum of 20 results.

Am I doing something wrong or is there a bug in Blazer?

Example:

https://metasmoke.erwaysoftware.com/data/sql/queries/95-drugs-posts-per-month

**Comment by ArtOfCode-** [comment]
By design, I guess? Blazer is doing this deliberately as a limit, it's not a bug.

**Comment by tripleee** [comment]
https://github.com/ankane/blazer#charts sort of suggests I might want to use `date_trunk('month', created_at) to get a line chart instead; but then Metasmoke tells me

>Mysql2::Error: execute command denied to user 'metasmoke_blazer'@'localhost' for routine 'metasmoke.date_trunc': SELECT date_trunc('month', created_at) as month, count(id) as count FROM p_post

**Comment by tripleee** [comment]
Upstream bug: https://github.com/ankane/blazer/issues/166 (closed), -- OP updated the max value in the code so not really a general solution.

**Comment by tripleee** [comment]
Something like `CAST(date_format(created_at, '%Y.%m') AS DECIMAL(4,3))` at least gets me a chart with all the data. The cast alone doesn't exactly work (this does a scatter plot -- the months get dots between 2017.01 and 2017.12 and then there's a wide gap until 2018.01) but mapping the months to 1/12 ranges in a [hidden column](https://stackoverflow.com/questions/14390007/how-to-hide-columns-mysql) might actually be a viable -- though complex -- workaround?

**Comment by tripleee** [comment]
Why is this norepro? The linked graph ends in February 2017 just like it did when I reported this.

**Comment by ArtOfCode-** [comment]
A thought: I might not have been able to repro because of types. Blazer doesn't allow more than 20 values in the x axis, but that doesn't appear to apply to dates as I've happily graphed more than that - see the Feedbacks by Application query.

Try casting your x values to dates (again, see the same query for an example) and see what happens?

**Comment by ArtOfCode-** [comment]
I'm gonna status-decline this one, I'm afraid. Making this one happen requires changes to Blazer itself - and, while we do have a fork of it, that's for an essential Maria support element without which it wouldn't work. I'd rather not start maintaining additional features in Blazer as well.
