### ISSUE TITLE
Blazer ownership search doesn't work

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#464]
The help guidance in the search field on the upper left suggests you can type in a user name, but doing that doesn't produce anything useful.

In general, ownership seems to be incorrectly implemented or missing a component. You can find your own searches but the "mastermind" column is empty for queries which are not yours, etc.

**Comment by ArtOfCode-** [comment]
Should be fixed with 6f63713f2812138cf42fcef7c938b8f89bb396d5 (pending manual deploy).
