### ISSUE TITLE
Gitignoring Gemfile.lock doesn't work

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#466]
`Gemfile.lock` is in git even though it's in `.gitignore`. That's probably not a good thing?

**Comment by ArtOfCode-** [comment]
Git issue. To gitignore a file you have to create a commit where it's not in the repo, which nobody did. Inconsequential.

**Comment by thesecretmaster** [comment]
Yeah, my though was that we wanted to either remove it from .gitignore or ignore it correctly. I think we shouldn't be ignoring it as per [this section on the Bundler website](https://bundler.io/v1.16/guides/bundler_sharing.html).

**Comment by thesecretmaster** [comment]
Completed by https://github.com/Charcoal-SE/metasmoke/commit/9fcfc396846d6e1057337b1974be92827c8a5ffb
