### ISSUE TITLE
Filtering NAA shows a lot of posts with all TP feedback?

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/metasmoke#469]
[Sample search](https://metasmoke.erwaysoftware.com/search?body=6296561&feedback_filter=naa)

This has been around for some time. **The actual** issue is that all-TP posts are recognized as both TP and NAA in search results, You see a page full of ticks, without a single crap, but still `NAA (2)` on the tabs.

![capture](https://user-images.githubusercontent.com/7273074/42134505-bb332d44-7d6f-11e8-8c09-88b584b609ba.PNG)

BTW, not sure if it's the same issue, the feedback'd post type numbers (TP/FP/NAA) on the front page and search page are different. The former is about 3% larger than the latter, and this ratio is consistent across all three types of feedbacks.

**Comment by angussidney** [comment]
Users with the developer role have the ability to fix this on a case-by-case basis, but by the looks of it there are too many posts to manually fix.

Would @Undo1 be able to help with this issue?

**Comment by ArtOfCode-** [comment]
A migration can solve this automatically. I'll write one up.
