### ISSUE TITLE
Fix CI timeouts

### ISSUE THREAD

**Issue by Undo1** [Charcoal-SE/metasmoke#471]
CI lately [likes to timeout](https://circleci.com/gh/Charcoal-SE/metasmoke/1983) for an unknown reason. My investigation suggests that it's related to a MySQL version change, but I can't articulate why. Just a gut feeling.

**Comment by iBug** [comment]
From what I see, it seems 726e85e4c281641c3cc620cfff3efe9d4b2a3347 is the point where Rails tests start to time out on CircleCI. Interestingly, there's one commit 190c369ac9782173e0154adda7c4329c8373d8d8 [whose CI][1] didn't fail.

  [1]: https://circleci.com/gh/Charcoal-SE/metasmoke/1947
