### ISSUE TITLE
Abuse report: DomainTag option does not work

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#476]
If I select Domain tag in the "what are you reporting" dropdown, I get a Ruby traceback.

```
ActionController::UrlGenerationError in AbuseReportsController#show

No route matches {:action=>"show", :controller=>"domain_tags", :id=>nil}, missing required keys: [:id]

Extracted source (around line #38):

def show
    @reportable_path = {
      'DomainTag' => domain_tag_path(@report.reportable),   <<<<<<<
      'Post' => post_path(@report.reportable),
      'SpamDomain' => spam_domain_path(@report.reportable)
    }[@report.reportable_type]

Rails.root: /var/railsapps/metasmoke/releases/20180729030318
```

**Comment by tripleee** [comment]
A couple of reports I attempted to submit actually created abuse reports which trigger this error as well. These tickets are empty junk and should be closed or perhaps removed completely.

* https://metasmoke.erwaysoftware.com/abuse/reports/68
* https://metasmoke.erwaysoftware.com/abuse/reports/69
* https://metasmoke.erwaysoftware.com/abuse/reports/71

**Comment by ArtOfCode-** [comment]
No repro (see [AR#72](https://metasmoke.erwaysoftware.com/abuse/reports/72)). Run me through how you were trying to create these reports? The error trace would seem to indicate there's no `reportable_id` on the abuse report, i.e. you picked DomainTag as the reportable type, but didn't enter an ID for the tag you wanted to report. Using the "Create Abuse Report" link from the domain tag itself should auto-fill both these parameters for you.

**Comment by ArtOfCode-** [comment]
and CC @Undo1 on removing abuse reports 68, 69, and 71.

**Comment by thesecretmaster** [comment]
@ArtOfCode- Should prolly toss a presence validation on reportable id, so you get an error in a neater place.

**Comment by thesecretmaster** [comment]
@ArtOfCode- These reports do have reportable_id, at least according to the SQL explorer.
68 => DomainTag 129903
69 => DomainTag 129903
71 => DomainTag 129879
However, the records have now been nuked from the DB. All those domain tag IDs are invalid. The question is how the domain tags went away.

**Comment by ArtOfCode-** [comment]
Theory:

 - Click "Create Abuse Report" _from a post_
 - Change reportable_type dropdown to DomainTag
 - Submit

Now you have an abuse report with the post's ID, but trying to reference a DomainTag.

**Comment by thesecretmaster** [comment]
Fix: Validate the relationship `AbuseReport#reportable`

**Comment by tripleee** [comment]
The repro steps are correct, except DomainTag was already preselected in the dropdown. I fiddled around for an option to complain to a given provider (the report I sent covers several posts with Tumblr URLs); perhaps we should have one for that as well?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
