### ISSUE TITLE
Regex in mysql

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#477]
Recently, we (mostly @iBug, thank you) have added support for various regex features into [search_helper.rb](https://github.com/Charcoal-SE/metasmoke/blob/master/app/helpers/search_helper.rb#L30). Are we going to continue doing this? Or do we want to revisit getting actual PCRE support by migrating to maria db or using a mysql plugin (if one exists)?

This was also mentioned in #258 and #351.

**Comment by tripleee** [comment]
My personal opinion is definitely that we should be looking towards migrating to MariaDB instead and get rid of this cruft. For the record, Debian out of the box now gives you MariaDB if you try to install MySQL and some wacky hacks are required to _actually_ install MySQL instead. (Thus the `metasmoke` Docker image also lands on MariaDB currently.)

**Comment by thesecretmaster** [comment]
@Undo1 Did you ever actually do that prod migration to MariaDB that was mentioned at some point? If not, maybe worth a try.

**Comment by Undo1** [comment]
Nope, never did. Did your test instance work well?

**Comment by thesecretmaster** [comment]
@Undo1 It worked, but I took it down after about an hour because I thought you were migrating on prod ([see this conversation](https://chat.stackexchange.com/transcript/message/46065842#46065842))

**Comment by ArtOfCode-** [comment]
Now on MariaDB.
