### ISSUE TITLE
Document MariaDB issues

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#478]
We only have this on an anecdotal level, so it would be really good to have a proper black on white account of why we gave up on MariaDB at a previous point in time, and what would be required in order for us to move back.

Posting a reply in this ticket and marking it as closed would be totally sufficient, I imagine.

This is related to #477 but also a number of related discussions.

**Comment by tripleee** [comment]
Also good old #258

**Comment by Undo1** [comment]
Running on MariaDB now. Report issues separately.
