### ISSUE TITLE
Feature request: Delete empty/default values from form's params before submitting search

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/metasmoke#479]
For example, this URL is excessively long for a simple search, especially when you want to share it in other places.

```
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=long+path+tool&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
```

The shortest necessary URL would be

```
https://metasmoke.erwaysoftware.com/search?body=long+path+tool
```

[Here's a potentially useful SO question](https://stackoverflow.com/q/2417928/5958455) that I don't know how to employ, and a comment that I like very much:

> Can I just say, it's very cool your thinking of your users like that. – [T.J. Crowder](https://stackoverflow.com/users/157247/t-j-crowder) [Mar 10 '10 at 15:14](https://stackoverflow.com/questions/2417928/delete-empty-values-from-forms-params-before-submitting-it#comment2399724_2417928)

**Comment by makyen** [comment]
Related: [How can I get a minimized MS search URL?](https://stackoverflow.com/c/charcoal/questions/429)
