### ISSUE TITLE
'Smokey Down' emails should be sent to the person hosting

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#48]
This was brought up a week or so ago, but I thought I'd make an issue for it so we remember to come back to it:

We should associate MS keys with their owner's emails so that the appropriate person gets emailed when their copy of smokey goes down.

**Comment by ArtOfCode-** [comment]
I stuck this on my todo list this morning... might be able to do it shortly

**Comment by ArtOfCode-** [comment]
Fixed by a136b22b5e327678a0fac9c340728bae820aff2a.

Emails are delivered to the owner of the affected SmokeDetector instance. Every email is CC'd to @Undo1 and me.
