### ISSUE TITLE
When I'm reviewing untagged domains, don't offer me a spam review

### ISSUE THREAD

**Issue by rschrieken** [Charcoal-SE/metasmoke#483]
It looks like MS sometimes offers a spam review while reviewing untagged domains on https://metasmoke.erwaysoftware.com/review/untagged-domains.

https://i.stack.imgur.com/YnpVe.png

I would only expect to get a domain and the option to add tags to those. 

I don't expect to see a spam review. The context switching doesn't improve the workflow. Specially as I was looking for a domain.

If this is intended (because spam has a higher priority?) then maybe use color or other visual indicators that you are supposed to be reviewing in a spam post context, not in a domain name context.

I prefer to stay in the same context in case it matters.

**Comment by ArtOfCode-** [comment]
Not intended, but I haven't been able to work out why this happens. The AJAX requests go to the correct endpoint, it just returns the wrong result type for some reason.

**Comment by ArtOfCode-** [comment]
Haven't seen this happen since I last looked into it a couple months ago, so may well be fixed.
