### ISSUE TITLE
Fix the weird CI query logger eror

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#494]
If anyone wants to have some fun, CircleCI and query_logger really don't get along. Take a look at the fix_ci_attempt_1 branch and corresponding CI runs to see what I mean. It's... interesting. Good luck.

**Comment by thesecretmaster** [comment]
So, weirdly enough, I can repro those mysql not connected errors locally. Still have no idea why, but it seems like it's more of a rails problem than a circle problem.

**Comment by ArtOfCode-** [comment]
Dump your current thoughts here, @thesecretmaster? Let's pool thoughts and theories and see if we can figure it out.

**Comment by thesecretmaster** [comment]
My theory is that the tests are spamming mysql and something something race condition something something AR thread pool. I think it's significant that we get the MySQL errors way more when querylogger is on then when it's off. Also, I think it's super weird that it sometimes dies with no errors, but feel like that's related.

**Comment by thesecretmaster** [comment]
Just tested the same seed a couple times -- it didn't die in the same place. So there goes that hypothesis.

**Comment by thesecretmaster** [comment]
Gonna strip out query logger and replace it with redis logs, which may resolve the issue?

**Comment by thesecretmaster** [comment]
Gonna call this closed, along with the other CI issue.
