### ISSUE TITLE
Simple API that dumps statistics for all reasons

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/metasmoke#496]
Maybe a Data Explorer query can do that, but I want an API that's accessible via a URL that dumps all reasons and their data, including title, weight, total/tp/fp/naa count, in a program-friendly interface (JSON or CSV or whatever program-parse-able).

**Comment by ArtOfCode-** [comment]
Is there a reason that a Data Explorer query's download-as-CSV doesn't work for what you're thinking?

**Comment by iBug** [comment]
@ArtOfCode- It would have been great had it not required logging in (and probably a Core role).

**Comment by iBug** [comment]
Answer:

```
GET https://metasmoke.erwaysoftware.com/api/v2.0/reasons?key=$KEY
```
