### ISSUE TITLE
Cannot view tag

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#498]
E.g. https://metasmoke.erwaysoftware.com/domains/tags/63 gets me a traceback.

The tag number in the URL doesn't seem to matter.

The error message says ```undefined method `extensions' for #<Array:0x00007fbac48451d0> Did you mean? extend``` but I don't see a call to `extensions` in [the code line it highlights](/Charcoal-SE/metasmoke/blob/0ced9b1d7ba9bc00c2f1710555e6e13eb52bba46/app/controllers/domain_tags_controller.rb#L62)

**Comment by tripleee** [comment]
https://metasmoke.erwaysoftware.com/data/sql/queries/46-domains-with-tag?domain_tag_id=202 would be a nice workaround but it times out for me.

**Comment by thesecretmaster** [comment]
/domains/tags is also broken

**Comment by thesecretmaster** [comment]
[status-norepro] on being unable to add tags to existing domains, see [this tag](https://metasmoke.erwaysoftware.com/domains/9746) (I'll leave it there so you can see, then we'll delete it)
