### ISSUE TITLE
Why is a moderators username nil?

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#499]
For some reason Asaf Karagila has a nil username in metasmoke. I couldn't tell you why, I can only tell you it's annoying. We should prolly fix that at its source, by adding a nil validation for usernames, sorting out how it became nil, and by correcting this in the DB.

It also causes Math mods to show up empty on the moderator list: https://charcoal-se.org/pings/mods

**Comment by ArtOfCode-** [comment]
Long since fixed - Asaf's account is old, and was created when we had a problem getting usernames from SE. I've fixed the name manually for now; if we want to add a nil validation later we can, but it's not essential.
