### ISSUE TITLE
503 Service Unavailable Error.

### ISSUE THREAD

**Issue by JonasCz** [Charcoal-SE/metasmoke#5]
https://metasmoke.erwaysoftware.com/ gives me a "503 Service Unavailable" error page. Would be nice if it worked :-)

**Comment by JonasCz** [comment]
OK, it seems to work again now, but it seems this is a recurring issue, so would be good for it to be fixed.

**Comment by Undo1** [comment]
Wait a sec, is it not working for you right now? What's `dig metasmoke.erwaysoftware.com` show?

**Comment by Undo1** [comment]
Oh. Yeah, recurring symptom, this time it was a different issue. Still digging.

**Comment by Undo1** [comment]
I'm going to close this; I threw a bandaid on it (just restarting it every 20 minutes, which is ugly but it works).
