### ISSUE TITLE
Some sites in the autoflagging list shouldn't be there

### ISSUE THREAD

**Issue by GolfingSuccess** [Charcoal-SE/metasmoke#501]
> Originally as part of an e-mail to `smokey[at]charcoal-se[dot]org`.

I tried to explore the list of sites I have selected for autoflagging, and I found 5 sites which don't exist:

**Writers**: Renamed, new name is in the list.
**Personal Productivity**: Closed.
**Cognitive Sciences**: Renamed, new name is in the list.
**Startups**: Closed.
**Technical Communication**: Closed.

At first, I thought I simply hadn't registered to some communities, but, afterwards, I started realizing that the list has errors too. It turns out I, indeed, wasn't registered to one community, CS50 (was probably a bit scared of the edX consent :P).

**Comment by thesecretmaster** [comment]
This should prolly get put in that chronic job that runs and checks moderator status.

**Comment by thesecretmaster** [comment]
I've stopped this from happening in the future, but @Undo1 will need to clean up some of the duplication that exists. For example, we have both a "Programmers" and a "Software Engineering" record when really it was just renamed.

**Comment by ArtOfCode-** [comment]
We actually have a helper for renaming sites and migrating things from the old to the new, but I don't recall whether it removes the site or

**Comment by ArtOfCode-** [comment]
That was me being dumb - feel free to use it in code, I only made that note because I didn't link it up to anything on the UI.

**Comment by Undo1** [comment]
Renamed using the fancy `do_site_rename` thing (kudos @ArtOfCode-, makes this easy):

 - Writers -> Writing
 - Writers Meta -> Writing Meta
 - Cognitive Sciences -> Psychology & Neuroscience
 - Cognitive Sciences Meta -> Psychology & Neuroscience Meta
 - Programmers -> Software Engineering
 - Programmers Meta -> Software Engineering Meta

Any others?

**Comment by thesecretmaster** [comment]
I think you missed Beer and it's meta (beer.stackexchange.com) -> Beer, Wine & Spirits (alcohol.stackexchange.com)

**Comment by GolfingSuccess** [comment]
Wow, you guys have found a few more sites, and this has turned big. :-)
