### ISSUE TITLE
/api/filters route produces InvalidAuthenticityToken error when POST not sent from MS domain

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#502]
The following POST request results in an "InvalidAuthenticityToken" error ([screenshot](https://i.stack.imgur.com/2vK9B.png)) when it's sent from a script running in a page from domains other than https://metasmoke.erwaysoftware.com/ (e.g. https://chat.stackexchange.com or https://stackoverflow.com).

    $.post('https://metasmoke.erwaysoftware.com/api/filters', {fields: ['reasons.id']}).done((result) => console.log('result:', result)).fail((fail) => {console.log('fail:', fail); $(document.documentElement).html(fail.responseText);});

This was [initially encountered](https://chat.stackexchange.com/transcript/11540?m=46535030) when trying to POST to this route from FIRE and passing FIRE's `key` and a valid `token` (the token works fine to submit feedback and flag). This can be tested from a chat page where FIRE runs with the following command:

    $.post('https://metasmoke.erwaysoftware.com/api/filters', {fields: ['announcements.id', 'announcements.text', 'announcements.expiry'], key:fire.api.ms.key, token:fire.userData.metasmokeWriteToken}).done((result) => console.log('result:', result)).fail((fail) => {console.log('fail:', fail); $(document.documentElement).html(fail.responseText);});

**Comment by angussidney** [comment]
[The filters page](https://metasmoke.erwaysoftware.com/api/filters) indicates that:

> it's possible to generate your own filters on the fly

which suggests that you should be able to do it via API request. Possibly some sort of authentication bug?

**Comment by Undo1** [comment]
@ArtOfCode- Any idea what this is about? It's like it completely ignores the `skip_before_action`.

**Comment by ArtOfCode-** [comment]
@Undo1 does your commit not fix it?

**Comment by ArtOfCode-** [comment]
bc49db7d0da690269cfb26fff9bce33f27882d50 (above) appears to fix it... don't know why this didn't work when @Undo1 tried, but calling this fixed - reopen if not.
