### ISSUE TITLE
Adding a tag sometimes produces a traceback

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#503]
As alluded in #498 I get tracebacks a lot of the time with the new tagging interface.  It is erratic in other ways, too.

Typing a substring which doesn't match any existing tag in the tag box like "sno" basically loses the string. Hitting Enter looks like it adds the tag, but then the page refreshes and it's gone.

It seems you have to type the tag, click the down arrow to select it, then *separately* click Add.

I am not sure under what circomstances exactly the traceback happens; I'll add one here when I manage to produce one again. I got a couple earlier today.

**Comment by tripleee** [comment]
Here. Not sure what I did differently this time, either.  I tried to add `blogspam` to [`mytectra.com`](https://metasmoke.erwaysoftware.com/domains/25133)

```
NoMethodError in DomainTagsController#add

undefined method `map' for nil:NilClass

Extracted source (around line #20):
  def add
    @domain = SpamDomain.find params[:domain_id]
    @domain.domain_tags = params[:tag_name].map do |tag_name|  # <---
      DomainTag.find_or_create_by name: tag_name
    end
    @domain.save
```

<img width="1016" alt="screen shot 2018-09-03 at 9 09 40" src="https://user-images.githubusercontent.com/2160915/44970284-9154bd00-af59-11e8-9951-c09a6daed000.png">

**Comment by thesecretmaster** [comment]
It looks like for some reason the tag name didn't make it into the POST request. I can get rid of the backtrace, but that shouldn't have happened in the first place. Currently, the way the form works, a space blue-boxes a tag, and only tags in the blue boxes are submitted. I do have general tagging improvements coming in PR #497.

**Comment by tripleee** [comment]
Thanks, adding a space after the tag helped work around the issue, but it's slightly disruptive.

A typical repro scenario is click in the tag box, start typing a partial tag, select the one I want from the dropdown, Enter.  Now I have to hit space before Enter in order to avoid the backtrace.

**Comment by ArtOfCode-** [comment]
Yes; that should be the default behaviour. If a user doesn't want to submit something, the thing they've been trained to do is to remove it before submitting (i.e. delete the extra text). If it's still there, you can assume they _wanted_ to submit it.

**Comment by thesecretmaster** [comment]
Note: The new tagging interface was rolled back and is now sitting in PR #497

**Comment by ArtOfCode-** [comment]
Status-deferring this unless/until we look at that tagging interface again.
