### ISSUE TITLE
Something goes rogue for unknown reasons

### ISSUE THREAD

**Issue by Undo1** [Charcoal-SE/metasmoke#505]
Eats all the server CPU. Minimal information. Likely related to MariaDB migration. https://chat.stackexchange.com/transcript/message/46580791#46580791 - possibly related to deploys, check_smokey_status job, 11a UTC.

**Comment by tripleee** [comment]
Can we get a status update on where we are with this, what's the current hypothesis?

**Comment by thesecretmaster** [comment]
@Undo1 I think we concluded this was MariaDB? But anyways, with the new 3-server setup, this is no longer an issue AFAIK.
