### ISSUE TITLE
TP posts showing up in FP queries

### ISSUE THREAD

**Issue by CalvT** [Charcoal-SE/metasmoke#507]
It would seem that the `is_fp` column in `p_posts` is not updated when the fp feedback is cleared. It could be the same for naa and tp, but I haven't had time to dig into it properly.

I came across this while looking at the Autoflag FP Dashboard, and I noticed that there is one FP with 7 reasons, and a weight of 692. [This is the post](https://metasmoke.erwaysoftware.com/post/52612). It has no FP feedback visible, but on clicking clear it shows that two users had their feedback cleared or automatically deleted.

Glorfindel has written a query to show the [Top 20 FPs](https://metasmoke.erwaysoftware.com/data/sql/queries/120-top-20-fp-posts-by-weight).

When I came to write this issue, the three posts I had found ([1](https://metasmoke.erwaysoftware.com/post/52612), [2](https://metasmoke.erwaysoftware.com/post/55693), [3](https://metasmoke.erwaysoftware.com/post/134223)) had stopped showing up in queries. However three others are now in their place.

So it could be something else (other than the `is_fp` column not updating).

**Comment by ArtOfCode-** [comment]
CC'ing @thesecretmaster on this, I think you were the last person to poke this code.

**Comment by thesecretmaster** [comment]
Yep, see #469 and #470. I bet we're just missing a call to `#update_feedback_cache` somewhere.
