### ISSUE TITLE
Ways to find posts which were *not* autoflagged

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#51]
The new autoflagging functionality is awesome, but in order to make it even more awesome, we need some way to find the posts which were still not autoflagged, so that we can analyze them and figure out additional heuristics we could put in the system in order to catch similar posts in the future.

I'm vague on what exactly would be useful, and only posting the use case at this point.  I can think of some ways which should hopefully be reasonably straightforward, by order of (my limited perception of) apparent complexity.

 - [x] Similar to the flagged log https://metasmoke.erwaysoftware.com/flagging/logs display a timeline of just the posts which were not flagged
 - [x] Throughout the system, expose the flag weight in places where currently we display a summary (title, site, timestamp, user, feedback icons, etc) -- this overlaps with issue Charcoal-SE/metasmoke#50  to some extent
 - [ ] Expose the flag weight in the search form as a searchable field

**Comment by ArtOfCode-** [comment]
#2 084d6ad296530856cce4c4b7c367c10b5e4d7b06

**Comment by tripleee** [comment]
Point 3 was requested again: http://chat.stackexchange.com/transcript/message/34498185#34498185

**Comment by tripleee** [comment]
Would it make more sense to close this and reopen #53?

**Comment by Undo1** [comment]
No, this one works. It's on my radar, just need to find time to do it.

**Comment by thesecretmaster** [comment]
Unless flag weight became a field in posts, I really think this is too expensive to be possible.

**Comment by tripleee** [comment]
Blazer delivers this and much more. Thanks for providing it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
