### ISSUE TITLE
Regex search is dead...

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/metasmoke#513]
When you click the "regex" checkbox for a field, that field becomes ineffective and just acts as if there's nothing.

I was going to search for username regex `w.ngd.ng`, but MS returned *all* posts (130k+) as result.

**Comment by angussidney** [comment]
I've tried [this](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&username_is_regex=1&username=w.ngd.ng) search as you suggested, but I haven't been able ot reproduce your issue?

**Comment by ArtOfCode-** [comment]
I fixed this a few days back, just didn't close the issue
