### ISSUE TITLE
"Include special" tick box is not sticky

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#519]
Visiting e.g. https://metasmoke.erwaysoftware.com/domains/tags?utf8=%E2%9C%93&include_special=%7B%3Achecked%3D%3Efalse%7D&filter=AS-13335 reveals a page where the "Include special" box is not ticked, even though the search it is displaying used to have it ticked.

**Comment by j-f1** [comment]
Looks like the value in the query is `{:checked=>false}`.

**Comment by tripleee** [comment]
Oh, my bad; that's the URL I ended up with but I should have paid attentien to it. Anyway, this is easy enough to repro; tick the box, click search, observe that the box is now unticked again (and the resulting URL says as much).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
