### ISSUE TITLE
Notes section for posts?

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#52]
Prompted by [these comments](http://chat.stackexchange.com/transcript/message/34388980#34388980) by Glorfindel and unarist:

> SmokeDetector: (Smokey report)
> 
> Glorfindel: ^ the URL points to drivethelife.com, a known spam target, and is an answer for Windows 10 instead of Windows 8.x. 
> 
> unarist: Maybe useful for reviewing if we can attach comment like this ^^ to own feedback on MS?

---

It would be useful if we could attach notes to a MS post. That way, when people come back to have a look at a MS post (e.g. contested by site mods/meta crowd), they can find out why the Charcoal users submitted the feedback they did.

Ideas on how to submit notes:

 - Any logged-in MS user can edit the notes section
 - Any content after the feedback part of a reply is sent to MS (e.g. if you replied to a report with `f (edited out spam link)`, the `(edited out spam link)` part would be sent to MS (possibly with the brackets stripped?))
 - Any content in a non-feedback reply (possibly, but may catch joke comments etc)
 - Subcommand for replies such as `note`?

**Comment by ArtOfCode-** [comment]
I'm gonna design this to operate less like a text area, and more like comments.
