### ISSUE TITLE
Add 'weight' to Search

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#53]
To determine if certain types of spam need another filter to be routinely auto-flagged, it would be nice if the weight (>=, <=) could be added as another parameter to search on. Or just a boolean 'would/would not be autoflagged'. The latter would also be good to have in the search result list.

**Comment by Glorfindel83** [comment]
Was already asked for in issue 51.

**Comment by ArtOfCode-** [comment]
#51
