### ISSUE TITLE
Eligible flag controller error

### ISSUE THREAD

**Issue by sau226** [Charcoal-SE/metasmoke#531]
It appears that the controller handling flag logs is using a template that does not exist as per the screenshot below.

![format error](https://user-images.githubusercontent.com/32805612/48970596-f5fb5180-f048-11e8-963c-1d8bf58db5c1.PNG)

**Comment by ArtOfCode-** [comment]
What are you doing that's returning this error?

**Comment by Undo1** [comment]
@ArtOfCode- 'Eligible Flaggers' on https://metasmoke.erwaysoftware.com/post/145285/flag_logs
