### ISSUE TITLE
Allow adding comments to metasmoke posts from /review/posts

### ISSUE THREAD

**Issue by magisch** [Charcoal-SE/metasmoke#534]
I find myself wanting to comment on posts when reviewing them, e.g explaining subtle diffs between naa/fp feedback or results of investigation when something looks fishy. Yet I have to open the actual MS post in a different tab for that.

Ideally I'd be able to comment on MS posts directly from the review interface.

**Comment by thesecretmaster** [comment]
Got some work done on this, so self-assigning. If anyone else want it, just ping me.

**Comment by thesecretmaster** [comment]
Um... so, I don't know where that work went... so I guess I'll un-assign it.

**Comment by ArtOfCode-** [comment]
79523cec0548f1e51a4ff8bfad0e600bd68bde28
