### ISSUE TITLE
Gemfile: malformed requirement 'blazer', '2.1.0+charcoal'

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#537]
I was trying to run `bundle lock` but it fails on this line in the `Gemfile`.

I believe there are two separate errors here.

1. The version requirement should be something like `'~> 2.1.0+charcoal'`. The same apparent error also exists in the `grape` dependency.
2. More crucially, `bundle` doesn't seem to like the `+charcoal` part of the version number. Should we use `.charcoal` or something instead?

I'm not familiar enough with Ruby in general or `Gemfile` in particular to proceed on my own.  The first error should be trivial but the second requires a proper understanding of what version numbers are acceptable.  I recognize the `+local` convention from Debian but it doesn't seem to be supported in `Gemfile`s.  Or am I using too old a version of `bundle` or something, perhaps?  Examples in the `Gemfile` documentation look like a dot would be an allowed separator here, and brief experiments seem to carry this out (though of course then the version I request cannot be found).

**Comment by ArtOfCode-** [comment]
Kicked

**Comment by ArtOfCode-** [comment]
Aye, it just didn't like the +
