### ISSUE TITLE
Proposal: spam-wave tool

### ISSUE THREAD

**Issue by ArtOfCode-** [Charcoal-SE/metasmoke#541]
I've been thinking on and off recently about spam waves. Every now and then, a site gets hit by a wave of spam, usually for a particular product or by a particular user (the last one was Web Apps, spamming a Google "support number"). Almost invariably, once we're alerted of it, our response is to try to kick the posts over the autoflagging threshold, and then let the system work its magic.

This kicking of posts over the threshold is usually done by manipulating the blacklists or other reasons to catch the posts - and while that's nominally fine, it's usually done with less care for false positives than regular everyday activities, and more of a hack-it-until-it-works attitude.

My thought is that having a dedicated tool for this kind of thing could help us be more efficient around spam waves and put us in a better position to help site moderators and CMs more directly. So, I'm suggesting a tool that allows an admin to define a search for which, for 24 hours, every matching post gets autoflagged.

We had a bit of a [discussion](https://chat.stackexchange.com/transcript/message/48070224#48070224) of this in chat last night. Obviously, this tool comes with suitable safeguards:

 - Allow admins to set the duration for which the wave lasts, with a _maximum_ of 24 hours, but allow it to be renewed when it's almost up. This forces it to be regularly reviewed so that it gets stopped when the spam has stopped. (Optionally, also drop a message in Charcoal HQ when the wave is ~90% done, to alert people that it needs review/renewal).
 - Require the search used to define the wave to have a minimum accuracy and post count. These figures will be lower than required for flag conditions, by the nature of spam waves, but could perhaps be in the 95%/10 ballpark.
 - Potentially, we could allow admins to set a max_flags for the wave, which could be above the regular max_flags. With site mod + CM buy-in (which is easier to get on one site than network-wide), we could 5-flag matching posts to get them destroyed quicker.

This _does_ raise questions of sockpuppetry, which is partially why I want to discuss this here - obviously allowing one person to 4-flag a single post is out of the question, but is defining a search as opposed to picking posts far enough removed that it's okay?

What else does this idea need?

**Comment by ArtOfCode-** [comment]
[status-completed]

**Comment by tripleee** [comment]
https://metasmoke.erwaysoftware.com/spam-waves
