### ISSUE TITLE
2FA Does not work for logins

### ISSUE THREAD

**Issue by teward** [Charcoal-SE/metasmoke#551]
Screenshot of the specific issue here:

![screenshot from 2018-12-26 12-31-26](https://user-images.githubusercontent.com/327952/50452785-38df6c00-090a-11e9-82db-1de8ced20503.png)

Basically, though, `undefined method 'verify_with_drift' for #<ROTP::TOTP:0x000000000739a718>` is the exact error, I can get you full stack trace if you need it.

Note that because I have 2FA enabled I can't login to Metasmoke for any Smokey related things either because of this.

**Comment by j-f1** [comment]
If you have an SE account, you should be able to log in with SE to skip 2FA.

**Comment by teward** [comment]
Except I dont.  Therefore the workaround doesnt work.

This issue was filed at @Undo 's request.

**Comment by thesecretmaster** [comment]
Also, as a FR, what do we think of letting devs disable 2FA for users? Or is that too rare of a use case? cc @Undo1

**Comment by thesecretmaster** [comment]
The `rotp` gem got updated from 3.3.1 to 4.0.2 in febc379b, which appears to be when tests started failing. We really should care about tests more.

**Comment by thesecretmaster** [comment]
Just locked `rotp` to 3.3.1, but we really should update to 4.0.2, so not closing.

**Comment by thesecretmaster** [comment]
@ArtOfCode- (since you wrote this code) Pretty sure this just need to change to `verify(params[:code], drift_before: 15, drift_after: 15)`, but I'm not quite sure.

https://github.com/Charcoal-SE/metasmoke/blob/9b86338533f8eeb9467765d4fc5217ed86113232/app/controllers/custom_sessions_controller.rb#L38

**Comment by teward** [comment]
just as an FYI, the 'hotfix' pushed by @thesecretmaster worked.  I can login again to MS.
