### ISSUE TITLE
Redis, data dumps, and dev environments

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#554]
So, now that I've migrated a whole bunch of stuff to redis, I realized that this will have a serious impact on how we develop metasmoke. Now, in order to have a working dev environment, you'll need redis with [the zhregex module](https://github.com/Charcoal-SE/redis-zhregex) and data populated over. Currently, to populate redis with data from the DB, it takes about a half hour.

First of all, this means I need to update instructions about how to set up a dev env. Where are all the places that those instructions live? Also, on that note, would it be useful to have script to automate dev env setup? Is that what we were trying to do with docker?

Second of all, 30 minutes is an annoyingly long time to have to wait to load redis with data. To speed this up, there are a couple options:

1. Instead of requiring that data be pre-populated, every time we access redis we can check if it's been populated, and if not we can populate the data that we require. The downside is that this could possibly slow stuff down in production, and that search will not work unless things are fully populated.
2. Serve redis dumps in the same way we serve mysql dumps. The downside is that this requires Undo to do some work and redis doesn't exactly integrate neatly with paperclip, which manages our mysql dumps. It also could cause minor issues if the DB dump you're using is slightly out of sync with the redis dump.
3. Make it possible to populate redis is segments. So, if the last post in redis is 1234, and the last post in the DB is 2345, we could have a script which would populate all the missing posts over. The downside is that it could take a significant time to run, and the script would need to change as the redis schema changes, so that would be annoying.

What do we want to do?

**Comment by ArtOfCode-** [comment]
What if we:

 - Keep the old search interface, indefinitely. Re-route it to `/search-old` once we've actually moved, and fast-search can become `/search`.
 - If Redis data isn't populated, redirect fast-search to old-search with a `flash[:warning]` explaining why and the solution. (i.e. don't populate on-demand, but make it obvious when the demands happen and aren't met)
 - _Also_ have a script to populate the delta between two points in time (your 3).

Build instructions, AFAIA, live both in the wiki and in Teams.

**Comment by thesecretmaster** [comment]
@ArtOfCode- Your 1 is status-planned, 2 is possible, but requires a `SELECT id FROM posts` query and comparing the result with an array of ids, which could be expensive, and 3 is... annoying to write and will be annoying to maintain, so I don't like it, but it's doable.

**Comment by Undo1** [comment]
Redis dumps are done, same place as SQL dumps: https://metasmoke.erwaysoftware.com/dumps

**Comment by ArtOfCode-** [comment]
Yup

**Comment by thesecretmaster** [comment]
So the only thing this issue is still for is moving docs from channels to GH wiki. I'll do that now.
