### ISSUE TITLE
What is the search icon in the topbar on the right and could it become a link to /search?

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#558]
Based on my quick look at our navbar code, it looks like it does nothing. I can't see it doing anything. I didn't check the JS files to see if there was anything, but I kinda doubt it. What was it's original purpose?

**Comment by j-f1** [comment]
It’s for filtering the reason list.

**Comment by thesecretmaster** [comment]
@j-f1 At /reasons? Because when I click it, nothing happens.

**Comment by ArtOfCode-** [comment]
Probably [status-broken], _maybe_ unless you're on /reasons. I think it appears for any page under DashboardController, though.

**Comment by thesecretmaster** [comment]
Reopening because this is still an issue -- the search icon works on the /reasons page but 1) it does the opposite of searching, it filters, and 2) it doesn't need to live in the navbar if it only works on /reasons.
