### ISSUE TITLE
Respect backoff on flag requests

### ISSUE THREAD

**Issue by Undo1** [Charcoal-SE/metasmoke#56]
We've had a couple (out of 400+) requests fail because we detect a few flag-worthy posts within a few seconds of eachother. As a low-priority thing, we should probably record the backoff and check it before sending more requests. 

We already have Redis running; we could probably leverage that as an in-memory store.

**Comment by ArtOfCode-** [comment]
dfaedd56d807b7f244c93c187c30aab03bb9f9fb
