### ISSUE TITLE
Please disable "link domains"

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#563]
The partial implementation of #459 causes (cough) careless users to create invalid database entries.

Could it please be disabled until the functionality is ready to be exposed?

**Comment by ArtOfCode-** [comment]
Subtle poke? :)

**Comment by Undo1** [comment]
eh, maybe more of a "I don't really know how this works, maybe someone else does"

**Comment by thesecretmaster** [comment]
I can work on disabling this functionality if that's still a path we want to go down (cc @ArtOfCode- in case things have changed in the last 2 years and we no longer want to do that)

**Comment by makyen** [comment]
@thesecretmaster I don't think we want to disable this functionality. There are some issues with the UI which cause multiple links to be established, but I have some prototype JavaScript changes which basically resolve that problem. I still need to convert the changes to running within MS' code and test. Well, OK, I need to go back and look at it in more detail to see if the hack I used has a better implementation within MS.

IMO, this is functionality that we use, so shouldn't be disabled. I'd close this and open a new issue for resolving the UI issues which cause multiple links to be established. Perhaps better, we could take this as an issue to have MS enforce not creating multiple identical links. In other words, I can resolve the UI issues that result in multiple identical calls, but it would be good to have MS ignore attempts to add an additional link which is identical to one which already exists (e.g. if someone purposefully tries to add the same thing a second time).

**Comment by makyen** [comment]
With the recent changes #935, and making the link-domain and "why" required, I'm going to assume that it is no longer desired to disable this functionality.

It would be good to validate both sides of the link when creating it, but it should be much less of an issue at this point, at least enough to not desire to disable the entire functionality.
