### ISSUE TITLE
Previewing post HTML in the review queue

### ISSUE THREAD

**Issue by fortunate-man** [Charcoal-SE/metasmoke#567]
When going through a large number of reviews on MS, it becomes difficult to see the actual post content due to many links present.

It would be nice if there was a sort of small tab on top of each review in which we could choose whether we want to see a preview of the post, i.e, the rendered html (how it would look like on SE), or the raw html, just like it is shown now.

**Comment by ArtOfCode-** [comment]
Technically an XSS vector... not sure how much of a problem that is. In theory the only way it could be abused is via a rogue Smokey runner or via SE's validation also having a bug in it.

**Comment by thesecretmaster** [comment]
Or we could just collapse links in some neat way

**Comment by Undo1** [comment]
Should be pretty easy to whitelist a few HTML things we want to make renderable. There has to be a simple HTML whitelist gem, we probably already have it.

**Comment by Undo1** [comment]
Yep, already have it. 
https://github.com/Charcoal-SE/metasmoke/blob/master/Gemfile.lock#L315, 
https://github.com/rails/rails-html-sanitizer

**Comment by ArtOfCode-** [comment]
dc168852
