### ISSUE TITLE
revision_count is inaccurate under some conditions

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#574]
MS/SD looks at the revision information from the SE API's `posts/{ids}/revisions` endpoint, but does not filter out the items in the returned data that are a change in the post's state rather than actual edits. Non-edits in the [SE API `revisions` data](https://api.stackexchange.com/docs/types/revision) don't have a `revision_number`.

**Comment by Undo1** [comment]
Relevant code: https://github.com/Charcoal-SE/metasmoke/blob/4f2e42a9608f63c5be81be594e8a1cd115c64686/app/models/concerns/post_concerns/autoflagging.rb#L200
