### ISSUE TITLE
Server Status Dashboard

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#576]
What do y'all think of having a dashboard which (possibly via some AWS APIs) shows CPU/memory usage for both the redis instance and the main instance, and maybe some passenger metadata, along with anything else that might be useful?

The only reason I'm thinking of this is because it'd be kinda handy to have for keeping an eye on redis and the memory leaks which may or may not exist.

**Comment by thesecretmaster** [comment]
This is now out of date after the move to tewards servers.

**Comment by teward** [comment]
> This is now out of date after the move to tewards servers.

Yep.  I am the only one with VMware access for metrics, though, but so far the server seems to be purring along now :)
