### ISSUE TITLE
Add domain count to domain link for posts

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#577]
When looking at a post, at the bottom there is a list of domains which were found in the post. It'd be very useful to be able to see counts of tp/fp posts containing the domain. Not sure how expensive that'd be, since domain stuff isn't in redis yet, but figured it was worth a FR.

**Comment by angussidney** [comment]
I think this is a really good idea - one of the first things I do when reviewing a non-obvious spam post is I click on all the domains to see if they have any past history. This FR would save a lot of time if implemented.

**Comment by ArtOfCode-** [comment]
Expensive-ish, but not undoably so
