### ISSUE TITLE
Paginate user list

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#578]
I was trying to use the user roles+data list earlier, and it took upwards of 5 seconds to load. I have a feeling pagination might be handy there.

**Comment by angussidney** [comment]
Note: previously the user roles list was limited to 100 items (like most lists on MS), but #404 asked for this limit to be expanded, As a result of this, selected pages were changed to have a 1000 item limit (e.g. the [user data/roles](https://github.com/Charcoal-SE/metasmoke/commit/9d742600144c7ec4ba9ea757ed91d7979c5fcb04) page, [My Feedbacks](https://github.com/Charcoal-SE/metasmoke/commit/d5969f47a0b92e8d8508380e60e25c8767b24510) page). 

Currently, we have less than 1000 users (although the IDs go above 1000, there are many deleted users), so no pagination appears on the user list.

Would you like to propose that we modify this limit?

**Comment by ArtOfCode-** [comment]
Agree with moving those back to 100 items. 1000 takes significantly longer to load.

**Comment by Undo1** [comment]
Gonna leave My Feedbacks where it is for now, but pulling User Data/Roles back to 100 (primarily since I've been using it lately and it *is* kinda slow).
