### ISSUE TITLE
Make MS flag gibberish posts as abusive

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#58]
This has been discussed before, but I think it should probably be discussed again if we are going to go public on meta about autoflagging. 

---

As you know, there is no difference between spam and abusive flags for when it comes to getting a post deleted, but only spam flags train SE's SpamRam. 

Right now, since we are only casting a single flag it doesn't matter which flag we use, since the humans which make up the other five flags take the majority and determine whether or not the post is used to train the system. However, if we get approval to cast more than one flag on a post, then smokey will have enough flags to outweigh the humans. Hence, it will beco e important that we are correctly flagging gibberish posts. 

This could possibly be implemented by adding a classification to each reason, spam or offensive. Reasons such as few unique characters in answer, offensive answer detected etc should be marked as offensive while everything else can be marked as spam. If >50% of the reasons of an autoflagging eligible post are offensive, then cast an offensive flag.

**Comment by tripleee** [comment]
A recent case in point is https://metasmoke.erwaysoftware.com/post/53027 which received a score weight of 255 from heuristics which typically trigger on rude/abusive and vandalism.

**Comment by ArtOfCode-** [comment]
Actually... Neither type of flag train the system at all, beyond "block the IP this came from". Ye Olde Spamme Ramme doesn't do ML, nor does it do anything with post content.

**Comment by Undo1** [comment]
The thought is good, but in this case I believe it's too much effort for too little reward:

 - We don't have clean data in metasmoke for rude v. spam to train against
 - We'd then be dealing with two types of flags. Not insurmountable, but it is another level of complexity to maintain.
 - Moderators (should) treat all red flags identically, especially for the kinds of posts we're targeting. 

So I'm closing this. If anyone has any further arguments, I'm definitely happy to hear them.
