### ISSUE TITLE
Enable Style/SymbolArray Cop?

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#581]
All of the violations of that cop can be automatically fixed by rubocop, so why not enable it and follow the style rubocop wants us to?

**Comment by ArtOfCode-** [comment]
Which one is SymbolArray?

**Comment by thesecretmaster** [comment]
`[:foo, :bar, :baz]` => `%i[foo bar baz]`, see https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/SymbolArray

**Comment by ArtOfCode-** [comment]
Oh that. Yeah, no objections.
