### ISSUE TITLE
Easier link to review history

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#591]
Are there any links to review history? If so, can we make them more obvious?

**Comment by ArtOfCode-** [comment]
There are, but they're on /review, which is only linked if you have JS disabled - otherwise, the review link is a dropdown.

**Comment by thesecretmaster** [comment]
In which case, you can't get to /review, right?

**Comment by ArtOfCode-** [comment]
You can navigate there direct, but it's not linked anywhere, no.

**Comment by thesecretmaster** [comment]
I think we should link it from somewhere for easier access/discovery.
