### ISSUE TITLE
Link to on-site post from autoflagged RSS

### ISSUE THREAD

**Issue by Undo1** [Charcoal-SE/metasmoke#594]
https://chat.stackexchange.com/transcript/message/49042166#49042166

**Comment by Undo1** [comment]
Turns out this already exists. https://github.com/Charcoal-SE/metasmoke/blob/master/app/views/rss/deleted.rss.builder#L44

`/rss/v1/deleted.xml?site=35&link_type=onsite`

**Comment by rjrudman** [comment]
The urls provided by `link_type=onsite` are protocol-relative links. This breaks SE chatroom feed functionality - and in general, links in RSS feeds should probably have a specified protocol.

**Comment by Undo1** [comment]
Should all be HTTPS links now, thanks @rjrudman. Had no idea that RSS was picky about protocols in chat.
