### ISSUE TITLE
Reason pages aren't showing the correct number of results

### ISSUE THREAD

**Issue by superplane39** [Charcoal-SE/metasmoke#595]
I just noticed this:

![](https://i.stack.imgur.com/EH4mF.png)

This occurred on the https://metasmoke.erwaysoftware.com/reason/148 page. At the top of the lists of posts caught by that reason. MS is supposed to give you a quick count of how many of these were TPss, FPs, etc. This seems to be locked at 1, though, when there are definitely more than 1 post caught by that reason.

**Comment by ArtOfCode-** [comment]
REDIIIIIIISSSSSS!
