### ISSUE TITLE
Document stabilization attempts

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#596]
I could find no ticket which describes what has been done to attempt to make Metasmoke more stable. Could we please have a ticket (such as, I dunno, this one?) where these tweaks are documented for visibility and followed up on?

I know the regex route in the API has been turned off experimentally and I see a bunch of commits which have "OOM" in the title, but this text should probably be replaced by something written by someone who knows about what was done and why.

**Comment by tripleee** [comment]
Sorry if this is a duplicate; I searched for an existing ticket but I might have missed it, or looked in completely the wrong places.

**Comment by thesecretmaster** [comment]
Gonna close this since I believe MS has been pretty stable recently -- the past instability was introduced by some changes I was making, but it should all be good now.
