### ISSUE TITLE
Add "edited" as a search option

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/metasmoke#597]
MS knows how many times a reported post is edited, right? It's even stored as a column in `posts` so this is probably not hard to implement. It's going to be useful when one wants to look for vandalism instead of any garbage.

**Comment by macinashutosh** [comment]
Hi, can i start working on this one?

**Comment by ArtOfCode-** [comment]
Go for it, @macinashutosh. Beware - the backend implementation for search is a bit of a mess, but I'm happy to help explain if you need it.
