### ISSUE TITLE
Adding a comment redirects to dashboard

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#598]
Title says it all. Clicking the 'add comment' button will redirect you to the dashboard, as opposed to keeping you on the post page.

**Comment by makyen** [comment]
It works for me. I just added a test comment from an MS post page (and then deleted it). Both clicking "Add a comment" and the "Add Comment" button worked fine.

**Comment by fortunate-man** [comment]
The "Add Comment" button seems to be working for me as well.

**Comment by Undo1** [comment]
Browsers?

**Comment by fortunate-man** [comment]
I'm using Firefox on macOS.

**Comment by makyen** [comment]
I've tried it in a few versions of Firefox and Chrome on Win 10. It worked in all of them.

**Comment by angussidney** [comment]
Hmm, weird. 

I am running Firefox (65.0.02 64bit) on Windows 10 (version 1803, build 17134.590). When I clock on the 'Add Comment' button, I am redirected to the dashboard. Navigating back to the post page shows that the comment was successfully added.

 I was not able to reproduce the issue in Chrome on the same machine.

I have tried:
 - disabling all extensions
 - disabling content blocking in Firefox settings
 - using a private browsing window
 - disabling PiHole


The network tab shows the following:

![network tab](https://user-images.githubusercontent.com/4848802/53693656-87dacf00-3d9b-11e9-9650-ab1825c5c1f8.PNG)

I will add more details as I try more things to fix the problem.

**Comment by angussidney** [comment]
Found it.

I had the `network.http.referer.trimmingPolicy` entry in `about:config` set to 2. Resetting the value back to the default (0) resolves the issue.

From the docs:

>  network.http.referer.trimmingPolicy
> 
>  controls how much referrer to send regardless of origin
>  values:
>      0 = (default) send the full URL
>      1 = send the URL without its query string
>      2 = only send the origin

However, I have had this entry set to 2 for quite a while now, and I haven't experienced the problem until today. Has a recent change modified the behaviour of the add comment button, or is the issue just another case of strange internet shenanigans...?

**Comment by ArtOfCode-** [comment]
That redirect is a `redirect_back` with fallback location. It tries to redirect you back where you came from, based on the referer header, but if it can't find a referer it'll just send you to the fallback - in this case, the dashboard.
