### ISSUE TITLE
Please merge Metasmoke accounts 1462 and 1470

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#601]
Looks like double-beep created two accounts which are both linked to the same SE user.

If they can't be merged, please delete 1470, which only has 6 feedbacks.

**Comment by double-beep** [comment]
@tripleee sorry for the confusion, delete the #1470 account please, it is only flagger account while #1462 is also a reviewer. See [this](https://metasmoke.erwaysoftware.com/users?utf8=%E2%9C%93&filter=double-beep).

**Comment by ArtOfCode-** [comment]
1470 gone
