### ISSUE TITLE
Redis Will Explode Soon

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#603]
Redis looks like it's getting close to it's max memory and it isn't expiring enough keys.

Currently, redis has 134238 keys, 14774 of which have an expiry set. That's way too low of a proportion. Somehow, 94902 of the non-expiring keys are "request/*" keys, or per-request keys that almost certainly should be expiring (unless they've been saved). That'd leave us with just about 30k non-expiring keys, a much healthier number (compared to the current 119k). If redis runs out of memory, a script to clear out all those requests would look like this:

```ruby
redis(logger:true).scan_each do |key|
  if redis(logger:true).ttl(key) < 0 && key.start_with?("request/")
    redis.del key
  end
end
```

**Comment by thesecretmaster** [comment]
So, after some further investigation, this is 100% an API bug. All but 284 of the non-expiring "request/*" keys are marked with status "API". The digging shall continue...

**Comment by thesecretmaster** [comment]
But as a quickfix, @Undo1 could you run the following ruby code on prod now?

```ruby
r = redis(logger:true)
r.scan_each.select { |k| r.ttl(k) < 0 && k.start_with?("request/") && r.hget(k.split("/")[0..2].join("/"), "status") == "API" }.each { |k| redis.del k }
```

**Comment by thesecretmaster** [comment]
Ah, also, this is prolly bad. This API logging is pointing at main redis rather than logging redis, which was an oversight on my part. Working on a fix now.

**Comment by thesecretmaster** [comment]
Yeah, this is kinda bad. Not terrible, just kinda bad because all the info is empty (so no PII leaks), but about 46k logs got sent over to main redis instead of logging redis.

**Comment by Undo1** [comment]
Done.

**Comment by thesecretmaster** [comment]
Fixed, see [this chat conversation](https://chat.stackexchange.com/transcript/message/49508821#49508821). TL;DR cleaned out all the non-expiring reqs out of main and logging redis, then made API logs actually go to logging redis which caused everything to have expiries.
