### ISSUE TITLE
Redis Log Websocket does not send request/response headers

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#607]

**Comment by ArtOfCode-** [comment]
Also doesn't appear to send timings on the realtime page: queries appear, but never progress beyond INC with timings unknown.

**Comment by thesecretmaster** [comment]
I think you're seeing 2 separate bugs: API requests don't get timing data because grape doesn't provide it, and requests to /status-update.json don't ever get completed.

**Comment by ArtOfCode-** [comment]
Sounds about right

**Comment by thesecretmaster** [comment]
Requests that are non-API and non-status-update.json will give you timing data.

**Comment by thesecretmaster** [comment]
Fixed with big redis log job unification
