### ISSUE TITLE
Review links should point to review items

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#614]
When review gives you a new item, it should modify the url to point to that specific review item, so if you bookmark it you can see the results of that review task. Low priority, but a nice feature to have.

**Comment by ArtOfCode-** [comment]
[status-declined] as-is, the amount of development that entails is not worth the results we get from it. What we can do instead is add a "permalink to review item" link on the review item that you can copy, and use that instead.

**Comment by Undo1** [comment]
Can we get that URL from JS fairly easily? I'd bet this is a one liner window.location change, but the time investment is in finding that one line.

**Comment by ArtOfCode-** [comment]
@Undo1 you might be able to construct it, but it's not just there waiting for you. Not sure it's as simple as it first appears.

**Comment by makyen** [comment]
There's enough information in the HTML within a review page to determine the appropriate URL for the review.

You could use the following function to push the URL for the review into the history state and set the title:

```
function setHistoryStateAndTitle() {
  const postTitle = document.querySelector('h4').firstChild.textContent.trim();
  const postID = document.querySelector('h4 a').href.replace(/^\D*(\d+)/, '$1');
  const relativeUrl = document.querySelector('.review-submit-link').getAttribute('href').replace(/\?.*/, '');
  const reviewID = relativeUrl.match(/\d+/)[0];
  const title = `Review ${reviewID}: post ID ${postID}: ${postTitle} - metasmoke`;
  document.title = title;
  history.pushState({}, title, relativeUrl);
}
```

After checking, it looks like jQuery is available, so the following would probably be more appropriate:

```
function setHistoryStateAndTitle() {
  const postTitle = $('h4')[0].firstChild.textContent.trim();
  const postID = $('h4 a').attr('href').replace(/^\D*(\d+)/, '$1');
  const relativeUrl = $('.review-submit-link').first().attr('href').replace(/\?.*/, '');
  const reviewID = relativeUrl.match(/\d+/)[0];
  const title = `Review ${reviewID}: post ID ${postID}: ${postTitle} - metasmoke`;
  document.title = title;
  history.pushState({}, title, relativeUrl);
}
```

This should allow a user to use the browser's "back" button to page back through their reviews.

**Comment by ArtOfCode-** [comment]
Un-declining, thanks @makyen. Needs someone to connect that up with the relevant bits in MS.
