### ISSUE TITLE
Have SmokeDetector also report newly filed issues and manual pull requests to CHQ, in addition to automatic ones

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/metasmoke#616]
Recently, change 1a0c60a was made, which was a great change: now, users in Charcoal HQ are notified about new automatic pull requests made by non-privileged users in different chat rooms using the `!!/watch` and `!!/blacklist` commands. This was implemented in response to Charcoal-SE/SmokeDetector#2794.

However, per tripleee's [comment](https://github.com/Charcoal-SE/SmokeDetector/issues/2794#issuecomment-477243461), it would be nice to also have it post a message whenever an issue is filed. I often find myself having to post issues in the chat room to make sure that they receive a response, or if my issue requires more input from other users; currently, only a few users watch the issues section on the SmokeDetector repository.

It would also be nice, for completeness, if SmokeDetector also posted a new message whenever any pull request was filed, whether it be automatic or manual.

**Comment by ArtOfCode-** [comment]
We have enough issues coming in that an issue notifier is on the noisy side rather than the signaly side. PR's often require relatively timely action; issues don't, and email notifications mean that people will get to them whether they're in CHQ or not.

**Comment by gparyani** [comment]
@ArtOfCode- I've disabled email notifications, and I'm sure that at least a few others participating in Charcoal HQ have done so as well. Without that, there is no notification, and I wouldn't mind a duplicate notification in CHQ.

Also, if PRs require timely action, why decline the PR aspect of this request as well?

(Also notifying @tripleee about this issue)

**Comment by ArtOfCode-** [comment]
@gparyani look.

(A) GitHub has its own web notifications.  
(B) You fairly clearly haven't read the commit. That chat message fires on *all* PRs already, not just automated.
(C) I told you this was declined in Tavern some while ago. Opening a(nother, there already was one) GH issue about it was not only pointless, but also *reeks* of trying to circumvent that decline, or apply peer pressure to it, or... whatever the hell it is. As does "helpfully" tagging in other people. That's *not* okay. All it's served to do is waste time.
