### ISSUE TITLE
Flag log for a post should include failures

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#625]
E.g. https://metasmoke.erwaysoftware.com/post/174862/flag_logs shows 3 successes but no failures, whereas https://metasmoke.erwaysoftware.com/flagging/logs?filter=failures reports one failure for this particular post (for Makyen).

**Comment by makyen** [comment]
That was a failure on a manual flag. Manual flags, and their failures, are not normally displayed in the MS flag logs page (there was another issue about that, Flag Logs empty, Issue #561).

I agree that it would be good for the flag logs page to include manual flags and their failures. IIRC, including manual flags on the flag logs page is [on the to-do list](https://github.com/Charcoal-SE/metasmoke/issues/561#issuecomment-453639634).

**Comment by thesecretmaster** [comment]
I have code locally to fix this (just removing a `where(is_auto: true)`), but since this exposes additional flagging information, I'd like @Undo1 to sign off first.

**Comment by ArtOfCode-** [comment]
@thesecretmaster Undo's sign-off can be implied from his thumbs-up up there ^. You can have my sign off too - just make sure it's clear which flags are manual vs. auto and successful vs. failed.
