### ISSUE TITLE
Messages are no longer posted in CHQ chat when a PR is filed

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/metasmoke#628]
Something broke with change 1a0c60a, which was supposed to post a message in Charcoal HQ whenever a new PR is filed, a feature I requested at Charcoal-SE/SmokeDetector#2794. As of recently, it's no longer posting such a message; I just tested by filing a non-privileged watch request via Tavern on the Meta and a message wasn't posted in CHQ.

Can this please be fixed?

**Comment by Undo1** [comment]
It got disconnected from the MS websocket... somehow. Not sure yet if this is the usual "that just happens sometimes" thing or something deeper, maybe related to the bizarre Nginx queueing issues from earlier.

'Fixed' by rebooting the active instance; leaving this open for now until it either (a) gets root-caused, or (b) doesn't happen for a while.

**Comment by ArtOfCode-** [comment]
Didn't happen for a while
