### ISSUE TITLE
Admin page: user flagging overview shows 0 "Flags used today"

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#630]
Minor bug: "Flags used today" always reports 0, but that's not the number that's actually been used in that UTC day. The error on that page is regardless of the user, but [here is a link to the page for me](https://metasmoke.erwaysoftware.com/flagging/users/overview?user=71).

**Comment by ArtOfCode-** [comment]
Yeah, that's a misleading field. That's actually displaying a field direct from the database - `flag_conditions.flags_today` (IIRC), which was originally intended to record flag usage and cutoff when the user-set max was reached. We never ended up actually hooking that field up, though, so it's _always_ zero - but it was put in a bunch of dashboards and never removed. This is one of them.
