### ISSUE TITLE
Why do some flag logs have no users?

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#633]
I was investigating the recent reports of weird flag log errors and I noticed that some flag logs have no user attached -- specifically, all the ones that had this error (but also some other logs). What conditions cause a flag log not to have a user attached?

**Comment by ArtOfCode-** [comment]
If a flag attempt fails before user selection, there won't be a user on it. Specifically, it happens [here](https://github.com/Charcoal-SE/metasmoke/blob/a9b0bf343fcba950fcb4d8b222e91dc78eef7ba3/app/models/concerns/post_concerns/autoflagging.rb#L96) - the general catch-all-errors block. If a user has been selected and the `send_autoflag` call issued, then any errors at that point will be more likely to create an error log _with_ the user - unless the task throws an exception, in which case it bubbles back to this block and doesn't have one.
