### ISSUE TITLE
Autoflagging posts by deleted users fails

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#636]
Currently, if the author of the post has been deleted, then autoflagging fails ([example](https://metasmoke.erwaysoftware.com/post/185801/flag_logs)). It fails because the reputation of the user can not be determined. Specifically:

```
undefined method `reputation' for nil:NilClass: undefined method `reputation' for nil:NilClass | /var/railsapps/metasmoke/releases/20190706205517/app/models/flag_condition.rb:70:in `validate!'
/var/railsapps/metasmoke/releases/20190706205517/app/models/concerns/post_concerns/autoflagging.rb:23:in `block in autoflag'
/var/railsapps/metasmoke/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/relation/delegation.rb:71:in `each'
/var/railsapps/metasmoke/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/relation/delegation.rb:71:in `each'
/var/railsapps/metasmoke/releases/20190706205517/app/models/concerns/post_concerns/autoflagging.rb:22:in `autoflag'
/var/railsapps/metasmoke/releases/20190706205517/app/controllers/posts_controller.rb:159:in `block (2 levels) in create'
```

Given that this fails due to an error, it's not clear to me if there is an intention not to raise autoflags in such cases. Obviously, some of the checks that are performed (e.g. reputation) can't be done on deleted users, but when the user is deleted, I'm unsure if we should care about those checks (or at least that one).

**Comment by ArtOfCode-** [comment]
Hm. Two issues here. The error message getting dumped into a flag log in raw form is a bug, and shouldn't be happening - if we _want_ to break off autoflagging if we can't get reputation, that should be handled more gracefully. Separately but relatedly, do we _want_ to break off flagging if the user is deleted? My instinct says yes, because it's an integral part of flag conditions, but I could be persuaded otherwise.

**Comment by Undo1** [comment]
Looks like this has happened 295 times; several times each week (often multiple per day).

@ArtOfCode- My default position on this from reading the excerpt on my phone was to say we should let flagging go through on deleted users (treat them as rep=0). Need to pull data on how that would work out.

**Comment by Undo1** [comment]
List of applicable posts: https://gist.github.com/Undo1/0ed23c0bcbe436e7fd571668ed17f36e (just looking for FlagLogs `LIKE '%undefined method `re%'`)

**Comment by makyen** [comment]
I'm unsure as to if we should apply autoflagging to posts by delete users. If the user is deleted, maybe we should fallback to checking how old the post is. If it's older than X (maybe a couple/few years?), then we don't autoflag? Obviously, we should back any decision as to how to handle them up based on the actual data we have.

Given that we have a list of affected posts, we could look at how many of those ended up with TP vs FP feedback, and if any FP corresponded with other criteria.

**Comment by makyen** [comment]
It looks like we get this error regardless of whether the post would qualify to be autoflagged, or not. For example, we got [this error](https://metasmoke.erwaysoftware.com/post/185847/flag_logs) on [this post](https://metasmoke.erwaysoftware.com/post/185847) today, which definitely would not have qualified for autoflagging. Thus, if we're going to look at any statistics wrt. FP/TP on posts by a deleted user that would be autoflagged, then we will need to make a determination as to which of the ones that got this error would have actually been autoflagged.

**Comment by angussidney** [comment]
In the past, I've generally found that when a post by a deleted user is posted, it's often very old, and thus the standard procedure (i.e. autoflagging the post) is not the right way to proceed (at least without a human discussion first). 

I would be interested to know what the stats say about this issue. But don't forget: with autoflagging, we want to optimise for zero false positives, not zero false negatives. Unless if there is a clear trend in the data, I think that disabling autoflagging for deleted users would be the safest option.

**Comment by thesecretmaster** [comment]
If this is still a problem, could someone find a more recent repro of it? The line numbers from the error message don't line up anymore.

**Comment by makyen** [comment]
The actual error is probably resolved, due to [the change in](https://github.com/Charcoal-SE/metasmoke/blob/master/app/models/flag_condition.rb#L70)

    post.stack_exchange_user.reputation <= max_poster_rep &&

to

    post.user_reputation <= max_poster_rep &&


`post.user_reputation` appears to be set to 1 for deleted users, so this is resolved.
