### ISSUE TITLE
Provide a way to always have a link on a post title even if the title is only non-visible/-width  unicode

### ISSUE THREAD

**Issue by rschrieken** [Charcoal-SE/metasmoke#638]
Case in point:

https://metasmoke.erwaysoftware.com/spammers/138796
(4th entry)

related: https://meta.stackexchange.com/q/330864/158100

**Comment by RobCoding** [comment]
That user recently earned a [peer pressure](https://meta.stackexchange.com/help/badges/36/peer-pressure?userid=497710) badge on Meta, and a **10 year** suspension network wide.

As to the issue itself there is a [bug report](https://meta.stackexchange.com/questions/330864/questions-with-invisible-titles-can-be-posted-by-using-soft-hyphens) filed on Meta about invisible titles (from a different user) that is only attracting downvotes.

**Comment by rschrieken** [comment]
@RobCoding I know and I have seen the meta issue. I assume SE doesn't get fixed. MS can be fixed, we have the code right here, I only lack the ability to code in ruby :-)

**Comment by thesecretmaster** [comment]
I'm not sure that this would be a good thing -- we'd need to either a) have some way to check if a title is invisible (which IIRC is annoying because unicode) or b) add some icon before every post title, so you could click on that instead (which adds some clutter to every single post title, for little/no benefit).

**Comment by ArtOfCode-** [comment]
@thesecretmaster or you use the post ID as the thing to put before every title - still takes some space, but at least it's useful information. Or you link the timestamp to the post as well, a la SE comments or Twitter.
