### ISSUE TITLE
"Potentially bad IP" should be experimental

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#639]
@Makyen [writes](https://chat.stackexchange.com/transcript/message/51088385#51088385):
> You used the same naming scheme for "potentially bad ip for hostname in {}" as is used for the rest of the "potentially bad" reasons. However, all the others with that naming scheme are "experimental" reasons which are locked to a max weight of 1. I think it would be better if every reason that uses that scheme is "experimental". Maybe it would be better to have this reason either be "experimental" or named something a bit different (e.g. "probably bad ip for hostname in {}").

**Comment by makyen** [comment]
The post which was erroneously autoflagged is: [is anyone else having problems accessing Latexbase.com?](https://metasmoke.erwaysoftware.com/post/188044)

**Comment by Undo1** [comment]
Done.

```
    [0] #<Reason:0x0000000009540688> {
                     "id" => 166,
         "maximum_weight" => 1,
                 "weight" => 1,
            "reason_name" => "Potentially bad ip for hostname in body",
        "last_post_title" => "is anyone else having problems accessing Latexbase.com?",
               "inactive" => false,
            "description" => nil
    },
    [1] #<Reason:0x0000000009540548> {
                     "id" => 168,
         "maximum_weight" => 1,
                 "weight" => 1,
            "reason_name" => "Potentially bad ip for hostname in title",
        "last_post_title" => "is anyone else having problems accessing Latexbase.com?",
               "inactive" => false,
            "description" => nil
    },
    [2] #<Reason:0x0000000009540408> {
                     "id" => 170,
         "maximum_weight" => 1,
                 "weight" => 1,
            "reason_name" => "Potentially bad ip for hostname in answer",
        "last_post_title" => "How to use github.com/jhump/protoreflect to parse a byte array of proto message knowing the message descriptor",
               "inactive" => false,
            "description" => nil
    }
```

**Comment by tripleee** [comment]
Do I understand correctly that new experimental rules need to be hard-coded to have weight 1 by someone who has write access to the Metasmoke database? Or is there some way to do this in code?

**Comment by ArtOfCode-** [comment]
This is one of those things that's been on the radar to be done almost since experimental reasons were born, but nobody's ever got round to putting in a button for it. Still needs to be done manually, at the moment.
