### ISSUE TITLE
Show confirmed/all in domain tag view

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#660]
For example, in [Tag: #AS-50673](https://metasmoke.erwaysoftware.com/domains/tags/510), there is no easy way to decide whether or not this is really a spammy AS or not. It would help if the "Occurrences" column could have some sort of indicator of the number of TP occurrences.

The [domains view](https://metasmoke.erwaysoftware.com/domains?utf8=%E2%9C%93&filter=.nl) already has this feature (Occurrences is subdivided into what looks like TP, FP, other -- though a legend would help) so I imagine this should not be too hard to implement.

**Comment by thesecretmaster** [comment]
Closing, since I believe this is covered in https://github.com/Charcoal-SE/metasmoke/commit/465353ace82d762b7883a86a6a5d5dd01751671e.
