### ISSUE TITLE
Impossible to tag untagged domains in review

### ISSUE THREAD

**Issue by double-beep** [Charcoal-SE/metasmoke#670]
Some time ago, the untagged domains review queue looked like:

> ![image](https://user-images.githubusercontent.com/38133098/63362493-95503980-c37a-11e9-88ba-6af5f14b7a2a.png)

However, now, it looks like it is broken:

![image](https://user-images.githubusercontent.com/38133098/63362623-cfb9d680-c37a-11e9-8b80-562889aa2580.png)

When clicking add, the system adds automatically two `#` tags. Can this be fixed?

The console throws the following error:

    Unhandled promise rejection TypeError: Unable to get property 'firstChild' of undefined or null reference

**Comment by makyen** [comment]
This appears to be an issue in code I added in #658. The issue is that the code I added is running on the untagged domains review page when it was intended only for the posts review page. I'll create a fix.
