### ISSUE TITLE
CircleCI tests have been failing for an extended time

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#677]
The last time the CircleCI tests all passed on a commit without reporting any errors or indicating problems in its output was [this commit](https://github.com/Charcoal-SE/metasmoke/commit/95d013411b629c365c8be98d6978acd1be54cda7) back in the middle of December 2018.<sup>1</sup> It's great that we've had significant, beneficial changes in MS since that time, but the CircleCI tests just haven't kept up.

As a contributor who only does a moderate bit of work on this project (and only dabbles in most of the tech stack), I rely heavily on the CircleCI tests to tell me if something is broken in what I submit to the project, or if there are issues with what other people submit. IMO, it would be of significant benefit for the CircleCI tests to normally be passing when correct code is submitted.

With the CircleCI tests normally not passing, it's a *lot* easier to miss that a commit has changed something which causes a failure. As an example of this, unfortunately, both myself and ArtOfCode missed that my PR #656 had a syntax error which wasn't caught due to the rails-test not running properly. That change was deployed to MS and resulted in the flag settings dashboard being unavailable, until a fix was deployed.

I'd like to see us work towards having the CircleCI tests routinely pass, even if that means tests that are *expected* to fail are just disabled, until new tests for the changed functionality are written. I've endeavored to make the tests pass, but there are some things which really should get input from people who are more in tune with how you want things done on this project.

I've done the following:

1. Submitted PR #627 (merged), which resolved the xo errors reported for the JavaScript test.
2. Pushed [a commit](https://github.com/Charcoal-SE/metasmoke/commit/8ea43f4309c48340d08682305a79102df142af57) on a throw-away branch which caused CircleCI to regenerate the cached configurations for the master branch. The cached configuration, which had been repeatedly restored and re-saved, was corrupted, preventing the rails-test from running. [This commit has done its job. There's no need to keep it around, other than to have a ready-made .circleci/config.yml that could be re-committed to do the same thing again, if it's ever needed. The link here should remain functional, but I'll delete the branch, unless it's desired that the branch be kept (it should not be merged).]
3. Submitted PR #672, which resolves some minor rubocop issues.
4. Submitted PR #673, which resolves the remaining rubocop issues. However, the way I resolved these issues was to implement the minimum changes needed to make rubocop happy, without changing functionality. These changes should be reviewed and someone more familiar with what's desired for the project make a choice as to if they'd like to implement fixes in a different, cleaner manner. This PR left:
    1. [live code which may be doing nothing](https://github.com/Charcoal-SE/metasmoke/pull/673/commits/2ad6a5984d01444e03c1f4ff06c4010330978cdf), along with several lines of code commented out, which might be better just deleted;
    2. [commented-out unreachable code that may be more appropriate to just delete, or adjust so it's functional](https://github.com/Charcoal-SE/metasmoke/pull/673/commits/9e8162ce162d966eb810f7d588048c8856508528);
    3. and [disabled a rubocop rule on one line](https://github.com/Charcoal-SE/metasmoke/pull/673/commits/d1db7c1545eeb4458d1bda610988cfce0c245079) where the code appeared functional. It was easier to disable the check, rather than restructure/test the code so that the same functionality was obtained without running into the rule rubocop was enforcing.
5. Submitted PR #674, which comments out all of the tests in flagging_test.rb. All the tests in that file [were failing](https://circleci.com/gh/Charcoal-SE/metasmoke/3565?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). I believe this is due to the substantial changes which were made to how MS does flagging. The changes to MS flagging are great, but these tests can't pass as is.  
Ideally, there would be new tests, or these adjusted to be functional, but that's a lot more work (and really would benefit from someone other than myself doing them). It's my opinion that, in the interim, it's better to not have the known-failing tests run every time.

Merging all of the above PRs will get the CircleCI tests to all pass,<sup>2</sup> but there are definitely things that could be done "better" compared to how I resolved the issues. I'm not invested in having these exact changes merged, but I would like to see the project move towards having the CircleCI tests routinely pass.

------
1. There have been a few runs which "passed" since then, but for all those, the rails-test indicates issues/problems/failures in its output, even if the the errors are not actually reported as a true "failure".
2. There's still an intermittent issue where the rails-test sees `Mysql2::Error::ConnectionError: MySQL server has gone away`. I haven't investigated the root cause of this problem, but every time I've seen it, it's gone away when the CircleCI build is re-run on the same commit.

**Comment by ArtOfCode-** [comment]
Nice work, thank you. I wonder whether turning on branch protection for this repo would help motivate us to keep tests passing.

**Comment by thesecretmaster** [comment]
Closing since the tests are mostly passing now.
