### ISSUE TITLE
Broken domain link customembroideredpatches.com

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#678]
https://metasmoke.erwaysoftware.com/domains/40223 produces a traceback after I tried to link it to gs-jj.com via the "Link a domain" dialog

**Comment by makyen** [comment]
Fixed with [3895ae7](https://github.com/Charcoal-SE/metasmoke/commit/3895ae777c2a4650493fa0f8503ed58ef59c7634) and [0ac260e](https://github.com/Charcoal-SE/metasmoke/commit/0ac260e1f8c5866c5337e5bd7ecdd4ae1b519f99).
