### ISSUE TITLE
Tagging an untagged domain through review adds 2-3 same tags

### ISSUE THREAD

**Issue by double-beep** [Charcoal-SE/metasmoke#680]
Trying to tag a domain in untagged domains review (e.g. want to tag `#notspam`) shows:

![image](https://user-images.githubusercontent.com/38133098/66714061-5a86e280-edba-11e9-9bbc-feaf3e3b4b30.png)

The domain has one tag, though:

![image](https://user-images.githubusercontent.com/38133098/66714070-7d18fb80-edba-11e9-8968-e1256f4c15d4.png)

**Comment by ArtOfCode-** [comment]
Part of the general JS fustercluck. Reload your page when this starts happening and it usually stops. Otherwise [status-declined] because I've tried to fix JS before and it's never worked.
