### ISSUE TITLE
Allow us to sort domain groups by all columns

### ISSUE THREAD

**Issue by double-beep** [Charcoal-SE/metasmoke#681]
Currently, [domain groups](https://metasmoke.erwaysoftware.com/domains/groups) are sorted by the "Group Name" column. The problem is that we cannot sort the groups by ID and/or Domain count.

Can *we* select the way the domain groups are sorted?

**Comment by ArtOfCode-** [comment]
ad3df5e5d5bc33cdbcf2f953885740d495a42faf
