### ISSUE TITLE
Make the message posted to automatic watch/blacklist pull requests include a link to the metasmoke search

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/metasmoke#684]
On automatic pull requests generated from non-privileged watch or blacklist requests, the user metasmoke comments on the request with the number of TPs, FPs, and NAAs.

It would be nice if this also included a link to the metasmoke search for the keyword in question, so users handling the request can easily see which exact posts were involved, or if there were any more posts after the request was filed.

**Comment by makyen** [comment]
There are normally two comments on each automatically generated `!!/watch` or `!!/blacklist-*` PR. The first comment from SmokeDetector contains links to a search on MS and a search on SE. The second comment contains the results of a search.

The linked searches are not exactly what they should be. In many cases, they are substantially different compared to what the watch or blacklist will detect, but the links are at least there.

Note: To find out what a watch or blacklist-keyword will detect actually requires at least 3 different searches on MS: one each for title, username, and body (more searches may be required for complex regexes, and variable length look-behind is not supported). Only one search is linked. The searches should also reflect the bookending which exists for watches and blacklist-keywords, along with setting the `s` flag.

Were you wanting us to improve those links?

**Comment by gparyani** [comment]
I completely overlooked the links in the SmokeDetector comment. It would be nice to *also* have a link in the metasmoke comment, so that it's much easier to find.

**Comment by user12986714** [comment]
The MS comment is implemented as a GH hook, which won't differentiate between blacklist/watch PRs from other PRs like code modification; it can be more easily implemented on the SD side.

**Comment by ArtOfCode-** [comment]
...except it _does_ differentiate between auto blacklist PRs and others.
