### ISSUE TITLE
Is "data exploder" intentionally misspelled?

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#686]
The Core menu in metasmoke contains the following entries, among others:

* JS Data Exploder
* SQL Data Exploder
* GraphQL Data Exploder

I'm guessing these should properly say "Explorer"...?

**Comment by Undo1** [comment]
It’s intentional, from [way back when](https://chat.stackexchange.com/transcript/message/38220483#38220483). Search CHQ for “exploder” and a lot comes up. 

Exact origin is fuzzy beyond “it liked to break a lot of stuff”. @ArtOfCode- ?

**Comment by ArtOfCode-** [comment]
Precisely that. It was _originally_ a misspelling, then I realised it applied pretty well to the thing that kept breaking, and it's just been the name ever since.
