### ISSUE TITLE
Feature Request: Test page to test strings, like smokey's `!!/test <string>` command.

### ISSUE THREAD

**Issue by Cerbrus** [Charcoal-SE/metasmoke#69]
Smokey has a couple of useful commands that allow you to test strings against smokey's filter.  
The disadvantage of these commands is that you have to dump the _bad_ text into chat.

It'd be very practical if MetaSmoke had a "test" page, where the following commands are available:

    !!/test
    !!/test-a
    !!/test-q
    !!/test-t
    !!/test-u

**Comment by angussidney** [comment]
http://chat.stackexchange.com/transcript/message/34848942#34848942

> @Cerbrus <s>[status-almost-certainly-going-to-be-declined]</s> [status-gonna-be-pretty-hard] - MS has none of the test code required, the only way to do it would be to send a request to smokey to test it then chuck it back up the websocket

**Comment by ArtOfCode-** [comment]
Possible, but I'm not sure it's worth it. This would involve sending a thing down the websocket to Smokey, having Smokey test it, then send it back - all possible, but if it's just to avoid posting spam-like text in a chatroom dedicated to killing spam anyway...

**Comment by Undo1** [comment]
Closing for now; feels like scope creep. Open to debate.
