### ISSUE TITLE
Traceback from GraphQL query

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#691]
I'm only just discovering the language so I'm probably doing something extremely stupid, but I should still not be getting a Rails traceback, right?

Query:
```
{  post { title, domain_tags { name, id } } }
```
Traceback:
```
      # query_params.merge!({max_depth: 8, max_complexity:20})
     end
     @results = MetasmokeSchema.execute(query, **query_params) <<<<
     respond_to do \|format\|
       format.json { render json: @results }
       format.html { @results = JSON.pretty_generate(@results.to_hash) }

Rails.root: /var/railsapps/metasmoke/releases/20191107205100

app/controllers/graphql_controller.rb:18:in `execute'

Request
Parameters:

{"utf8"=>"✓", "authenticity_token"=>"lISOolsaBSF7oJrXkt1JPzfBVdqM3J74BGO3GmMlnaGol+mTUiYYaSu0SV9KxJZao536Ch6pwvG1gGEAuKvwYA==", "query"=>"{  post { title, domain_tags { name, id } } }"}
```

**Comment by tripleee** [comment]
The schema I get for `"Posts"` (from the introspection example which is displayed when you originally open the GraphQL page) suggests that each `post` should have a `domain_tags` member, but I guess that is actually not the case. I can query for `{domain_tags{id,name}}` just fine.

**Comment by ArtOfCode-** [comment]
What's the error message? You've got the trace there, but not the error - that's the red headline on a Rails error page.

**Comment by tripleee** [comment]
NoMethodError in GraphqlController#execute

**Comment by ArtOfCode-** [comment]
That's the header... can you get a screenshot of the error page, so I can grab the bits I need?

**Comment by makyen** [comment]
I was able to duplicate this error from the [GraphQL page](https://metasmoke.erwaysoftware.com/api/graphql) (the link was mentioned in chat, but not in this issue) and entering the query mentioned above:

    {  post { title, domain_tags { name, id } } }

I'm not sure if it's our intent to have that page functional. As far as I know, it's not linked from anywhere. The page for GraphQL that was functional was for the interactive [GraphiQL](https://metasmoke.erwaysoftware.com/api/graphiql) (note the `i`), which now just displays "Loading...". ([the GraphiQL repo on GitHub](https://github.com/graphql/graphiql)).

**Comment by makyen** [comment]
@ArtOfCode- Given that I'm able to duplicate this, I'm happy to add whatever context helps you. However, my assumption is that it's best if you're able to duplicate the error yourself and that you being able to do so makes additional information here superfluous. Unless you say you want more information, I'm assuming the link in my prior comment was the thing you were missing in order to be able to duplicate the problem.

**Comment by thesecretmaster** [comment]
Got graphiql back up and running (hopefully) in b8da74d, I don't know if that solves this issue, but feels relevant.

**Comment by thesecretmaster** [comment]
Note: @tripleee  @makyen the problem here was on the backend, but it should've been post_tags not domain_tags.
