### ISSUE TITLE
Some URLs prevent metasmoke from extracting domain, UTF-8 related?

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#692]
It looks like two of the four hits on emexotechnologies have evaded linking by metasmoke. I don't have a proper way to test what caused this so the bug title is speculative at this point, but they seem to have managed to pass in a space before the closing > in the <a href="..."...> HTML tag.

1: https://metasmoke.erwaysoftware.com/post/209143

2: https://metasmoke.erwaysoftware.com/post/207360

All hits: https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body=emexotechnologies

**Comment by tripleee** [comment]
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=%3Ca+href%3D%22%5B%5E%3C%3E%5D*+%3E has many more such links and many of them were extracted, so my initial speculation seems to be wrong.

**Comment by Undo1** [comment]
Got a link to one of the offending posts? For some reason I’m not finding it with a simple search for `emoxextechnologies`.

**Comment by tripleee** [comment]
Updated -- sorry for the typo in the original description.

**Comment by tripleee** [comment]
Another example, with quite different formatting.

https://metasmoke.erwaysoftware.com/post/210509

Updating bug title.

**Comment by tripleee** [comment]
Another: https://metasmoke.erwaysoftware.com/post/212292

Looking definitely like percent encoding in the URL tail is the culprit. This should be completely run of the mill; why does this throw off metasmoke?

**Comment by ArtOfCode-** [comment]
We were trying to URI-decode the domain to deal with #615, but doing it at the wrong point and `URI.parse` was throwing on URIs that didn't look valid because of it.

I've also solved the other half of #615, in that domains with URI-encoded characters and domains with unencoded Unicode will both be normalized before parsing, so we don't end up with duplicates or domains that still have escapes in them.

**Comment by tripleee** [comment]
Still: https://metasmoke.erwaysoftware.com/post/212511

**Comment by ArtOfCode-** [comment]
Wasn't deployed - is now.
