### ISSUE TITLE
Feature request: Allow privileged users to annotate posts with domain links

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#698]
When a domain link was not properly extracted from a post when its record was created in metasmoke, it would be nice to be able to manually add a "domains:" entry for that domain.

For example, it would be nice to be able to add the missing links for the posts in #692 -- but also, sometimes domains are so obfuscated that there is no way automated extraction can reliably extract them; and yet, we heavily depend on being able to assess the number of hits we see for individual domains when we decide whether to blacklist something, for example.

I don't have a concrete proposal; I guess this should be a privileged operation only available to trusted users, but what level of trust exactly we want to require is unclear to me. I'm thinking this should be made easy to revert so that we can also be rather generous in allowing new users to do this.

**Comment by tripleee** [comment]
There seems to be some overlap with #444 but I don't think it ever was exposed as a user-accessible feature?

**Comment by thesecretmaster** [comment]
Core users can now add domains to posts. Requires DB access to remove, and the form is a lil awkward cuz generating HTML containing all 60k domains is expensive and bootstrap-select doesn't let you pull data from an api endpoint.
