### ISSUE TITLE
Make search use Ruby's regex engine instead of MySQL's

### ISSUE THREAD

**Issue by ArtOfCode-** [Charcoal-SE/metasmoke#70]
Search is a pretty good proxy for #69, certainly for the long-standing reasons. The major problem with it is the terrible regex support.

Instead of using the MySQL regex commands, we should leave fields out of the DB query if `field_is_regex=1`, and iterate through the results after we get them back from the DB, running the regexes in Ruby, and dropping results that don't match.

**Comment by Undo1** [comment]
First reaction is that this would probably be a performance nightmare on an already-slow page. For paging to work right, you'd need to fetch the top `100+n` results, where `n` is the number you'll throw out with your regex... and you don't know `n` ahead of time, so you're guessing and probably making multiple trips to the database.

**Comment by ArtOfCode-** [comment]
@Undo1 I dunno, actually. Ruby regex is *significantly* faster than MySQL regex, which is where most of the slow comes from.

You could *probably* do it by fetching *everything* matching the regexes-excluded query (i.e. don't call `paginate`), then start iterating, dropping as needed, and break as soon as you have `pagesize` in your results collection.

**Comment by Undo1** [comment]
That's a whole bunch of data to be moving around and storing in memory. Might be worth a try, though.
