### ISSUE TITLE
ActiveModel::RangeError in UserSiteSettingsController#create

### ISSUE THREAD

**Issue by leonheess** [Charcoal-SE/metasmoke#702]
If you input a high enough number when changing max_flags it fails:

"%input% is out of range for ActiveModel::Type::Integer with limit 4 bytes"

_Extracted source (around line #40):_
```
    @preference.site_ids = params[:user_site_setting][:sites]

    if @preference.save
      flash[:success] = 'Saved your preferences.'
      redirect_to url_for(controller: :user_site_settings, action: :index)
    else
```
_Rails.root: /var/railsapps/metasmoke/releases/20200103021727_
_Trace: app/controllers/user_site_settings_controller.rb:40:in `create'_

**Comment by ArtOfCode-** [comment]
Declined: that's a 32-bit integer, i.e. max of 2147483647. There's no reason to go anywhere north of 100 in that field, let alone that high.
