### ISSUE TITLE
Redirection via http:// URLs is broken

### ISSUE THREAD

**Issue by EliahKagan** [Charcoal-SE/metasmoke#704]
Since the metasmoke migration, `http://` URLs don't seem to work. `https://` URLs do still work. Attempting to load a page on metasmoke with a `http://` URL takes a very long time--perhaps a couple minutes--and eventually fails with a 503 Service Unavailable error.

I expect it to instead redirect to the corresponding `https://` URL. I believe this was the behavior before. Note that some links to metasmoke that SmokeDetector posts in chat--specifically the "[ MS ]" links on messages about feedback--are `http://` links. [Here's an example of such a message.](https://chat.stackexchange.com/transcript/message/53284084#53284084)

The workaround of manually adding an "s" to change the protocol from http to https is completely effective.

Some information and additional context for this bug can be found [in Charcoal HQ](https://chat.stackexchange.com/transcript/message/53284173#53284173).

**Comment by thesecretmaster** [comment]
We should definitely add a http->https redirect, but I think that we should also fix Smokey to post https links. I can see no reason why they should be http.

**Comment by makyen** [comment]
@thesecretmaster The HTTP link in feedback notifications appears to be a message relayed from MS. As far as I could tell, it doesn't originate with SD.

There were places where SD did have "http" which definitely should have been "https". I've changed those and changed most of SD's tests to use "https".

**Comment by teward** [comment]
I'm in the process of debugging this.  The initial reason for this:

LetsEncrypt at HAProxy listens on 80 for incoming.  So that's the 'default'.  80 -> 443 shouldn't be an issue now that we have a valid cert on it, so I'll set up the redirect at the HAProxy level.

However, patience is needed, because I'm away from my home network (VPN is slow)

**Comment by teward** [comment]
This should be fixed now, HAProxy rules set up for 80 -> 443.

```
$ curl -I http://metasmoke.erwaysoftware.com/
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://metasmoke.erwaysoftware.com/
```
