### ISSUE TITLE
Moderately complex searches get "504 Gateway Time-out" response

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#705]
I tried to run a [moderately complex search](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=%28%3Fs%3A%5Cb%28%3F%3Aearn%5B%5CW_%5D*%2Bfree%5B%5CW_%5D*%2Bbitcoin%7Cfree.%7B0%2C40%7Dearn%5B%5CW_%5D*%2Bbitcoin%7Cearn%5B%5CW_%5D*%2Bbitcoin%28%3F%3D.%7B0%2C40%7Dfree%29%29%5Cb%29), which resulted in a response:
> ### 504 Gateway Time-out  
> The server didn't respond in time. 

I've gotten similar responses a few/several times since the move to the new system.

In the past, searches would still return results even after a very long time. I've had ones that have taken more than an hour to complete. An example of a longer one was the search mentioned in [this PR](https://github.com/Charcoal-SE/SmokeDetector/pull/2113), which took more than forty minutes.

**Comment by teward** [comment]
I have to adjust the HAProxy timeout config then to accept insanely long response times.  Add that to the list of things I have to get done.

**Comment by teward** [comment]
@makyen try again, I've bumped the gateway response timeout in HAProxy to 60 minutes.  That should fix the 504 Gateway Timeout issues.  (Please close this if the issue is resolved)

**Comment by makyen** [comment]
Thanks for the fix. The above search did work, which I assume you'd already tested. I'll run a few longer searches, but I expect the problem is solved (unless someone is doing a *really* long search :-) ).

**Comment by teward** [comment]
@makyen my thought with 60min max is any search that takes longer than an hour to complete should be rethought out but that's just my opinion.  As long as it works, all's good :)

**Comment by makyen** [comment]
@teward  I agree that such searches should be rethought, unfortunately some of the constructs to mimic SD's capabilities can get a bit complex. Fortunately, that improved significantly once we had PCRE on MS.

As to the length of the timeout, currently, MS doesn't stop working on the search when the request is 504'ed, so it's going to keep a process on MS going until the search completes. At least in the past, one of the limits on MS was the maximum number of concurrent request threads. While that number was increased (the number I'm remembering as now current is 4), I find it helpful to know when a search actually completes on MS in order to limit the active requests I make. When doing testing for new regexes, I'll be sure not to have more than two searches active at a time to leave resources available for other uses of MS. If we're going to limit the time for a response, then it would be good if MS would stop working on a request once that time expires.
