### ISSUE TITLE
Allow watching or blacklisting domains from metasmoke

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/metasmoke#715]
When I click on a post in metasmoke, it tells me which domains were found in that post. I can also search for those domains to see how many times it's been seen.

Now, if I want to watch or blacklist any of those domains, I then have to go back to chat, and type the command manually.

Can it please be easier to watch or blacklist domains seen in a post when looking at its metasmoke record? It would be nice if there were buttons to watch or blacklist a domain from the domain record, or better yet, the post itself.

**Comment by makyen** [comment]
The easiest way to do this would probably be a userscript which would just send a chat message to CHQ with the `!!/watch` or `!!/blacklist` command.

**Comment by gparyani** [comment]
@makyen It would be nice to have it in metasmoke itself, so I can use it even on mobile devices (on which user scripts can't be installed, and on which typing in the request manually is a much bigger pain).

**Comment by thesecretmaster** [comment]
Marking as deferred because it seems like a lot of work for not a lot of gain, it would require changes both smokey-side and MS side
