### ISSUE TITLE
Sorting weight for reasons won't work as intended

### ISSUE THREAD

**Issue by user12986714** [Charcoal-SE/metasmoke#723]
At [this](https://metasmoke.erwaysoftware.com/reasons) page on metasmoke, reasons, after trying to sort reason weight for either increasing or decreasing, the list won't sort as intended.

Expected order: (increasing)
1 14 22 27 ... 99 100

Current order: (increasing)
1 100 14 22 27 ... 99

100 is smaller than 14?
[Screenshot](https://imgur.com/jO4OsBO)

**Comment by user12986714** [comment]
[Added screenshot](https://imgur.com/LY3eMCZ)

**Comment by ArtOfCode-** [comment]
Classic text sort vs number sort issue.

**Comment by user12986714** [comment]
Yet "number caught" field sorts just fine... But not "reason weight".
