### ISSUE TITLE
Repeated identical reports of one same post

### ISSUE THREAD

**Issue by user12986714** [Charcoal-SE/metasmoke#724]
Due to various reasons, we have repeated identical reports of one post. [Example](https://metasmoke.erwaysoftware.com/posts/by-url?url=//buddhism.stackexchange.com/a/38728). Repeated reports may be caused by *another* answer on the same question being edited, or the post being reported manually by `!!/allspam`, which will cause SD to send reports to MS without inspecting if it has already been reported.

One may want to implement some checks on MS, in an effort to discard identical reports.

Reasons: identical reports are incredibly annoying, is a waste of review effort, and causes inaccuracies when evaluating tp/fp percentages using search.

**Comment by teward** [comment]
This... is always how MetaSmoke has worked.

Identical reports also show trends-over-time and revisions/edits of the same post.  This is how SmokeDetector has always worked and how Metasmoke has always worked.

Consider an example:

SPAMMER posts something that is bad as an edit to a post per Vandalism on a stolen account.
Someone reverts it.
Spammer comes back in and edits it again, adding the same spam content.

That would trigger **two separate reports** for **two separate incidents of the same spam**.  This is by-design behavior so we can track all the cases of such spam on the post, especially when edit spammers hit the same post multiple times.

**Comment by user12986714** [comment]
(@teward ) Yes, that is true. However, the problem is that MS seems to keep duplicated reports even when the original post is not edited (no revision history), but another post on the same question get edited; or when the original post is not edited but someone reported it again with !!/allspam

**Comment by user12986714** [comment]
Closed as this is due to SD, not MS.
