### ISSUE TITLE
"Edit description" blanks any existing rule description

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#725]
I wanted to edit https://metasmoke.erwaysoftware.com/reason/143 but noticed that the old description disappears when you click "Edit description".

(The old description was the one I entered just seconds before, so it wasn't hard to reconstruct. Still, that's data loss.)

**Comment by ArtOfCode-** [comment]
Norepro - the existing description doesn't appear in the textbox when you click "Edit description", but it isn't deleted - cancelling the dialog and reloading the page shows it still there for me.

**Comment by tripleee** [comment]
The problem is that the old description is not in the edit box. If this is by design, the button should say "replace description", not "edit description".

**Comment by double-beep** [comment]
By design? It's `nil` (instead of `@reason.description` which you suggest).
https://github.com/Charcoal-SE/metasmoke/blob/0b652cc8754eb92deb892e9c4967d6ab20b7f2be/app/views/reasons/show.html.erb#L56
