### ISSUE TITLE
The site picker is missing

### ISSUE THREAD

**Issue by NobodyNada** [Charcoal-SE/metasmoke#73]
The site picker for the autoflagging preferences is invisible:

![screen shot 2017-01-19 at 12 31 57 pm](https://cloud.githubusercontent.com/assets/19418817/22124182/867b986a-de43-11e6-8c81-68cfacba1630.png)

I'm using Safari 10.0.2 on macOS 10.12.2.  I get this JavaScript error in the console, twice:

    TypeError: $(".selectpicker").selectpicker is not a function. (In '$(".selectpicker").selectpicker()', '$(".selectpicker").selectpicker' is undefined)

**Comment by NobodyNada** [comment]
Nevermind; it was caching and a shift-reload fixed it.

**Comment by angussidney** [comment]
Known bug experienced by many people, strangely it only seems to appear the first time you use it so I'm not sure what's causing it. I might add a note there to tell people to reload.

**Comment by ArtOfCode-** [comment]
@angussidney I've run into what I *think* is a similar kind of bug before, so I may be able to fix it - just need to get some time to do that.

**Comment by ArtOfCode-** [comment]
Should be fixed by c19a260919db85a25250118b943fb329e5fd8fd7.
