### ISSUE TITLE
Autoflagging is slow & recorded time of flagging is inaccurate

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#739]
### Slow autoflagging (delays of tens of seconds, minutes, or even tens of minutes)
Something that happened around the same time MS was moved to ThomasWard's infrastructure resulted in a significant increase in how long it took MS to raise autoflags from when the post is reported. Prior to the move, it used to be difficult for a human to see the SmokeDetector report in chat and raise a flag, even using FIRE, prior to the autoflags starting to be raised. Now, it's normal for there to be multiple people manually flagging posts through MS prior to the autoflags being raised. It is not uncommon to see many seconds go by, or even minutes prior to the autoflags being raised. In an extreme case, there was 33 minutes of delay between when the post was reported and when autoflags were raised.

The **33 minute** extremely delayed autoflagging example ([from chat](https://chat.stackexchange.com/transcript/11540?m=54800987#54800987) about [this SD report](https://chat.stackexchange.com/transcript/11540?m=54800574#54800574)):

> @ArtOfCode @Undo There's definitely something wrong/inaccurate with the date-time recorded for when the spam flags were raised on [this post](https://metasmoke.erwaysoftware.com/post/250444). The post was created at 21:44:41 UTC. MS claims that all three flags were raised at 21:45:26 UTC. My browser history shows I ctrl-F5 refreshed the post's page on MS at 21:51 UTC and no flags were shown at that time.
> Looking on SO, at the record of the flag raised for SD, it shows the flag was actually raised at 22:18:07 UTC, or ~33 minutes after MS claims.
> Also, that's ~33 minutes of lag time between when a post was reported and when it was autoflagged. That's really not good. That delay used to be a couple/few seconds (faster than most human feedback/flagging).

### Inaccurate time recorded for when the autoflags were raised
Note that in the above example, there's a 33 minute difference between when MS claims the autoflags were raised, 21:45:26 UTC, and the time SE recorded for the autoflags being raised, 22:18:07 UTC. Under most conditions, I'd normally assume that the clock on one of the systems isn't synced to a time server. However, that delay was real, based on myself and others actively watching for flags to be raised on the post. It was being watched more carefully than normal, because the post was FP, so I wanted to make sure to retract SD's autoflag shortly after it was raised.

**Comment by artofcode** [comment]
@ArtOfCode- , one for you mate :-)

**Comment by ArtOfCode-** [comment]
Heh, cheers @artofcode :)

**Comment by teward** [comment]
@ArtOfCode- and I started the dig process.

According to the system logs, this is the timestamps of autoflagging related activity for the post:

    W, [2020-06-29T21:45:37.309626 #13338]  WARN -- : [autoflagging] 250444: post.save succeeded
    W, [2020-06-29T21:45:37.309984 #13338]  WARN -- : [autoflagging] 250444: thread begin
    W, [2020-06-29T21:45:37.310591 #13338]  WARN -- : [autoflagging] 250444: Post#autoflag begin
    W, [2020-06-29T21:45:37.314135 #13338]  WARN -- : [autoflagging] 250444: not a dupe
    W, [2020-06-29T21:45:39.319793 #13338]  WARN -- : [autoflagging] 250444: fetched conditions
    W, [2020-06-29T21:45:41.594007 #13338]  WARN -- : [autoflagging] 250444: before revision count
    W, [2020-06-29T21:45:41.594088 #13338]  WARN -- : [autoflagging] 250444: fetch_revision_count begin
    W, [2020-06-29T21:45:41.594220 #13338]  WARN -- : [autoflagging] 250444: site was present
    W, [2020-06-29T21:45:42.151841 #13338]  WARN -- : [autoflagging] 250444: queried SE: 1
    W, [2020-06-29T21:45:42.425601 #13338]  WARN -- : [autoflagging] 250444: lottery begin
    W, [2020-06-29T21:45:42.427283 #13338]  WARN -- : [autoflagging] 250444: scaled maxes: ["0", "0", "0", "99.9", "101", "101"]
    W, [2020-06-29T22:18:05.069978 #13338]  WARN -- : [autoflagging] 250444: send_autoflag begin: SmokeDetector
    W, [2020-06-29T22:18:06.609388 #13338]  WARN -- : [autoflagging] 250444: has enough flags
    W, [2020-06-29T22:18:06.612031 #13338]  WARN -- : [autoflagging] 250444: pre spam_flag
    W, [2020-06-29T22:18:07.986873 #13338]  WARN -- : [autoflagging] 250444: post spam_flag
    W, [2020-06-29T22:18:08.398413 #13338]  WARN -- : [autoflagging] 250444: send_autoflagged...
    W, [2020-06-29T22:18:08.627624 #13338]  WARN -- : [autoflagging] 250444: broadcast
    W, [2020-06-29T22:18:08.627731 #13338]  WARN -- : [autoflagging] 250444: core...
    W, [2020-06-29T22:18:08.630634 #13338]  WARN -- : [autoflagging] 250444: send_autoflag begin: User1
    W, [2020-06-29T22:18:08.718461 #13338]  WARN -- : [autoflagging] 250444: has enough flags
    W, [2020-06-29T22:18:08.720730 #13338]  WARN -- : [autoflagging] 250444: pre spam_flag
    W, [2020-06-29T22:18:09.541835 #13338]  WARN -- : [autoflagging] 250444: post spam_flag
    W, [2020-06-29T22:18:09.603524 #13338]  WARN -- : [autoflagging] 250444: send_autoflagged...
    W, [2020-06-29T22:18:09.615434 #13338]  WARN -- : [autoflagging] 250444: broadcast
    W, [2020-06-29T22:18:09.615507 #13338]  WARN -- : [autoflagging] 250444: plebs...
    W, [2020-06-29T22:18:09.626061 #13338]  WARN -- : [autoflagging] 250444: send_autoflag begin: User2
    W, [2020-06-29T22:18:09.717404 #13338]  WARN -- : [autoflagging] 250444: has enough flags
    W, [2020-06-29T22:18:09.719761 #13338]  WARN -- : [autoflagging] 250444: pre spam_flag
    W, [2020-06-29T22:18:10.089668 #13338]  WARN -- : [autoflagging] 250444: post spam_flag
    W, [2020-06-29T22:18:10.089847 #13338]  WARN -- : [autoflagging] 250444: send_autoflag begin: User3
    W, [2020-06-29T22:18:10.148536 #13338]  WARN -- : [autoflagging] 250444: has enough flags
    W, [2020-06-29T22:18:10.185719 #13338]  WARN -- : [autoflagging] 250444: pre spam_flag
    W, [2020-06-29T22:18:10.931071 #13338]  WARN -- : [autoflagging] 250444: post spam_flag
    W, [2020-06-29T22:18:10.995647 #13338]  WARN -- : [autoflagging] 250444: send_autoflagged...
    W, [2020-06-29T22:18:11.011217 #13338]  WARN -- : [autoflagging] 250444: broadcast

ActionCable logs confirm the post creation time in MS as follows:

    "created_at"=>Mon, 29 Jun 2020 21:45:26 UTC +00:00

The discrepancy happens between the scaled maxes task and the send_autoflag task.  I believe that @ArtOfCode- has offered to take a look later when they're not in the middle of things, to see what could go wrong specifically with the process between these two timepoints, which is where the ~30 minute discrepancy is seen:

    W, [2020-06-29T21:45:42.427283 #13338]  WARN -- : [autoflagging] 250444: scaled maxes: ["0", "0", "0", "99.9", "101", "101"]
    W, [2020-06-29T22:18:05.069978 #13338]  WARN -- : [autoflagging] 250444: send_autoflag begin: SmokeDetector

**Comment by ArtOfCode-** [comment]
I've added and deployed some more logging around there. There's a query that checks historical accuracy in there, and I wonder if that's being slow.

**Comment by teward** [comment]
NOTE: Within a week or so I will be moving Metasmoke around to a new storage array in my server farm, that's SSD powered.  That should HOPEFULLY improve performance across the board.

**Comment by teward** [comment]
With the move to SSD backed storage and the addition of a few DB indexes this looks to be resolved now.
