### ISSUE TITLE
Some posts not recording feedback? (resulting in a 'feedback recorded' post loop via SD)

### ISSUE THREAD

**Issue by teward** [Charcoal-SE/metasmoke#750]
https://metasmoke.erwaysoftware.com/post/149859 as an example, has gotten multiple feedback submissions for it today, and none of the feedback seems to be being kept/logged as feedback.

https://chat.stackexchange.com/transcript/message/54895296#54895296 is where you can see the chat logs begin for it with attempting to put feedback on it.

**Comment by teward** [comment]
@ArtOfCode- dug and found some redis errors triggering for this one.  (Adding the redis tag)

**Comment by thesecretmaster** [comment]
For some reason, there was a sorted set where there should've been a set. No idea why. But it was a one off thing, since that particular post was in my redis dump from 6+ months ago, so I don't think this bug should occur again.
