### ISSUE TITLE
The 'Preview' button is broken on the autoflagging conditions

### ISSUE THREAD

**Issue by superplane39** [Charcoal-SE/metasmoke#77]
The first time you go to set your autoflagging conditions, the preview button works great, it gives you a nice helpful preview. If you go to edit your conditions afterwards, however, the preview button does nothing. You click, and it gives the exact same stats as before.

**Comment by angussidney** [comment]
I've repro'd this before

**Comment by Fortunate-MAN** [comment]
I have repro'd this too IIRC.

**Comment by ArtOfCode-** [comment]
This is related to the bug we've been seeing with the multiple-select not showing up on the first page load - clicking the Preview button often does nothing on the first page load, either. You can verify that by using the Network tab of your browser developer tools - the Preview button *should* issue a network request, but often doesn't on first load.

Fixed (I hope) in c19a260919db85a25250118b943fb329e5fd8fd7, pending deploy.
