### ISSUE TITLE
Deleting a user wipes the manual flag logs for all users

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#770]
When user12986714 [asked for](https://chat.stackexchange.com/transcript/11540?m=54946841#54946841) an MS account they created for testing to be deleted, [I actually did it](https://chat.stackexchange.com/transcript/11540?m=54947005#54947005). Unfortunately, doing so wiped the manual flag logs for all users, or at least all of them that I've checked.

Something very similar happened when [I deleted shree's account](https://chat.stackexchange.com/transcript/11540?m=54595753#54595753) on 2020-06-08.

**Comment by teward** [comment]
Was this fixed by #765?  Do we want to run a test-case since we have functioning backups?

**Comment by user12986714** [comment]
I have tested this locally and the flag logs were *not* deleted when destroying a user.

**Comment by makyen** [comment]
Thanks for the reminder. Yes, this has been tested on the production system some time ago (a while, but not all that long ago) and the issue is resolved.
