### ISSUE TITLE
Several popups won't close after clicking the action button

### ISSUE THREAD

**Issue by user12986714** [Charcoal-SE/metasmoke#779]
Already verified: (On both Firefox 68.10.0esr and Chromium 83.0.4103.116, platform Linux, $CC=gcc (8.3.0))
- Admin report popup will not close after clicking "Report" button
- Add domain link popup will not close after clicking "Link" button

**Comment by makyen** [comment]
The domain link popup is now fixed, as a result of #935. Some of the changes there would have also affected the Admin report popup. While I didn't test the admin report popup prior to those changes, the admin report popup is working for me now. I'm going to assume this is resolved.
