### ISSUE TITLE
Prevent unstable rules from contributing to autoflagging weight

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#80]
Until a rule has actually been tested against a reasonable number of messages, a 100% TP rate should not add 100 to the autoflagging weight.  A new rule (or ideally, to be really safe, any recently changed rule) should simply add 0 (or perhaps some small value instead of 100) to the autoflagging weight until we have substantial evidence to support it.

Tentatively, don't promote a rule to a position where it contributes to the weight until it has been run against 100 (or 200? or 500?) posts.

Discussion (or more like monologue): http://chat.stackexchange.com/transcript/message/34974667#34974667

**Comment by Glorfindel83** [comment]
Maybe the max. weight of a rule should be limited by the # of posts it ran on (e.g. a rule triggered by 50 posts has a weight of min(50, accuracy %)).

**Comment by ArtOfCode-** [comment]
Already a thing - reasons have 0 weight until they've run on at least 20 posts. Threshold is open to debate.

**Comment by tripleee** [comment]
Thanks.  What about edits to existing rules and quarantining those somehow?  I guess that should be a separate request and a fairly substantial effort in its own right anyway.

**Comment by ArtOfCode-** [comment]
@tripleee Minor edits won't affect accuracy too much; we can probably rely on the existing system there. Major edits should probably be sent off to a new rule anyway.
