### ISSUE TITLE
Allow very old posts to be completed with only one fp feedback under certain conditions

### ISSUE THREAD

**Issue by Rubiksmoose** [Charcoal-SE/metasmoke#812]
My proposal is that we allow old posts to be cleared from the review queue after only one fp if the reports are over 60 days old and have reason weight <=5.

[This query](https://metasmoke.erwaysoftware.com/data/sql/queries/241-posts-which-are-in-the-queue-with-1-fp-and-low-weight-and-report-is-2-months-old?limit=100000) should capture that condition.

See on [Teams](https://stackoverflow.com/c/charcoal/questions/645).

**Comment by ArtOfCode-** [comment]
Done
