### ISSUE TITLE
Move website build from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/metasmoke#816]
As of now, GitHub Actions officially supports triggering (starting a new run) via API. The API is a simple POST route so it should be easily accomplishable (e.g. `Net::HTTP.post`)

Benefits:

- Runs faster than Travis CI, which boots for almost a minute, in which time GHA will have completed already
- More secure, as [GHA provides a `GITHUB_TOKEN`][1] for each workflow run that can be used to push to the deploy branch of the website repo
  - One less credential to manage off-site
- One less external dependency

References:

- <https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch>
- <https://docs.github.com/en/rest/reference/actions/#create-a-workflow-dispatch-event>

  [1]: https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

**Comment by thesecretmaster** [comment]
Not sure what you mean by "website build" but if you're talking about MS I think that's not feasible because we want to control who has ssh access to MS seperately from who is a GH admin, and the deploy script requires an SSH key. If you're talking about charcoal-se.org, that issue should be made on that repo, not here.

**Comment by makyen** [comment]
@iBug I don't think that alleviates the concern about the SSH key. Setting up the MS build process up as part of GitHub Actions puts the ability to do an MS build in the hands of anyone with Owner access to the Charcoal-SE organization, and potentially the ability to get the SSH key (I'd have to check to see if such a secret was obtainable, but it definitely makes it *possible* to obtain unrestricted acces). So far, the list of users who are Charcoal-SE Owners (i.e. MS Admins) and the list intended to have Deploy access (i.e. MS Developers) has been separate, and is separate from those with SSH access (a subset of MS Developers).

**Comment by iBug** [comment]
@thesecretmaster @makyen I've updated the issue title and description to clear certain confusions. Can we re-open this? There's been a level of degradation on Travis CI recently and it's less reliable now.
