### ISSUE TITLE
Permissions error on Wiki build webhook

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#824]
The [gollum_hook](https://github.com/Charcoal-SE/metasmoke/blob/master/app/controllers/github_controller.rb#L48), which is responsible for triggering a website rebuild every time the wiki is updated, is returning an error every time Github attempts to send a payload:

([source](https://github.com/Charcoal-SE/SmokeDetector/settings/hooks/12739390))

```
Travis::Client::Error
      in GithubController#gollum_hook

...

You do not seem to have sufficient permissions.
```

Looks like some sort of authentication error between metasmoke and Travis?

**Comment by thesecretmaster** [comment]
It appears that we now use GH actions instead of travis for this so I assume this is resolved
