### ISSUE TITLE
Add reason weight to Posts API

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#84]
@angussidney [suggested](http://chat.stackexchange.com/transcript/11540?m=35190751#35190751) to add the reason weight to the Autoflagging Information script. I'd love to do that, but it needs to be exposed in the API. It could be that the field `score` is the one I need, but currently it always [returns `null`](https://metasmoke.erwaysoftware.com/api/posts/urls?key=d897aa9f315174f081309cef13dfd7caa4ddfec1c2f8641204506636751392a4&urls=//drupal.stackexchange.com/questions/227544).

**Comment by ArtOfCode-** [comment]
`score` is not the field you are looking for.

**Comment by Glorfindel83** [comment]
I'm curious to what it *is* then. That also makes this a feature-request.

**Comment by ArtOfCode-** [comment]
Originally intends to store the post score, but we don't use it.
