### ISSUE TITLE
Dependencies update required, due to mimemagic 0.3.5 being yanked

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#849]
We currently use the 0.3.5 version of the mimemagic gem. That project recently (probably 2021-03-25) yanked the 0.3.5 version from distribution. The currently available 0.3.x versions are 0.3.7 – 0.3.10. All versions have updated dependencies, so a quick drop-in manual version change in Gemfile.lock isn't sufficient. Someone with a full development environment will need to update dependencies.

**Comment by makyen** [comment]
I see from [this comment](https://github.com/mimemagicrb/mimemagic/issues/127#issuecomment-807902889) by [rstacruz](https://github.com/rstacruz) that the issue is a licensing problem:

> Unfortunately this [keeping old versions] isn't possible because of legal licensing issues. It also isn't possible to push new code in place of the old versions.
> 
> * https://www.theregister.com/2021/03/25/ruby_rails_code/
> 
> * [rails/rails#41750](https://github.com/rails/rails/issues/41750)

The short story is that all 0.3.x versions < 0.3.7 and 0.4.x versions < 0.4.1 are GPL licensed, even though they claim to be MIT licensed, due to including some GPL code/content. All of those versions of mimemagic have been yanked. The package/gem was changed as of 0.3.7 and 0.4.1 to remove the GPL'ed content and, thus return to an MIT license.

**Comment by user12986714** [comment]
It would be safe to upgrade if we have `shared-mine-info` *system* package installed. Otherwise everything will be on fire...
