### ISSUE TITLE
Websocket for Charcoal HQ extensions

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#85]
The Autoflagging Information userscript currently pulls its data from the MS API (/api/posts/urls). This is fine for the initial load when you enter the chatroom. But for reports which come in later, it's better to push it, so @Undo1 [suggested](http://chat.stackexchange.com/transcript/11540?m=35219476#35219476) to build a WebSocket for this.

There's more information from MS that could be used in Charcoal HQ, and the userscript could be extended to handle this:

- When MS detects a reported post is deleted, this information can be pushed and the userscript can grey out / strikethrough the corresponding Smokey report
- Feedback (TP/FP/NAA) can be displayed 'live', e.g. 

![](http://i.stack.imgur.com/GVflj.png)

**Comment by Undo1** [comment]
This should be done. Use like so:

```
var socket = new WebSocket("wss://metasmoke.erwaysoftware.com/cable");

socket.onmessage = function(msg){
	console.log(JSON.parse(msg.data));
}

var s = '{"identifier": "{\\"channel\\":\\"ApiChannel\\",\\"key\\":\\"your key\\"}", "command": "subscribe"}'
socket.send(s)
```

And you'll see results like so:

![screen shot 2017-02-07 at 10 25 13 pm](https://cloud.githubusercontent.com/assets/5162342/22724738/7f39c008-ed85-11e6-90e6-49afbcdeb6aa.png)
![screen shot 2017-02-07 at 10 32 54 pm](https://cloud.githubusercontent.com/assets/5162342/22724739/7f39d444-ed85-11e6-9225-439a175a3ea3.png)
![screen shot 2017-02-07 at 10 35 00 pm](https://cloud.githubusercontent.com/assets/5162342/22724787/cd09ee48-ed85-11e6-9c50-b2f880e2bcd9.png)

Let me know if you need/want anything more.

**Comment by Glorfindel83** [comment]
Thanks, I'm able to connect, but all I get is 'welcome' and then 'ping' messages. Also, an exception occurs in the 'send' method. Or does this simply not work from the browser console? Tested with FF and Safari on macOS.

<img width="712" alt="screen shot 2017-02-08 at 10 22 48" src="https://cloud.githubusercontent.com/assets/24611142/22730842/d5ca1496-ede8-11e6-83f3-813948b9fd72.png">

**Comment by ArtOfCode-** [comment]
@Glorfindel83 Replace "your key" with a real key.

**Comment by ArtOfCode-** [comment]
Tested, confirmed working from a browser console. Calling this status-completed.

**Comment by Glorfindel83** [comment]
As noted [here](http://chat.stackexchange.com/transcript/message/35296001#35296001), it's still not working for me, even after using the userscript's MS API key. If you have any idea, or can add some server-side tracing which checks why it isn't working, that would be great.

**Comment by ArtOfCode-** [comment]
@Glorfindel83 I suspect it is working, actually - the undefined messages are normal, and getting actual data down that socket isn't that common.

**Comment by Glorfindel83** [comment]
But I have been keeping the browser console open for multiple hours ...
Could any of you show *your* output?

**Comment by Undo1** [comment]
@Glorfindel83 Are you running this from a chat.(SE|SO|MSE) domain? ActionCable will reject other domains.

**Comment by Undo1** [comment]
@Glorfindel83 Issue was that `sock.send` doesn't work until the socket is established; you need to use the callback. This works for me:

```
var KEY = "my_key";
var sock = new WebSocket("wss://metasmoke.erwaysoftware.com/cable");
sock.onmessage = function(data) {
    var jsonData = JSON.parse(data.data);
    if (jsonData["type"] == null || jsonData["type"] != "ping") {
        console.log(jsonData.message);
    }
};

sock.onopen = function() {
    var auth = '{"identifier": "{\\"channel\\":\\"ApiChannel\\",\\"key\\":\\"' + KEY + '\\"}", "command": "subscribe"}';
    sock.send(auth);
};
function () {
    var auth = '{"identifier": "{\\"channel\\":\\"ApiChannel\\",\\"key\\":\\"' + KEY + '\\"}", "command": "subscribe"}';
    sock.send(auth);
}
```

**Comment by Glorfindel83** [comment]
Thanks, I confirmed it's working.
