### ISSUE TITLE
SSL cert for MetaSmoke site expired 11 May 2021

### ISSUE THREAD

**Issue by Tyler-H** [Charcoal-SE/metasmoke#861]
The SSL cert for https://metasmoke.erwaysoftware.com/ expired today:

![image](https://user-images.githubusercontent.com/206492/118005126-1ce09780-b318-11eb-8c77-e2150301f5e1.png)

Not sure who would handle that re-certification.

**Comment by teward** [comment]
We already know.

Not a MS bug.

**Comment by Tyler-H** [comment]
Thanks @teward; where's the right place to alert the team when it expires next time, or there's some other problem with the website? This is the only MS repo I could find.

**Comment by teward** [comment]
> Thanks @teward; where's the right place to alert the team when it expires next time, or there's some other problem with the website? This is the only MS repo I could find.

You were already preempted by other team members by over 12 hours.  I end up being the one who has to handle the issue, but likely I've already been notified long before a GH issue is raised.

**Comment by Tyler-H** [comment]
That doesn't really answer my question.

**Comment by teward** [comment]
Your first thing should be to check https://chat.stackexchange.com/rooms/11540/charcoal-hq and pinned posts.  If someone's already reported it there's going to be a pin about it and then you don't *have* to ping anyone about this issue.

If there's not, state it in the chat room.  No need to ping anyone.

GH issues is not the issue to ping us about the expired SSL.

**Comment by Tyler-H** [comment]
Thanks; the team may want to consider policy for pinning in https://chat.stackoverflow.com/rooms/111347/sobotics as well since the chat server separation between SO and everywhere else means lots of folks might not ever see Charcoal HQ on SE chat.
