### ISSUE TITLE
Add deletion status to Posts API

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#87]
Thanks to the new websocket, we can receive realtime deletion information and gray out the corresponding Smokey report (this is already working in my development environment). I'd like to have a deletion status field in the Posts API as well, so that upon loading of the chatroom, I can do the same for older messages. A boolean field is more convenient for me, but transferring the deletion date is probably just as easy and more valuable for other uses of the API.

**Comment by Undo1** [comment]
![screen shot 2017-02-09 at 10 50 09 am](https://cloud.githubusercontent.com/assets/5162342/22795893/8d3573b0-eeb5-11e6-9a68-7e7db0fdec74.png)

Will be `null` if we don't have an affirmative `deletion_log` for a post.
