### ISSUE TITLE
"Contains domains:" on posts page shows (0, 0, 0)

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#876]
This is not true on all pages, but e.g. https://metasmoke.erwaysoftware.com/post/324620 shows

* scoop.it (0, 0, 0)
* a1ketobhbsharktank.wixsite.com (0, 0, 0)

even though the former has been massively spammed over many years; https://metasmoke.erwaysoftware.com/domains?utf8=%E2%9C%93&filter=scoop.it shows it as

* scoop.it 59 (58, 1, 0)

Regression from recent library updates?

**Comment by thesecretmaster** [comment]
Sounds like the same issue as #810?

**Comment by tripleee** [comment]
Yeah, probably ... I assumed it was related to the recent dependency updates but apparently not.
