### ISSUE TITLE
Add a way to mark a post as deleted on MS

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/metasmoke#89]
See https://chat.stackexchange.com/rooms/11540/conversation/add-a-way-to-mark-a-post-as-deleted-on-ms for info and alternatives.

**Comment by Cerbrus** [comment]
I more or less suggested the same, [here](http://chat.stackexchange.com/transcript/message/36480755#36480755).

I could automate FIRE to send "deleted" feedback when a reported post is loaded.
Not sure if I have access to the deleted date/time, though.

**Comment by angussidney** [comment]
I could probably make a tool which reverse-engineers the way Smokey sends deletion data, but unfortunately that'd only be avaliable for people with Smokey keys

**Comment by Cerbrus** [comment]
@angussidney: Preferably, it'd be just another api endpoint.

**Comment by angussidney** [comment]
@Cerbrus yeah, and it'd probably be faster for me to write the API endpoint than make a tool, even with my limited ruby skills

**Comment by ArtOfCode-** [comment]
Done in c7c888212027e96950a7c979aa74b31c4b05a748 (@Cerbrus)
