### ISSUE TITLE
<select> in the flagging conditions page duplicate when pressing back

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/metasmoke#892]
1. Go to a flagging conditions page
![image](https://user-images.githubusercontent.com/1576684/139716113-2053eeb2-befd-409a-be96-20b5564e51bc.png)
2. Go to another page like "status" on the top
3. Press the browser back button

**Expected**:
I expect the old page to load

**Actual**:
We now have 2 site instances of the &lt;select> box
![image](https://user-images.githubusercontent.com/1576684/139716324-d0f4dce0-be93-4edd-a75c-8420dee741cc.png)

(repeat the steps to get even more duplicated selection inputs)

**Comment by makyen** [comment]
This actually affects multiple pages which have a similar type of selection input, not just "Sites".
