### ISSUE TITLE
database is too big for Docker

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#900]
When importing the latest database, I bumped into

```
 => [14/21] COPY . .                                                       8.2s
 => [15/21] RUN gem install bundler                                        2.0s
 => [16/21] RUN bundle update --bundler                                  211.1s
 => [17/21] RUN bundle install                                             2.0s
 => ERROR [18/21] RUN ./createdb                                           2.0s
------
 > [18/21] RUN ./createdb:
#22 0.440 ./createdb: importing import/redis_1643761044.rdb.gz
#22 1.867 /etc/init.d/mariadb: ERROR: The partition with /var/lib/mysql is too full! ... failed!
------
executor failed running [/bin/sh -c ./createdb]: exit code: 1
```

There seems to be a workaround of sorts in https://stackoverflow.com/questions/37100065/resize-disk-usage-of-a-docker-container but it apparently affects all your Docker containers.

**Comment by tripleee** [comment]
Notice that the `Dockerfile` does `COPY . .` so if you have temporary files you are not using for anything (such as previous imports!) those will be copied into the image, too.

**Comment by teward** [comment]
I'm confused, are you saying that this is a problem with the database being large, or that it's a problem with the Docker image?

If this is an issue with Docker containers not being provisioned large enough, that sounds more like an issue with your Docker daemon not provisioning enough and thus something that has to be handled on the Docker daemon side of things.  just my 2 cents.

**Comment by tripleee** [comment]
> If this is an issue with Docker containers not being provisioned large enough, that sounds more like an issue with your Docker daemon not provisioning enough and thus something that has to be handled on the Docker daemon side of things. just my 2 cents.

This is indeed the obvious workaround, but Docker out of the box defaults to 10G disk images; it would be nice to be able to stay within this limit.
