### ISSUE TITLE
domyhomework.us domain page broke

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#903]
I tried to link https://metasmoke.erwaysoftware.com/domains/90854 to allassignmenthelp.com but adding the link somehow broke the page to the point where it only displays a traceback.

Similar to #897 - I'll see if I can apply the repair steps from there.

**Comment by tripleee** [comment]
https://metasmoke.erwaysoftware.com/data/sql/queries/291-domain-links-on-domain-page?domain_id=90854 shows which items to remove.

**Comment by makyen** [comment]
I deleted these. There were a couple more entries with the same problem, which I took care of too.

Here's a bookmarklet which will prompt you for a domain link ID to delete:
```
javascript:void((function(){
    function deleteMSDomainLink(domainLinkId) {
        if (domainLinkId) {
            const authenticity_token = $(document.head).find('meta[name="csrf-token"]').attr('content').trim();
            if (!authenticity_token) {
                alert('ABORTING: Unable to determine authenticity_token');
                return;
            }
            const _method = 'delete';
            $.post(`https://metasmoke.erwaysoftware.com/domains/links/${domainLinkId}`, {authenticity_token, _method});
        }
    }
    domainLinkId = ((prompt('What is the ID of the domain link you want to delete?') || '').match(/\d+/) || [])[0];
    if (domainLinkId && confirm(`Are you sure you want to delete domain link ID: ${domainLinkId}`)) {
        deleteMSDomainLink(domainLinkId);
    }
})());
```
