### ISSUE TITLE
Deletion watcher missing some messages?

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#928]
### What problem has occurred? What issues has it caused?

Shadow complained about a message which got reported in the Tavern even though it was already deleted.

Speculations abound, but the message still isn't reported as deleted in metasmoke.

https://chat.meta.stackexchange.com/transcript/message/9228055#9228055

### What would you like to happen/not happen?

The deletion watcher should have noticed that the message was deleted, and ideally have removed the message from the Tavern if it was posted before the message was deleted, or else not have posted it at all.

**Comment by makyen** [comment]
This appears to be entirely about deleting or not posting SD reports in chat when a post has been deleted, rather than something on MS. So, this is actually an SD issue. However, as far as I'm aware this has been resolved. So, rather than move it to the SD repo, I'm just going to close it.
