### ISSUE TITLE
metasmoke.charcoal-se.org points to the wrong IP address

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#93]
SOA points to Cloudflare, not sure who has access to the DNS settings to update this?

```
ordinatrix$ dig +short metasmoke.charcoal-se.org.
34.197.90.29

ordinatrix$ dig +short metasmoke.erwaysoftware.com.
54.236.78.156

```

Only the latter works at the moment.

**Comment by tripleee** [comment]
NVM, Art was already on it. http://chat.stackexchange.com/transcript/message/35445589#35445589

**Comment by ArtOfCode-** [comment]
Anything on charcoal-se.org is ultimately me
