### ISSUE TITLE
Add a bit of non-clickable space between the "Add feedback" options on MS reports

### ISSUE THREAD

**Issue by jeffschaller** [Charcoal-SE/metasmoke#933]
While reviewing posts on mobile, I ([and others](https://chat.stackexchange.com/search?q=misclick&room=11540)) often misclick, causing temporary confusion. I wonder if a bit of non-clickable space between the "Add feedback" icons would help our aim?

**Comment by jeffschaller** [comment]
![This is the area](https://i.stack.imgur.com/oBBeB.jpg)

**Comment by BuyakzLu** [comment]
I was wondering if you know the real name of this Individual? : https://stackoverflow.com/users/1014587/mast?tab=profile
He claimed hes part of the charcoal project, It's been a week and I still haven't cool down after what this guy said to me in a stackoverflow question. So it would be awesome if you could tell me the real name and address of this guy I've been burning resources and been to a lot of forum just trying to find who this guy is. Please let me know you would help me a lot, thank you.
