### ISSUE TITLE
Annotate Flagging graph

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/metasmoke#94]
Can the graph on [this](https://metasmoke.erwaysoftware.com/flagging) page accept annotations? If so, if there a way to annotate Feb 14, 2017 as the day max flags jumped from 1 to 3? That'd be helpful in the future.

**Comment by Undo1** [comment]
![screen shot 2017-02-21 at 9 12 04 am](https://cloud.githubusercontent.com/assets/5162342/23173269/dea3a38e-f815-11e6-9cea-b44ede8e6f34.png)
