### ISSUE TITLE
`deleted_at` is not available in the filters

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/metasmoke#97]
The [`posts/urls`](https://github.com/Charcoal-SE/metasmoke/wiki/Posts-by-URLs) end point includes a `deleted_at` attribute when no filter is provided to the path. This attribute is not listed on the [filters](https://metasmoke.erwaysoftware.com/api/filters) page. 

Request: Add it to the filters page and do NOT remove it from the default attributes returned on the above route.

**Comment by Undo1** [comment]
It's a generated column. #96 needs to be implemented first.

**Comment by AWegnerGitHub** [comment]
I didn't realize it was generated. Good to know.

Rational for requesting that it remains - I am using the field to generate this data: http://chat.stackexchange.com/transcript/message/35493118#35493118
