### ISSUE TITLE
Review: Solicit feedback for low-weight spam with only one feedback

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#99]
Since the introduction of multiple autoflags, we seem to be receiving much less feedback on spam posts.

My suggestion would be to queue recent alerts with a single piece of feedback and a low weight to the Review tab, perhaps only when the user has otherwise reviewed the items which would have been shown there.

**Comment by ArtOfCode-** [comment]
As long as a post has at least one feedback, that's fine - and review is doing a good job of that already.
